from . import cemetery_application
from . import cemetery_cemetery
from . import cemetery_section
from . import grave_grave
from . import province_province
from . import municipality_municipality
from . import res_users
from . import res_partner
from . import cemetery_tag
from . import cause_death
from . import death_register
from . import funeral_parlour
from . import grave_booking
from . import crematorium_crematorium
from . import sale_order
from . import account_move
from . import product_template
from . import undertaker_undertaker
