{
    'name': "Website Design",
    'description': """Website Design""",
    'summary': """Website Design""",
    'version': '19.0.1.0.0',
    'category': 'Theme/eCommerce',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'depends': ['website', 'base', 'web','website_blog'],
    'data': [
        'data/attachment.xml',
        'data/blog_blog.xml',
        'data/website_about_us_pages.xml',
        'data/website_services_pages.xml',
        'data/website_supply_chain_pages.xml',
        'data/website_careers_people.xml',
        'data/website_menu.xml',
        'views/website_template.xml',
    ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
