# -*- coding: utf-8 -*-
{

    'name': "Esubmission",
    'version': '16.0.1.0.0',
    "summary": "Manage internal memos,circular and procurement with approval, signature, and acknowledgment",
    'category': 'Services',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': "https://natedsystems.co.za",
    "depends": ["base", "hr", "mail", "sign", "documents", "xf_partner_contract", "web", ],
    "data": [
        "security/memo_security.xml",
        "security/sign_request_security.xml",
        "security/ir.model.access.csv",
        "data/memo_sequence.xml",
        "data/circular_sequence.xml",
        "data/procurement_sequence.xml",
        "data/email_template.xml",
        "wizard/memo_email_wizard_views.xml",
        "wizard/signature_wizard_views.xml",
        "wizard/memo_action_wizard_view.xml",
        'report/memo_template.xml',
        'report/memo_report.xml',
        "views/memo_views.xml",
        "views/memo_dashboard_views.xml",
        "views/circular_dashboard_views.xml",
        "views/procurement_dashboard_views.xml",
        "views/memo_menu.xml",
        "views/memo_template_views.xml",
        "views/memo_portal_template.xml",
        "views/sign_request_action.xml",
    ],
    'qweb': [],
    'images': [],
    'license': 'OEEL-1',
    'installable': True,
    'application': True,
    'auto_install': False,
}
