from . import client_enquiry
from . import enquiry_assessment
from . import assessment_valuation
from . import building
from . import committee_meeting
from . import helpdesk_team
from . import res_partner
from . import ir_attachment
from . import client_enquiry_sla_status
from . import circulation_comments
from . import client_transaction
from . import eac_process
from . import property_acqucition
from . import property_legal
from . import land_regularization
from . import approval_request
from . import mail_therad
from . import client_enquiry_sla_policy
from . import res_groups
from . import document_document

