{
    'name': "Client Enquiry",
    'description': """Client Enquiry""",
    'summary': """Client Enquiry""",
    'version': '16.0.5.2.0',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'sequence': '20',
    'category': 'Services',
    'depends': ['helpdesk', 'itsys_real_estate', 'portal', 'base', 'law_firm_bits', 'project',
                'document_update', 'committee_meeting_management', 'sign','approvals'],
    'data': [
        'data/client_enquiry_data.xml',
        'data/documents_folder_data.xml',
        'data/res_users_data.xml',
        'data/circulation_comments_data.xml',

        'data/mail_template_data.xml',
        'data/committee_data.xml',
        'data/mail_template_circulation.xml',
        'data/enquiry_team_data.xml',
        'data/client_enquiry_sla_policy_data.xml',
        'security/client_enquiry_security.xml',
        'security/ir.model.access.csv',
        'reports/enquiry_sla_policy_status_reports.xml',
        'views/res_partner_views.xml',
        'views/client_enquiry_views.xml',
        'views/client_enquiry_sla_policy.xml',
        'views/client_enquiry_sla_policy_status.xml',
        'views/land_regularization.xml',
        'views/enquiry_assessment_views.xml',
        'views/assessment_valuation_views.xml',
        'views/approval_request_views.xml',
        'views/building_views.xml',
        'views/committee_meeting_views.xml',
        'views/helpdesk_team_views.xml',
        'views/client_enquiry_sla_status_views.xml',
        'views/circulation_comments_views.xml',
        'views/client_transaction_views.xml',
        'views/eac_process_views.xml',
        'views/property_acquisition_views.xml',
        'views/property_legal_views.xml',
        'views/building_no_update.xml',
        'views/client_enquiry_menus.xml',

        'wizard/assessement_objection_views.xml',
        'wizard/valuation_form_view.xml',
        'wizard/scm_valuation_views.xml',
        'wizard/owenship_verification_views.xml',
        'wizard/check_ownership_views.xml',
        'wizard/assessment_transaction_views.xml',
        'wizard/assessment_meeting_views.xml',
        'wizard/upload_meeting_report_views.xml',
        'wizard/enquiry_sla_policy_status_reports_views.xml',
        'wizard/upload_property_report_views.xml',
        'wizard/acqusition_comments_views.xml',
        'wizard/legal_missing_document_views.xml',

    ],
    'assets': {
        'web.assets_frontend': [
            'client_enquiry/static/src/js/client_enquiry_file_upload.js',
            'client_enquiry/static/src/scss/client_enquiry.scss',
        ],
        'web.assets_backend': [
            'client_enquiry/static/src/js/action_manager.js',
            'client_enquiry/static/src/xml/list_controller.xml'
        ],
    },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
