# -*- coding: utf-8 -*-
{
    'name': "Project Portfolio Management",
    'version': '18.0.1.0.0',
    "summary": "Project Portfolio Management",
    'category': 'Services',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': "https://natedsystems.co.za",
    "depends": ["project", "hr", 'analytic', 'timesheet_grid', 'account_budget', "calendar","mail"],
    "data": [
        'data/sequence_data.xml',
        'data/dashboard_link_data.xml',
        'security/ir.model.access.csv',
        'views/dashboard.xml',
        'views/project_project_views.xml',
        'views/project_phase_views.xml',
        'views/health_indicator_views.xml',
        'views/project_comments_views.xml',
        'views/project_documents_views.xml',
        'views/governance_requirments_views.xml',
        'views/project_approval_views.xml',
        'views/project_cost_views.xml',
        'views/project_risk_views.xml',
        'views/project_tasks_views.xml',
        'views/resource_allocation_views.xml',
        'views/scope_changes_views.xml',
        'views/resources_views.xml',
        'views/portfolio_management_views.xml',
        'views/programme_management_views.xml',
        'views/pm_intake_views.xml',
        'views/pm_scoring_views.xml',
        # 'views/analytic_account_views.xml',

        'views/project_decisions_views.xml',
        'views/project_issues_views.xml',
        'views/project_phase_views.xml',
        'report/alert_and_reminder_report.xml',
        "wizard/project_report_views.xml",
        'wizard/project_dashboard_link_wizard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'project_porfolio_management/static/src/js/dashboard.js',
            'project_porfolio_management/static/src/js/chart_chart.js',
            'project_porfolio_management/static/src/css/dashboard_new.css',
            'project_porfolio_management/static/src/xml/dashboard_templates.xml',
        ],
    },
    'images': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
