{
    'name': "Asset Verification Report",
    'description': """Asset Verification Report""",
    'summary': """Asset Verifications Report""",
    'version': '18.0.1.0.0',
    'sequence': '20',
    'category': 'Accounting',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'depends': ['asset_verification', 'account_asset', 'fixed_assets',
                'asset_registry','asset_project', "asset_movement"],
    'data': [
        'security/ir.model.access.csv',
        'report/asset_verification_report.xml',
        'report/asset_register_report.xml',
        'report/assets_disposal_report.xml',
        'report/report_asset_location_history.xml',
        'report/asset_register_location_report.xml',

        'wizard/assets_verification_wizard_views.xml',
        'wizard/asset_register_report_views.xml',
        'wizard/assets_disposal_report_views.xml',
        'wizard/asset_register_location_report_views.xml',
        "views/asset_reports.xml",
        "views/account_asset.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'asset_verification_report/static/src/js/asset_dashboard.js',
            'asset_verification_report/static/src/xml/asset_dashboard_template.xml',
            'asset_verification_report/static/src/js/asset_register.js',
            'asset_verification_report/static/src/js/asset_verification.js',
            'asset_verification_report/static/src/xml/asset_verification.xml',
            'asset_verification_report/static/src/xml/asset_register.xml',
            'asset_verification_report/static/src/xml/asset_disposed.xml',
            'asset_verification_report/static/src/js/asset_disposed.js',
            'asset_verification_report/static/src/scss/asset_dashboard.css',
        ],
    },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,

}
