{
    'name': "Asset Reports",
    'description': """Asset Reports""",
    'summary': """Asset Reports""",
    'version': '19.0.1.0.0',
    'sequence': '20',
    'category': 'Accounting',
    'depends': ['hr','account_asset', 'asset_disposal', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'report/asset_acquisition_report.xml',
        'report/asset_disposal_report.xml',
        'report/asset_impairment_report.xml',
        'report/asset_depreciation_report.xml',
        'report/asset_fully_depreciation_report.xml',
        'report/asset_rul_change_report.xml',
        'wizard/asset_acquisition_report_views.xml',
        'wizard/asset_disposal_report_views.xml',
        'wizard/asset_impairment_report_views.xml',
        'wizard/asset_depreciation_report_views.xml',
        'wizard/rul_change_report.xml',
        'wizard/asset_transfer_report.xml',
        # 'wizard/asset_useful_report_views.xml',
        'wizard/asset_report_views.xml',
        # 'wizard/asset_insurence_report_views.xml',
        'wizard/asset_register_report_views.xml',
        'wizard/asset_verification_report_views.xml',
        'wizard/asset_wip_report_wizard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'asset_reports/static/src/js/action_manager.js',
        ],
    },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,

}