{
    'name': "Recruitment Enhancement",
    'description': """Recruitment Enhancement""",
    'summary': """Recruitment Enhancement""",
    'version': '17.0.4.3.3',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': "https://natedsystems.co.za",
    'sequence': '20',
    'category': 'Services',
    'depends': ['mail', 'website', 'hr', 'contacts', 'survey',
                'l10n_be_hr_contract_salary', 'purchase',
                'hr_recruitment_extract', 'appointment_hr_recruitment',
                'hr_contract_salary_payroll',
                'website_hr_recruitment', 'hr_recruitment', 'portal',
                'documents_hr_recruitment',
                'hr_recruitment_reports', 'hr_recruitment_sign',
                'hr_recruitment_survey', 'spreadsheet_dashboard_hr_referral',
                'hr_referral',
                'hr_recruitment_skills'],
    'data': [

        'data/scheduled_action.xml',
        'data/mail_template_data.xml',
        'data/hr_recruitment_stage_data.xml',
        'data/ir_cron_data.xml',
        'data/applicant_feedback_template.xml',
        'data/interview_schedule.xml',
        'data/regret_template.xml',
        'data/advertise_email_template.xml',
        'security/ir.model.access.csv',
        'security/recruitment_enhancement_groups.xml',
        'views/res_partner_views.xml',
        'views/hr_applicant_views.xml',
        'views/hr_job_views.xml',
        'views/survey_survey_views.xml',
        'views/survey_user_input_view.xml',
        'views/survey_question_views.xml',
        'views/website_erratum_template.xml',
        'views/job_application_template.xml',
        'views/portal_job_template.xml',
        'views/survey_templates.xml',
        'views/res_users_portal_views.xml',
        'views/terms_conditions_template.xml',
        'views/website_erratum.xml',
        'views/hr_department_views.xml',
        'wizard/hr_job_revert_views.xml',
        'wizard/applicant_interview.xml',
        'report/job_advert_report.xml',
        'views/approval_team.xml',
        'views/approval_team_line.xml',
        'views/approver_role_views.xml',
        'views/hr_job_approval_views.xml',
        'data/approver_role_data.xml',
        'data/email_template.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            '/recruitment_enhancement/static/src/css/style.css',
            '/recruitment_enhancement/static/src/js/job_application_visibility.js'
        ],
    },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
