from . import res_partner
from . import hr_job
from . import hr_applicant
from . import survey_survey
from . import survey_question
from . import survey_user_input
from . import res_users_portal
from . import hr_applicant_skill
from . import website_erratum
from . import hr_department
from . import approver_role
from . import approval_team
from . import hr_job_approval
