# -*- coding: utf-8 -*-
{
    'name': "Recruitment Enhancement",
    'description': """Recruitment Enhancement""",
    'summary': """Recruitment Enhancement""",
    'version': '16.0.1.0.0',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'sequence': '20',
    'category': 'Services',
    'depends': [
        'base',
        'mail',
        'hr',
        'hr_skills',
        'hr_recruitment_skills',
        'hr_recruitment',
        'hr_recruitment_survey',
        'sign',
        'contacts',
        'website_hr_recruitment',
        'hr_contract_salary'
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/recruitment_media_data.xml',
        'data/document_type_data.xml',
        'data/email_template.xml',
        'data/hr_recruitment_stage_data.xml',
        'data/mail_activity_plan.xml',
        'wizard/requisition_signature_wizard_views.xml',
        'wizard/recruitment_requisition_interview_wizard.xml',
        'wizard/applicant_interview.xml',
        'views/recruitment_requisition_views.xml',
        'views/recruitment_shortlisting_views.xml',
        'views/recruitment_interview_views.xml',
        'views/recruitment_background_check_views.xml',
        'views/recruitment_offer_views.xml',
        'views/hr_applicant_views.xml',
        'views/hr_job_views.xml',
        'views/hr_employee.xml',
        'views/approver_role_views.xml',
        'views/hr_job_kpi.xml',
        'views/interview_evaluation.xml',
        'data/approver_role_data.xml',
        'views/res_users_portal_views.xml',
        'views/requisition_document.xml',
        'views/menuitems.xml',
        'views/survey_question_views.xml',
        'views/survey_survey_views.xml',
        'views/survey_user_input_view.xml',
        'views/survey_templates.xml',
        'views/job_application_template.xml',

        # 'report/custom_external_layout.xml',
        'report/job_advert_report.xml',
        'report/job_offer_letter.xml',
        'report/recruitment_job_advert.xml',
        'report/candidate_declaration_report.xml',
        'data/ir_cron_data.xml',

        'views/approval_team.xml',
        'views/approval_team_line.xml',
    ],
    'images': [],
    # 'assets': {
    #     'web.assets_frontend': [
    #         'recruitment_enhancement/static/src/js/survey_submit_confirmation.js',
    #         'recruitment_enhancement/static/src/js/job_application.js',
    #     ],
    # },
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
