{
    'name': 'Whatsapp Odoo for dashboard Integration (Meta)',
    'version': '16.0.0.0.8',
    'category': 'Connector',
    'summary': 'whatsapp connector whatsapp integration odoo Whatsapp crm Whatsapp lead Whatsapp task Whatsapp sale order Whatsapp purchase order Whatsapp invoice Whatsapp payment reminder Whatsapp pos Whatsapp so Whatsapp point of sale whats app communication',
    'description': """Whatsapp Odoo for dashboard Integration""",
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'depends': ['base', 'contacts', 'delivery', 'crm', 'project', 'sale_management', 'purchase_stock', 'website', 'phone_validation', 'pragtech_whatsapp_base'],
    'data': ['security/ir.model.access.csv',
             'wizard/send_wp_msg_views.xml',
             'views/res_config_settings_view.xml',
             'views/res_partner_views.xml',
             'views/res_users.xml',
            #  'views/template_pos.xml',
             'views/whatsapp_scheduler.xml',
             'security/security.xml',
             'security/sale_security.xml',
             'views/login_template.xml',
             'views/whatsapp_message_view.xml',
             'views/whatsapp_instance_view.xml',
             'views/mail_message_view.xml',
             'views/res_partner_views.xml',
             'views/sale_order_view.xml',
             'views/account_invoice_views.xml',
             'views/stock_picking_views.xml',
             'views/purchase_order_view.xml',
             'views/project_task_view.xml',
             'views/default_answers.xml',
             'views/account_payment_view.xml',
             'views/ir_attachment_view.xml'],
    'qweb': [],
    'assets': {
        'web.assets_backend': [],
    },
    'license': 'OPL-1',
    'application': False,
    'auto_install': False,
    'installable': True,
}
