# -*- coding: utf-8 -*-
{
    'name': 'JHBProperty Studio Update',
    'version': '19.0.1.0.0',
    "category": "Base",
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    "license": "LGPL-3",
    "application": True,
    "installable": True,
    "auto_install": False,
    'description': u"""
This module contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'City of Joburg Property Company Soc Ltd',
    'depends': [
        'account',
        'accountant',
        'account_asset',
        'account_budget',
        'account_reports',
        'analytic',
        'approvals',
        'asset_approval',
        'asset_dashboard',
        'asset_impairment',
        'asset_registry',
        'asset_reports',
        'asset_verification',
        'asset_verification_report',
        'base',
        'client_enquiry',
        'documents',
        'e_system',
        'frontdesk',
        'helpdesk',
        'hr',
        'hr_attendance',
        'hr_timesheet',
        'itsys_real_estate',
        'itsys_real_estate_approval',
        'itsys_real_estate_conditional_assessment',
        'jhbproperty_land_process',
        'law_firm_bits',
        'property_intelligence',
        'property_update',
        'purchase',
        'servitude_register',
        'seta_data',
        'sign',
        'valuation_roll_import',
        'web_studio',
        'xf_partner_contract',
    ],
    'data': [
        'views/actions.xml',
        'views/menu.xml',
        'views/view.xml',
    ],
}
