{
    'name': "Property Maintenance Management",
    'description': """Property Maintenance Management""",
    'summary': """Property Maintenance Management""",
    'version': '19.0.1.0.0',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'sequence': '20',
    'category': 'Services',
    'depends': ['helpdesk', 'website', 'itsys_real_estate', 'stock', 'project','industry_fsm','maintenance'],
    'data': [
        'data/helpdesk_stage_data.xml',
        'data/helpdesk_team_data.xml',
        'data/project_task_type_data.xml',
        'data/helpdesk_sla_data.xml',
        'security/ir.model.access.csv',
        'security/facility_manager_groups.xml',
        # 'security/client_enquiry_security.xml',
        # 'views/client_enquiry_views.xml',
        'views/maintenance_request_templates.xml',
        'views/maintenance_requests_view.xml',
        'views/building.xml',
        'views/helpdesk_ticket.xml',
        'views/job_card_view.xml',
        'views/inspection_details_views.xml',
        'views/project_task_views.xml',
        'views/job_card_template.xml',
        'views/project_portal_templates_updates.xml',
        'views/helpdesk_sla.xml',
        # 'views/project_portal_task_templates.xml',
        'wizard/job_card_decline.xml',
        'report/ir_actions_report.xml',
        # 'report/worksheet_custom_report_templates_update.xml',
        # # 'wizard/inventory_required.xml',
        # # 'wizard/valuation_form_view.xml',
        # # 'wizard/scm_valuation_views.xml',
    ],
    # 'assets': {
    #         'web.assets_frontend': [
    #             'property_maintenance_management/static/src/css/project_portal_task_template.css',
    #             # 'age_verification_odoo/static/src/js/age_verification.js',
    #             # 'age_verification_odoo/static/src/js/session_remove.js',
    #         ],
    #     },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
