{
    'name': "Fixed Assets",
    'description': "Fixed Assets",
    'summary': "Fixed Assets",
    'version': '18.0.0.0.0',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'sequence': 20,
    'depends': [
        'account_asset',
        'asset_registry',
        'accountant',
        'asset_verification',
        # 'account_asset',
        'assets_disposal'
    ],
    'category': 'Services',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/asset_removal_wizard.xml',
        "views/res_config_settings.xml",
        'views/assets_views.xml',
        "views/account_asset_views.xml",
    ],
    'images': ['static/description/icon.png'],
    'demo': [],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
