from odoo import api, fields, models, _
from odoo.tools.safe_eval import safe_eval
from odoo.exceptions import ValidationError


class ProjectProject(models.Model):
    _inherit = 'project.project'

    # region_id = fields.Many2one('res.region', string='District - Region')
    municipality_id = fields.Many2one('res.municipality', string='Municipality')
    intervention = fields.Selection(
        [("FINANCIAL", "FINANCIAL"), ("INCREMENTAL", "INCREMENTAL"), ("RURAL", "RURAL"),
         ("SOCIAL_RENTAL", "SOCIAL_RENTAL")], string="Intervention")
    sub_intervention = fields.Selection(
        [("EASTERN CAPE PROVINCIAL","EASTERN CAPE PROVINCIAL"),
         ("FINANCIAL  - 1.1b INDIVIDUAL HOUSING SUBSIDIES (NON CREDIT LINKED) (R 0 - R 3 500)",
          "FINANCIAL - 1.1b INDIVIDUAL HOUSING SUBSIDIES (NON CREDIT LINKED) (R 0 - R 3 500)"),
         ("FINANCIAL - 1.2 HOUSING FINANCE LINKED INDIVIDUAL SUBSIDY PROGRAMME",
          "FINANCIAL - 1.2 HOUSING FINANCE LINKED INDIVIDUAL SUBSIDY PROGRAMME"),
         ("FINANCIAL   - 1.3 ENHANCED EXTENDED DISCOUNT BENEFIT SCHEME (EEDBS)",
          "FINANCIAL - 1.3 ENHANCED EXTENDED DISCOUNT BENEFIT SCHEME (EEDBS)"),
         ("FINANCIAL - 1.4 STATE ASSET MAINTENANCE PROGRAMME", "FINANCIAL - 1.4 STATE ASSET MAINTENANCE PROGRAMME"),
         ("FINANCIAL  -1.5a RECTIFICATION OF RDP STOCK POST 1994 - 2002",
          "FINANCIAL  -1.5a RECTIFICATION OF RDP STOCK POST 1994 - 2002"),
         ("FINANCIAL - 1.5b RECTIFICATION OF RDP STOCK PRE 1994",
          "FINANCIAL - 1.5b RECTIFICATION OF RDP STOCK PRE 1994"),
         ("FINANCIAL  - 1.6 SOCIAL AND ECONOMIC FACILITIES", "FINANCIAL - 1.6 SOCIAL AND ECONOMIC FACILITIES"),
         ("FINANCIAL - 1.7 ACCREDITED MUNICIPALITIES (LEVEL 1 & 2)",
          "FINANCIAL - 1.7 ACCREDITED MUNICIPALITIES (LEVEL 1 & 2)"),
         ("FINANCIAL - 1.8 OPERATIONAL CAPITAL BUDGET", "FINANCIAL - 1.8 OPERATIONAL CAPITAL BUDGET"),
         ("FINANCIAL - 1.10 NHBRC ENROLMENT", "FINANCIAL - 1.10 NHBRC ENROLMENT"),
         ("FINANCIAL - 1.11a LAND PARCELS PROCURED", "FINANCIAL - 1.11a LAND PARCELS PROCURED"),
         ("FINANCIAL - 1.12 HOUSING CHAPTERS OF IDPS", "FINANCIAL - 1.12 HOUSING CHAPTERS OF IDPS"),
         ("INCREMENTAL - 2.1 PROJECT LINKED SUBSIDIES (CURRENT COMMITMENTS APPROVED UP TO 31/03/07)",
          "INCREMENTAL - 2.1 PROJECT LINKED SUBSIDIES (CURRENT COMMITMENTS APPROVED UP TO 31/03/07)"),
         ("INCREMENTAL - 2.2a INTEGRATED RESIDENTIAL DEVELOPMENT PROGRAMME: PHASE 1: PLANNING AND SERVICES",
          "INCREMENTAL - 2.2a INTEGRATED RESIDENTIAL DEVELOPMENT PROGRAMME: PHASE 1: PLANNING AND SERVICES"),
         ("INCREMENTAL - 2.2c  INTEGRATED RESIDENTIAL DEVELOPMENT PROGRAMME: PHASE 2: TOP STRUCTURE CONSTRUCTION",
          "INCREMENTAL - 2.2c  INTEGRATED RESIDENTIAL DEVELOPMENT PROGRAMME: PHASE 2: TOP STRUCTURE CONSTRUCTION"),
         ("INCREMENTAL - 2.3a PEOPLES HOUSING PROCESS", "INCREMENTAL - 2.3a PEOPLES HOUSING PROCESS"),
         ("INCREMENTAL - 2.5a CONSOLIDATION SUBSIDIES (EXCLUDING BLOCKED PROJECTS)",
          "INCREMENTAL - 2.5a CONSOLIDATION SUBSIDIES (EXCLUDING BLOCKED PROJECTS)"),
         ("INCREMENTAL - 2.6 EMERGENCY HOUSING ASSISTANCE", "INCREMENTAL - 2.6 EMERGENCY HOUSING ASSISTANCE"),
         ("RURAL - 4.2 RURAL SUBSIDY COMMUNAL LAND RIGHTS", "RURAL - 4.2 RURAL SUBSIDY COMMUNAL LAND RIGHTS"),
         ("SOCIAL_RENTAL - 3.1 INSTITUTIONAL SUBSIDIES", "SOCIAL_RENTAL - 3.1 INSTITUTIONAL SUBSIDIES"),
         ("SOCIAL_RENTAL - 3.2a SOCIAL HOUSING: OPERATIONAL SUPPORT",
          "SOCIAL_RENTAL - 3.2a SOCIAL HOUSING: OPERATIONAL SUPPORT"),
         ("SOCIAL_RENTAL - 3.3a COMMUNITY RESIDENTIAL UNITS  CONVERTED / UPGRADED",
          "SOCIAL_RENTAL - 3.3a COMMUNITY RESIDENTIAL UNITS  CONVERTED / UPGRADED"),
         ('SOCIAL_RENTAL - 3.1 INSTITUTIONAL SUBSIDIES', 'SOCIAL_RENTAL - 3.1 INSTITUTIONAL SUBSIDIES')],
        string="Sub Intervention")
    hss_project_number = fields.Char(string="HSS Project Number")
    total_annual_no_of_units = fields.Integer("Total Annual No. Of Units", default=0)
    total_annual_no_of_sites = fields.Integer("Total Annual No. Of Sites", default=0)

    @api.constrains('hss_project_number')
    def _check_hss_project_number_unique(self):
        for project in self:
            if project.hss_project_number and self.env['project.project'].search_count(
                    [('hss_project_number', '=', project.hss_project_number)]) > 1:
                raise ValidationError(_('Another Project already has this HSS project number'))
