# -*- coding: utf-8 -*-
{
    'name': "Portal Account",
    'description': """Portal Account""",
    'summary': """Portal Account""",
    'version': '19.0.1.0.0',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'sequence': '20',
    'category': 'Services',
    'depends': ['web', 'sale', 'portal', 'purchase', 'client_enquiry', 'project', 'helpdesk'],
    'data': [
        'security/helpdesk_security.xml',
        'views/portal_views.xml',
        'views/enquiry_assessment_portal_template.xml',
        'views/circulation_comment_portal_template.xml',
        'views/transaction_portal_template.xml',
        'views/eac_process_portal_template.xml',
        'views/assessment_valuation_portal_template.xml',
        'views/property_intelligence_portal_template.xml',
        'views/land_regulariztion_portal_template.xml',
        'views/client_enquiry_portal_template.xml',
        'views/legal_portal_template.xml',
    ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
