# -*- coding: utf-8 -*-
{
    'name': "Supply Chain Management",
    'description': """Supply Chain Management""",
    'summary': """Supply Chain Management""",
    'version': '18.0.1.0.0',
    'sequence': '20',
    'category': 'Purchase',
    'depends': ['purchase'],
    'data': [
    'security/supply_chain_management_group.xml',
    'security/ir.model.access.csv',
    'data/ir_sequence_data.xml',
    # 'data/committee_data.xml',
    # Commended this because of dupilcation document folder.
    # 'data/documents_data.xml',
    'data/supply_chain_sub_classification_type_data.xml',
    'data/supply_document_classification_type.xml',
    'views/purchase_requisition_views.xml',
    # 'views/committee_meeting_views.xml',
    'views/bsc_memo_views.xml',
    'views/supply_chain_classification_type.xml',
    'views/supply_chain_sub_classification_type.xml',
    # 'views/purchase_order_views.xml',
    'report/purchase_requisition_report.xml',
    'report/independent_auditor_report.xml',
    'wizard/tender_advertisment_views.xml',
    'wizard/bid_evaluation_views.xml',
    'wizard/edc_evaluation_views.xml',
    'wizard/supply_chain_documents.xml'
],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
