{
    'name': "Asset Registry",
    'description': """Asset Registry""",
    'summary': """Asset Registry""",
    'version': '16.0.1.0.0',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'sequence': '20',
    'category': 'Accounting',
    'depends': ['base', 'account_asset', 'stock', 'account', 'purchase', 'asset_useful_life', 'asset_approval'],
    'data': [
        # 'data/journal_data.xml',
        'data/account_asset_data.xml',
        'data/ir_cron_data.xml',
        # 'data/asset_export_server_action.xml',
        # 'security/asset_registration_security.xml',
        'security/asset_groups.xml',
        'security/ir.model.access.csv',
        'report/asset_barcode_views.xml',
        'views/account_asset_form.xml',
        # 'report/asset_disposal_report.xml',
        # 'report/asset_depreciation_report.xml',
        'views/account_asset_views.xml',
        'views/asset_category_views.xml',
        'views/asset_dashboard_views.xml',
        # # 'views/account_account_views.xml',
        # 'views/project_segment_views.xml',
        # 'views/asset_dashboard_views.xml',
        # 'views/asset_transfer_department_views.xml',
        'wizard/asset_import_views.xml',
        # 'wizard/asset_lose_views.xml',
        'wizard/asset_modify.xml',
        # 'wizard/account_import_views.xml',
        # 'wizard/asset_addition_views.xml',
        'wizard/asset_impairment_views.xml',
        # 'wizard/asset_transfer_views.xml',
        # 'wizard/asset_depreciation_views.xml',
    ],
    # 'assets': {
    #     'web.assets_backend': [
    #         'asset_registration/static/src/js/action_manager.js',
    #     ],
    # },
    # 'external_dependencies': {
    #     'python': ['openpyxl'],
    # },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,

}
