{
    'name': "Client Enquiry",
    'description': """Client Enquiry""",
    'summary': """Client Enquiry""",
    'version': '18.0.1.0.0',
    'sequence': '20',
    'category': 'Services',
    'depends': ['helpdesk', 'portal', 'base','document_retention_update',  'sign'],
    'data': [
        'data/client_enquiry_data.xml',
        # 'data/document_folder.xml',
        'data/res_users_data.xml',
        'data/mail_template_data.xml',
        # 'data/committee_data.xml',
        'data/enquiry_team_data.xml',
        'data/client_enquiry_sla_policy_data.xml',
        'security/client_enquiry_security.xml',
        'security/ir.model.access.csv',
        'reports/enquiry_sla_policy_status_reports.xml',
        'views/res_partner_views.xml',
        'views/client_enquiry_views.xml',
        # 'views/client_enquiry_templates.xml',
        'views/enquiry_assessment_views.xml',
        'views/assessment_valuation_views.xml',
        # 'views/enquiry_assessment_portal_templates.xml',
        # 'views/building_views.xml',
        # 'views/committee_meeting_views.xml',
        'views/helpdesk_team_views.xml',
        'views/client_enquiry_sla_status_views.xml',

        'wizard/assessement_objection_views.xml',
        'wizard/valuation_form_view.xml',
        'wizard/scm_valuation_views.xml',
        'wizard/check_ownership_views.xml',
        'wizard/assessment_transaction_views.xml',
        'wizard/assessment_meeting_views.xml',
        'wizard/upload_meeting_report_views.xml',
        'wizard/enquiry_sla_policy_status_reports_views.xml',

    ],
    'assets': {
        'web.assets_frontend': [
            'client_enquiry/static/src/js/client_enquiry_file_upload.js',
            'client_enquiry/static/src/scss/client_enquiry.scss',
        ],
        'web.assets_backend': [
            'client_enquiry/static/src/js/action_manager.js',
        ],
    },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
