{
    'name': "Asset Registration",
    'description': """Asset Registration""",
    'summary': """Asset Registration""",
    'version': '16.0.1.1.0',
    'sequence': '20',
    'category': 'Accounting',
    'depends': ['base', 'account_asset', 'account_accountant', 'stock', 'account', 'purchase', 'maintenance'],
    'data': [
        'data/asset_category_data.xml',
        'data/account_asset_data.xml',
        # 'data/asset_export_server_action.xml',
        'security/asset_registration_security.xml',
        'security/ir.model.access.csv',
        'report/asset_disposal_report.xml',
        'report/asset_depreciation_report.xml',
        'views/account_asset_views.xml',
        'views/asset_category_views.xml',
        # 'views/account_account_views.xml',
        'views/project_segment_views.xml',
        'views/asset_dashboard_views.xml',
        'views/asset_transfer_department_views.xml',
        'wizard/asset_import_views.xml',
        # 'wizard/asset_lose_views.xml',
        'wizard/asset_export_views.xml',
        'wizard/account_import_views.xml',
        'wizard/asset_addition_views.xml',
        'wizard/asset_impairment_views.xml',
        'wizard/asset_transfer_views.xml',
        'wizard/asset_depreciation_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'asset_registration/static/src/js/action_manager.js',
        ],
    },
    # 'external_dependencies': {
    #     'python': ['openpyxl'],
    # },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,

}