{
    'name': 'TOMS',
    'version': '19.0.1.0.0',
    'author': 'Humint',
    'website': "www.humint.co.za",
    'depends': ['base', 'sale_management', 'calendar', 'sms_frame', 'account', 'stock', 'crm',
                'project', 'sale_stock', 'sms',
                'purchase', 'oehealth' ],
    'application': True,
    'data': [
        'data/ir_sequence_data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/toms_demo_data.xml',
        # 'views/assets.xml',
        'views/res_partner.xml',
        # 'views/child_form.xml',
        'views/medical_aid_plan.xml',
        'views/medical_codes.xml',
        'views/product_template.xml',
        'data/humint_language.xml',
        'data/humint_occupation.xml',
        'data/humint_title.xml',
        'data/codes.xml',
        'data/automated_actions.xml',
        'data/paper_formats.xml',
        # 'views/calendar_event.xml',
        'views/clinic_examination.xml',
        'views/res_partner_contact.xml',
        'views/clinical_menus.xml',
        'views/purchase_order.xml',
        'views/payment_pivot.xml',
        'views/product_pricelist_views.xml',
        'wizard/crm_lead_lost_wizard.xml',
        # 'views/account_invioce.xml',
        # 'report/customer_invoice.xml',
        # 'report/product_report.xml',
        # 'report/custom_productlabel.xml',
        # 'report/custom_product_label_shipment.xml',
        'report/job_report.xml',
        # 'report/tray_label.xml',
        # 'views/project_task.xml',
        'views/res_config_settings.xml',
        'wizard/wizard_final_rx.xml',
        'wizard/project_fitting_detail.xml',
        'wizard/detaching_dependent_wizard.xml',
        'wizard/wizard_receive_product.xml',
        'data/cron_recall_customer.xml',
        'views/res_company.xml',
        'views/appointment_view.xml',
        'views/res_users.xml',
        # 'views/stock_views.xml',
        # 'views/adjustment_lines.xml',
        'views/account_account.xml',
        'wizard/wizard_stock_take_validate.xml',
        'views/medical_aid_confrimations.xml',
        'views/project_views.xml',
        # 'views/account_journal.xml',
        'report/invoice_normal_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # '/TOMS/static/src/xml/roster_view.xml',
            # '/TOMS/static/src/xml/payment.xml',
            '/TOMS/static/src/css/scheduler.css',
            '/TOMS/static/src/css/fullcalendar.css',
            '/TOMS/static/src/css/bootstrap-colorpicker.min.css',
            '/TOMS/static/src/css/bootstrap-datepicker.css',
            '/TOMS/static/src/css/spectrum.css',
            # '//cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.11/moment-timezone-with-data.js',
            # '/TOMS/static/src/js/fullcalendars.js',
            # '/TOMS/static/src/js/scheduler.js',
            # '/TOMS/static/src/js/resource_view.js',
            # '/TOMS/static/src/js/kanban_image.js',
            '/TOMS/static/src/js/bootstrap-colorpicker.js',
            # '/TOMS/static/src/js/spectrum.js',
            # '/TOMS/static/src/js/color_picker.js',
            '/TOMS/static/src/css/style.css',
            '//TOMS/static/src/js/main.js',
            # '/TOMS/static/src/js/global_fetch.js',

        ],
    },
    'installable': True,
    'auto_install': False,
    'post_init_hook': 'post_init_check'
}
