from werkzeug import urls

from odoo import api, fields, models, _


class ProjectTask(models.Model):
    """Project Task"""
    _inherit = 'project.task'

    stages = fields.Selection([
        ('preparer', 'Preparer'),
        ('first_reviewer', 'First Reviewer'),
        ('second_reviewer', 'Second Reviewer'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ], 'State', default='preparer', tracking=True)
    sub_task_count = fields.Integer(string="Sub Task Count", compute="_compute_sub_task_count")
    reference_number = fields.Char(string="Reference Number")

    audit_steps = fields.Html(string="Audit Steps",
                              help="Detailed steps and procedures to be followed during the audit.")

    guidance = fields.Html(
        string="Guidance",
        help="Provide specific instructions or guidelines for the audit process."
    )

    work_done = fields.Html(
        string="Work Done",
        help="Record the work completed during the audit process."
    )

    attachment_id = fields.Many2many('ir.attachment', 'attachment_rel',
                                     help="The file generated by edi_format_id when the invoice is posted (and this document is processed)."
                                     )
    upload_document_name = fields.Char(related='attachment_id.name')

    sample_selection = fields.Html(
        string="Sample Selection",
        help="Details about the sample selection criteria and process used for auditing."
    )

    conclusion = fields.Html(
        string="Conclusion",
        help="Summarize the findings and outcomes of the audit."
    )
    upload_report_document_name = fields.Char('Upload Document Name', help="Uploaded report document")
    attachment_report_ids = fields.Many2many('ir.attachment', 'report_rel',
                                             string="Attachment", tracking=True)
    upload_draft_audit_document_name = fields.Char('Upload Document Name', help="Uploaded report document")
    attachment_draft_audit_ids = fields.Many2many('ir.attachment', 'audit_document_rel',
                                                  string="Attachment", tracking=True)

    upload_final_audit_document_name = fields.Char('Upload Document Name', help="Uploaded report document")
    attachment_final_audit_ids = fields.Many2many('ir.attachment', 'final_document_rel',
                                                  string="Attachment", tracking=True)
    upload_quality_assessment_document_name = fields.Char('Upload Document Name', help="Uploaded report document")
    attachment_quality_assessment_audit_ids = fields.Many2many('ir.attachment', 'quality_assessment_rel',
                                                               string="Attachment", tracking=True)
    documents = fields.Html(
        string="Documents",
        help="List or describe the documents reviewed or used during the audit."
    )
    request_documents = fields.Html(
        string="Request Documents",
        help="Details about the documents requested for the audit."
    )

    upload_document = fields.Binary(
        string="Upload Document",
        help="Upload relevant documents to be included in the audit."
    )
    attachment_notification_ids = fields.Many2many('ir.attachment', 'notification_rel',
                                                   string="Attachment", tracking=True)
    upload_notification_name = fields.Char(string="Name")
    comments = fields.Html(
        string="General Comments",
        help="Details about the General Comments."
    )
    audit_objective = fields.Html(
        string="Audit Objective",
        help="Details about the Audit  Objective."
    )
    special_instruction = fields.Html(
        string="Special  Instruction",
        help="Details about the Special  Instruction."
    )
    internal_audit_ids = fields.Many2many('res.users', string='Internal Audit Personal Assigned')
    auditor_id = fields.Many2one('res.users', string='Auditor In Charge')
    objective = fields.Html(string="Objective", help="Add the objective")
    rules = fields.Html(string="Add the Laws,Rules,Regulations,Policies and Procedures", help="Add the Laws")
    skill = fields.Html(string="Key Performance Area's", help="Add the performance areas")
    system_objective = fields.Html(string="Audit Objective", help="Add the objective for the audit")
    component_nature = fields.Html(string="Nature of Component", help="Add the component of nature")
    share_document = fields.Binary(
        string="Share Document",
        help="Share documents related to the audit with stakeholders."
    )
    references = fields.Html(
        string="References",
        help="Include references or citations used in the audit."
    )

    finding_raised = fields.Html(
        string="Finding Raised",
        help="Document the issues or findings identified during the audit."
    )

    type = fields.Many2one('task.type', default=lambda self: self._get_default_type())
    manager_id = fields.Many2one("res.users", string="Manager", tracking=True)
    audit_finding_ids = fields.Many2many('audit.finding',
                                         string="Audit Finding", tracking=True)
    hr_team_id = fields.Many2one('hr.department', string="Team", tracking=True)
    user_preparer_ids = fields.Many2one('res.users',
                                        string="Preparer", tracking=True, related='project_id.user_preparer_ids')
    user_reviewer_1_ids = fields.Many2one('res.users', string="First Reviewer", tracking=True,
                                          related='project_id.user_reviewer_1_ids')
    user_reviewer_2_ids = fields.Many2one('res.users', string="Second Reviewer ", tracking=True,
                                          related='project_id.user_reviewer_2_ids')
    user_approver = fields.Many2one('res.users', string="Approver", tracking=True, related='project_id.user_approver')
    user_approver_ids = fields.Many2many('res.users', 'user_approver_project_rel', string="Approver", tracking=True)
    control_assessment_ids = fields.One2many("control.assessment", 'project_control_id', string="Control Assessment")
    activity_description_ids = fields.One2many("activity.description", 'project_activity_description_id',
                                               string="Activity Description")
    professional_development_ids = fields.One2many("professional.development", 'professional_development_id',
                                                   string="Professional Development")
    time_budget_task_ids = fields.One2many("time.budget", 'task_time_id', string="Time Budget")
    state = fields.Selection([
        ('01_in_progress', 'In Progress'), ('02_changes_requested', 'Changes Requested'),
        ('03_approved', 'Approved'), ('1_done', 'Done'), ('1_canceled', 'Canceled'), ('04_waiting_normal', 'Waiting')],
        string='State')
    stages_id = fields.Many2one("project.task.type", string="Stages")
    survey_details = fields.One2many('survey.details', 'survey_details_id')
    memo_attachment_id = fields.Many2many('ir.attachment', 'memo_attachment_id', string="Upload Engagement Memorandum")
    audit_pgm_id = fields.One2many('audit.pgm', 'audit_details_id')
    mom_attachment_id = fields.Many2many('ir.attachment', 'mom_attachment_id',
                                         string="Upload Minutes of Meeting")
    client_survey_ids = fields.One2many('client.survey', 'client_survey_id')
    risk_ids = fields.Many2many('business.risk', string="Risk")
    task_type = fields.Selection([('plan_1', 'Plan 1'), ('plan_2', 'Plan 2'),
                                  ('plan_3', 'Plan 3'), ('plan_4', 'Plan 4'),
                                  ('plan_5', 'Plan 5'), ('plan_6', 'Plan 6'),
                                  ('plan_7', 'Plan 7'), ('plan_8', 'Plan 8'),
                                  ('plan_9', 'Plan 9'), ('plan_10', 'Plan 10'), ('exec_1', 'EXEC 1'),
                                  ('exec_2', 'EXEC 2'), ('exec_3', 'EXEC 3'),
                                  ('rep_1', 'REP 1'), ('rep_2', 'REP 2'),
                                  ('rep_3', 'REP 3'), ('rep_4', 'REP 4')], related="type.task_type")
    population_type = fields.Selection([('class_transaction',
                                         'Class of transactions and its related disclosures'),
                                        ('account_balance',
                                         'Account balance and its related disclosures'),
                                        ('disclosure_class_transaction',
                                         'Disclosure that is similar in nature to classes of transactions and events'),
                                        ('disclosure_account_balances',
                                         'Disclosure that is similar in nature to account balances')
                                        ])
    name_population = fields.Char(string="Name of the population")
    recorded_amount = fields.Float(string="Recorded amount")
    completeness = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Completeness")
    occurrence = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Occurrence")
    accuracy = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Accuracy")
    cut_off = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Cut-off")
    existence = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Existence")
    valuation = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Accuracy, valuation and allocation")
    obligations = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Rights and obligations")

    classification = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Classification")
    presentation = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Presentation")
    revised = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Materiality revised",
                               help="Indicate whether the preliminary materiality was revised during the course of the audit")
    preliminary_materiality_overall = fields.Float(string="Preliminary overall/ specific materiality")
    preliminary_performance_materiality = fields.Float(string="Preliminary performance materiality")
    revised_materiality_overall = fields.Float(string="Revised overall/ specific materiality")
    revised_performance_materiality = fields.Float(string="Revised performance materiality")
    final_materiality_overall = fields.Float(string="Final overall/ specific materiality")
    final_performance_materiality = fields.Float(string="Final performance materiality")
    level_assurance = fields.Selection([('1', '1'), ('2', '2'), ('3', '3')], string="Level of assurance",
                                       help="Level of assurance required from substantive tests of details")
    define_population = fields.Char(string="Define the population",
                                    help="Define the population; i.e. the entire set of data from which the sample will be drawn")
    define_sampling = fields.Char(string="Define the sampling",
                                  help="Define the sampling unit; i.e. the individual items of the sampling population")
    indicate_sample_selection = fields.Selection([
        ('random', 'Random selection'), ('systematic', 'Systematic selection'),
        ('haphazard', 'Haphazard selection'), ('monetary', 'Monetary unit sampling'),
        ('block', 'Block selection')], string="Indicate The Sample Selection",
        help="Indicate the sample selection method that will be used to select items for testing (e.g. haphazard, systematic, random, etc.): (Select from the drop-down menu.)")
    sample_size_3 = fields.Float(string="Sample Size",
                                 help="Sample size calculated per the formula (Level of assurance x Population amount ÷ Performance materiality)")
    mini_sample_size_3 = fields.Float(string="Minimum Sample Size", )
    final_sample_size_3 = fields.Float(string="Final sample size",
                                       help="Sample sizes based the population being audited")
    sample_size_2 = fields.Float(string="Sample Size",
                                 help="Sample size calculated per the formula (Level of assurance x Population amount ÷ Performance materiality)")
    mini_sample_size_2 = fields.Float(string="Minimum Sample Size", )
    final_sample_size_2 = fields.Float(string="Final sample size",
                                       help="Sample sizes based the population being audited")
    sample_size_1 = fields.Float(string="Sample Size",
                                 help="Sample size calculated per the formula (Level of assurance x Population amount ÷ Performance materiality)")
    mini_sample_size_1 = fields.Float(string="Minimum Sample Size", )
    final_sample_size_1 = fields.Float(string="Final sample size",
                                       help="Sample sizes based the population being audited")
    initial_sample_size = fields.Float(string="Initial Sample Size", )

    @api.model
    def _get_default_type(self):
        task_name = self.name
        task_type = self.env['task.type'].search([('name', 'ilike', f"%{task_name}%")], limit=1)
        return task_type.id if task_type else False

    @api.onchange('level_assurance', 'recorded_amount', 'preliminary_performance_materiality', 'mini_sample_size_2',
                  'mini_sample_size_3', 'mini_sample_size_1')
    def _onchange_sample_size(self):
        for rec in self:
            sample_size_3 = 0
            sample_size_2 = 0
            sample_size_1 = 0
            initial_sample_size = 0
            if rec.preliminary_performance_materiality:
                sample_size_3 = round((rec.recorded_amount * 3) / rec.preliminary_performance_materiality)
                sample_size_2 = round((rec.recorded_amount * 2) / rec.preliminary_performance_materiality)
                sample_size_1 = round((rec.recorded_amount * 1) / rec.preliminary_performance_materiality)
            rec.sample_size_3 = sample_size_3
            rec.final_sample_size_3 = sample_size_3 if sample_size_3 > rec.mini_sample_size_3 else rec.mini_sample_size_3
            rec.sample_size_2 = sample_size_2
            rec.final_sample_size_2 = sample_size_2 if sample_size_2 > rec.mini_sample_size_2 else rec.mini_sample_size_2
            rec.sample_size_1 = sample_size_1
            rec.final_sample_size_1 = sample_size_1 if sample_size_1 > rec.mini_sample_size_1 else rec.mini_sample_size_1
            if rec.level_assurance == '1':
                initial_sample_size = rec.final_sample_size_1
            if rec.level_assurance == '2':
                initial_sample_size = rec.final_sample_size_2
            if rec.level_assurance == '3':
                initial_sample_size = rec.final_sample_size_3
            rec.initial_sample_size = initial_sample_size

    @api.onchange('revised', 'preliminary_materiality_overall',
                  'preliminary_performance_materiality', 'revised_materiality_overall',
                  'revised_performance_materiality')
    def _onchange_materiality(self):
        """Onchange Materiality"""
        for rec in self:
            final_materiality_overall = rec.preliminary_materiality_overall
            final_performance_materiality = rec.preliminary_performance_materiality
            if rec.revised == 'yes':
                final_materiality_overall = rec.revised_materiality_overall if rec.revised_materiality_overall != 0 else rec.preliminary_materiality_overall
                final_performance_materiality = rec.revised_performance_materiality if rec.revised_performance_materiality != 0 else rec.preliminary_performance_materiality
            rec.final_materiality_overall = final_materiality_overall
            rec.final_performance_materiality = final_performance_materiality

    @api.onchange('hr_team_id')
    def _onchange_team_id(self):
        """Onchange Team"""
        for rec in self:
            user = []
            user_reviewer_2 = []
            user_approver = []
            users = []
            if rec.hr_team_id:
                users = rec.hr_team_id.employee_ids.mapped('user_id')
                user = [
                    employee.user_id.id
                    for employee in rec.hr_team_id.employee_ids
                    if any(role.type == 'Reviewer_1' for role in employee.role_ids)
                ]
                user_reviewer_2 = [
                    employee.user_id.id
                    for employee in rec.hr_team_id.employee_ids
                    if
                    any(role.type == 'Reviewer_2' for role in employee.role_ids)
                ]
                user_approver = [
                    employee.user_id.id
                    for employee in rec.hr_team_id.employee_ids
                    if
                    any(role.type == 'Approver' for role in employee.role_ids)
                ]
            rec.user_reviewer_1_ids = user
            rec.user_reviewer_2_ids = user_reviewer_2
            rec.user_approver = user_approver
            rec.user_ids = users

    @api.model_create_multi
    def create(self, vals_list):
        """Support multi-create and single-create paths safely (used during XML data load)."""
        # Accept both dict and list-of-dicts (some code might call with dict unexpectedly)
        if isinstance(vals_list, dict):
            vals_list = [vals_list]

        prepared = []
        for vals in vals_list:
            v = dict(vals or {})

            # parent-based defaults
            if v.get('parent_id'):
                parent_id = self.env['project.task'].browse(int(v.get('parent_id')))
                v['stage_id'] = parent_id.stage_id.id or False
                v['type'] = parent_id.type.id if parent_id.type else False
                prefix = parent_id.stage_id.prefix if parent_id.stage_id and parent_id.stage_id.prefix else ""
                reference_number = prefix + ': ' + str(
                    parent_id.sub_task_count + 1) if prefix or parent_id.sub_task_count is not None else False
                v['reference_number'] = reference_number

            # project-based defaults
            if v.get('project_id'):
                project_id = self.env['project.project'].browse(int(v.get('project_id')))
                if project_id and project_id.department_id:
                    v['hr_team_id'] = project_id.department_id.id
                    v['user_ids'] = project_id.team_member_ids.mapped('user_id').ids
                    # keep the rest as before (commented-out defaults left out to avoid unexpected writes)

            prepared.append(v)

        # Try bulk create (preferred). If parent/other modules are not multi-create aware, fall back to per-record create.
        try:
            records = super(ProjectTask, self).create(prepared)
        except Exception:
            records = self.browse()
            for v in prepared:
                try:
                    rec = super(ProjectTask, self).create(v)
                except TypeError:
                    # some parent implementations expect a list; try with single-item list
                    rec = super(ProjectTask, self).create([v])
                records |= rec
        return records

    @api.onchange('child_ids')
    def _compute_sub_task_count(self):
        """Calculate the sub-tasks"""
        for rec in self:
            rec.sub_task_count = len(rec.child_ids)

    def action_view_sub_task(self):
        return {
            'type': 'ir.actions.act_window',
            'name': 'Sub Task',
            'res_model': 'project.task',
            'view_mode': 'form',
            'views': [(self.env.ref('internal_audit_management.view_my_sub_task_form').id, 'form')],
            'res_id': self.id,  # Opens the current record
            'target': 'current',  # Opens in the same window
            'context': {
                'default_title': self.name,
                'active_id': self.id,
                'default_res_id': self.id,

            },
        }

    def action_view_request_documents(self):
        return {
            'name': 'Request Document',
            'type': 'ir.actions.act_window',
            'res_model': 'documents.request_wizard',
            'view_mode': 'form',
            'view_id': self.env.ref('documents.documents_request_form_view').id,
            'target': 'new',
            'context': {
                'default_res_id': self.id,
                'default_res_model': 'project.task',
            },
        }

    def action_request_details(self):
        return {
            'res_model': 'documents.document',
            'type': 'ir.actions.act_window',
            'name': _("%(project_name)s's Documents", project_name=self.name),
            'domain': [
                ('res_model', '=', 'project.task'),
                ('res_id', '=', self.id),
                ('attachment_id', '=', False)
            ],
            'view_mode': 'kanban,list,form',
            'context': {'default_res_model': 'project.task',
                        'default_res_id': self.id,
                        'limit_folders_to_project': True},
        }

    def get_list_url(self):
        """Method for create the url."""
        base_url = self.env['ir.config_parameter'].sudo().get_param(
            'web.base.url')
        Urls = urls.url_join(base_url,
                             'web#id=%s&model=task.project&view_type=form' % self.id)
        return Urls

    def action_review(self):
        """First Review"""
        mail_template = self.env.ref(
            'internal_audit_management.email_template_audit_procedure_to_review')
        recipient_ids = self.user_reviewer_2_ids
        partner = recipient_ids.mapped('partner_id')
        email_values = {
            'recipient_ids': [(6, 0, partner.ids)]
        }
        mail_template.send_mail(self.id, force_send=True,
                                email_values=email_values)
        self.message_post(body=_('The Audit Procedure %s was reviewed by %s') % (
            self.name, self.env.user.name))
        self.stages = 'first_reviewer'
        self.state = '01_in_progress'

    def action_2nd_review(self):
        """Second Review"""
        mail_template = self.env.ref('internal_audit_management.email_template_audit_procedure_to_approve')
        recipient_ids = self.user_approver
        partner = recipient_ids.mapped('partner_id')
        email_values = {
            'recipient_ids': [(6, 0, partner.ids)]
        }
        mail_template.send_mail(self.id, force_send=True,
                                email_values=email_values)
        self.message_post(
            body=_('The Audit Procedure %s was reviewed by %s') % (
                self.name, self.env.user.name))
        self.stages = 'second_reviewer'
        self.state = '01_in_progress'

    def action_approve(self):
        """First Review"""
        mail_template = self.env.ref('internal_audit_management.email_template_audit_procedure_to_approved')
        recipient_ids = self.user_ids
        partner = recipient_ids.mapped('partner_id')
        email_values = {
            'recipient_ids': [(6, 0, partner.ids)]
        }
        mail_template.send_mail(self.id, force_send=True,
                                email_values=email_values)
        self.message_post(
            body=_('The Audit Procedure %s was Approved by %s') % (
                self.name, self.env.user.name))
        self.stages = 'approved'
        self.state = '03_approved'

    def action_reject(self):
        """First Review"""
        self.state = '1_canceled'
        mail_template = self.env.ref('internal_audit_management.email_template_audit_procedure_to_rejected')
        recipient_ids = self.user_ids
        partner = recipient_ids.mapped('partner_id')
        email_values = {
            'recipient_ids': [(6, 0, partner.ids)]
        }
        mail_template.send_mail(self.id, force_send=True,
                                email_values=email_values)
        self.message_post(
            body=_('The Audit Procedure %s was Rejected by %s') % (
                self.name, self.env.user.name))
        self.stages = 'rejected'

    def action_revert(self):
        return {
            'name': 'Revert Procedure',
            'type': 'ir.actions.act_window',
            'res_model': 'project.task.revert',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_task_id': self.id,
            },
        }

    class SurveyDetails(models.Model):
        """Survey Details"""
        _name = 'survey.details'
        _description = "Survey Details"

        survey_details_id = fields.Many2one('project.task', string='Project Task')
        survey_num = fields.Html(string="No", help="Survey Number")
        item_description = fields.Html(string="Item Description", help="Item Description")
        assignment_category = fields.Many2one('audit.assignment.category', string="Assignment Category/Discipli",
                                              help="Assignment Category")
        comments = fields.Html(string="Comments", help="Comments")
        analysis = fields.Html(string="Analysis", help="Analysis")
        reference = fields.Html(string="Ref", help="Reference")

    class AuditProgram(models.Model):
        """Audit Program"""
        _name = 'audit.pgm'
        _description = "Audit Program"

        audit_details_id = fields.Many2one('project.task',
                                           string='Task')
        process = fields.Html(string='Process', help='Audit Process')
        risk_identified = fields.Html(string='Risk Identified', help='Risk Identified')
        controls_identified = fields.Html(string='Controls Identified', help='Controls Identified')
        audit_procedures = fields.Html(string='Audit Procedures to Test Control Effectiveness',
                                       help='Audit Procedures to Test Control Effectiveness')
        timeline = fields.Html(string='Timeline', help='Timeline')
        responsibility_assigned_to = fields.Html(string='Responsibility Assigned To', help='Responsibility Assigned To')
        wp_reference = fields.Html(string='WP Reference', help='WP Reference')
