# -*- coding: utf-8 -*-
{
    'name': "Internal Audit System: Project",
    'description': """Internal Audit System: Project""",
    'summary': """Internal Audit System: Project""",
    'version': '16.0.1.0.2',
    'sequence': '21',
    'category': 'Services/Project',
    'depends': ['documents', 'project', 'hr', 'hr_timesheet', 'e_system'],
    'data': [
        'data/rolling_plan_data.xml',
        'data/business_risk_data.xml',
        'data/data_operational_plan.xml',
        'data/mail_template_audit_universe.xml',
        'data/audit_role_data.xml',
        'data/ir_sequence_data.xml',
        'report/ir_actions_report.xml',
        'report/other_documents_report.xml',
        'report/risk_report.xml',
        'data/mail_template_data.xml',
        'data/mail_template_audit_findings_data.xml',
        'data/mail_template_rolling_plan.xml',
        'data/mail_template_operational_plan.xml',
        'data/mail_template_swot_analysis.xml',
        'data/mail_template_pestel_analysis.xml',
        'data/mail_template_internal_audit_charter.xml',
        'data/mail_template_audit_strategy.xml',
        'data/mail_template_audit_commitee.xml',
        'data/mail_template_methodology_tracking.xml',
        'data/project_template_data.xml',
        'data/mail_template_client_survey.xml',
        'data/mail_template_project_checklist.xml',
        'data/mail_quality_assurance.xml',
        'data/ir_cron_data.xml',
        'data/documents_folder_data.xml',
        'data/audit_revert_data.xml',
        'data/mail_template_audit_followup.xml',
        'data/mail_template_for_doc.xml',
        'data/mail_template_for_mom.xml',
        'data/mail_template_other_doc.xml',
        'data/client_survey_data.xml',
        'report/client_satisfaction_survey_template.xml',
        'report/project_checklist_template.xml',
        'report/quality_assurance.xml',
        'report/internal_audit_plan_report.xml',
        'report/internal_auidt_methodology_report.xml',
        'report/audit_universe_report.xml',
        'report/rolling_plan_report.xml',
        'report/quality_control_peer_report.xml',
        'report/quality_control_outsourced_peer_report.xml',
        'report/internal_quality_control_report.xml',
        'report/internal_audit_charter_report.xml',
        'report/audit_committee_charter_report.xml',
        'report/audit_standards_report.xml',
        'report/operational_plan_report.xml',
        'report/financial_statements.xml',
        'report/audit_finding.xml',
        'report/audit_follow_up.xml',
        'report/minutes_of_meeting.xml',
        'report/audit_action_plan.xml',
        'report/swot_analysis.xml',
        'report/pestel_analysis.xml',
        'report/project.xml',
        'report/professional_development.xml',
        'security/ir.model.access.csv',
        'views/project_checklist.xml',
'views/rolling_plan_views.xml',
        'views/audit_action_plan_views.xml',
        'views/audit_followup.xml',
        'views/quality_assurance.xml',
        'views/project_template_views.xml',
        'views/project_project_views.xml',
        'views/hr_employee_views.xml',
        'views/customer_satisfaction_survey.xml',
        'views/hr_department_views.xml',
        'views/res_config_settings_views.xml',
        'report/project_task_report.xml',
        'views/project_task_views.xml',
        'views/project_task_type_views.xml',
        'views/audit_universe_views.xml',
        'views/task_type_views.xml',
        'views/audit_revert.xml',
        'views/financial_statements_views.xml',
        'views/internal_audit_plan_views.xml',
        'views/internal_audit_charter_views.xml',
        'views/business_risk_views.xml',
        'views/audit_committee_charter_views.xml',
        'views/quality_control_views.xml',
        'views/quality_control_peer_views.xml',
        'views/audit_strategy_views.xml',
        'views/audit_methodology_views.xml',

        'views/audit_entity_views.xml',
        'views/exception_report_views.xml',
        'views/audit_category_views.xml',

        'views/operational_plan_views.xml',
        'views/pestel_analysis.xml',
        'views/swot_analysis.xml',
        'views/internal_audit_methdology.xml',
        'views/professional_development.xml',
        'views/internal_audit_standards.xml',
        'views/minutes_of_meeting.xml',
        'views/other_documents.xml',
        'views/advisory_engagments.xml',
'wizard/project_create_views.xml',
'views/audit_findings_views.xml',
        'views/internal_audit_management_menus.xml',
        'views/documents_document_views.xml',
'views/revise_materiality_views.xml',
        'wizard/rolling_revert_wizard_views.xml',
        'wizard/operational_revert_wizard_views.xml',
        'wizard/audit_rever_wizard_views.xml',


        'wizard/audit_universe_revert_wizard_views.xml',
        'wizard/project_task_revert_views.xml',
        'wizard/swot_analysis_revert_wizard_views.xml',
        'wizard/pestel_analysis_revert_wizard.xml',
        'wizard/audit_strategy_revert_wizard.xml',
        'wizard/internal_audit_charter_wizard_views.xml',
        'wizard/internal_audit_revert_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'internal_audit_management/static/src/css/style.css',
            'internal_audit_management/static/src/js/action_manager.js',
            'internal_audit_management/static/src/js/report_utils.js',
        ],
    },
    'external_dependencies': {
        'python': ['python-docx'],
    },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
