import base64
import io
import logging
import os
import random
import re
import traceback
from datetime import date, datetime, timedelta

from odoo import _, api, fields, models
from odoo.exceptions import UserError

import openpyxl


_logger = logging.getLogger(__name__)


PROGRAMME_FALLBACK = {
    "1": "Administration",
    "2": "Integrated Human Settlements Development",
    "3": "Housing Development",
    "4": "Housing Asset Management",
}

SUB_PROGRAMME_FALLBACK = {
    "1.1": "Executive Leadership",
    "1.2": "Corporate Governance and Risk Management",
    "1.3": "Financial Management",
    "1.4": "Strategic Management and ICT",
    "1.5": "Human Resources and Legal Services",
    "2.1": "Research and Policy Development",
    "2.2": "Human Settlements Delivery Planning",
    "2.3": "Capacity Building and Municipal Support",
    "3.1": "Beneficiary Management and Social Facilitation",
    "3.2": "Housing Programmes",
    "3.3": "Project Management and Grant Services",
    "4.1": "Sales, Transfer and Asset Management",
    "4.2": "Land Acquisition and Tenure Services",
    "4.3": "Social and Rental Housing",
}

REQUIRED_COLUMNS = [
    "Directorate_Name",
    "Output_ Indicator",
    "Indicator_Type",
    "Annual_Target",
    "Q1_Planned",
    "Q2_Planned",
    "Q3_Planned",
    "Q4_Planned",
]

REQUIRED_COLUMN_ALIASES = {
    "Directorate_Name": ["Directorate_Name", "Directorate Name"],
    "Output_ Indicator": ["Output_ Indicator", "Output Indicator"],
    "Indicator_Type": ["Indicator_Type", "Indicator Type"],
    "Annual_Target": ["Annual_Target", "Annual Target"],
    "Q1_Planned": ["Q1_Planned", "Q1"],
    "Q2_Planned": ["Q2_Planned", "Q2"],
    "Q3_Planned": ["Q3_Planned", "Q3"],
    "Q4_Planned": ["Q4_Planned", "Q4"],
}

MEASUREMENT_TYPE_ALIASES = {
    "number": "number",
    "numeric": "number",
    "percentage": "percentage",
    "percent": "percentage",
    "%": "percentage",
    "date": "date",
    "deadline": "date",
    "boolean": "boolean",
    "yes/no": "boolean",
    "bool": "boolean",
    "milestone": "milestone",
    "text": "text",
}

AGGREGATION_RULE_ALIASES = {
    "sum": "sum",
    "count": "count",
    "count submissions": "count",
    "latest": "latest",
    "max": "max",
    "maximum": "max",
    "min": "min",
    "minimum": "min",
    "average": "average",
    "avg": "average",
    "any": "any",
    "all": "all",
    "standalone": "standalone",
    "per period": "standalone",
    "non-cumulative": "standalone",
    "non cumulative": "standalone",
    "independent": "standalone",
}

COMPARISON_DIRECTION_ALIASES = {
    "higher": "higher",
    "higher is better": "higher",
    "lower": "lower",
    "lower is better": "lower",
    "exact": "exact",
    "exact match": "exact",
}

MEASUREMENT_UNIT_ALIASES = [
    "Measurement_Unit",
    "Measurement Unit",
    "Unit",
    "UOM",
]

# ── Demo seed data constants ─────────────────────────────────────────────────
_DUMMY_EVIDENCE_BYTES = (
    b"OPMS DEMO EVIDENCE\n\n"
    b"This file is a placeholder generated for demonstration purposes.\n"
    b"In actual reporting, replace with real supporting evidence documents.\n"
    b"\nGenerated by the OPMS Demo Seed functionality.\n"
)

_DEMO_COMMENTS = [
    "All planned activities for this quarter have been completed as targeted.",
    "Progress is on track with no significant deviations from the plan.",
    "Target achieved within the reporting period with minimal deviation.",
    "Significant progress made; approximately 90% of planned activities completed.",
    "Exceeded the planned target through increased operational efficiency.",
    "Implementation is ongoing; full delivery is expected by end of quarter.",
    "Behind schedule due to capacity constraints; recovery plan is in place.",
    "Target partially achieved; remedial measures have been initiated.",
    "On track with minor delays attributed to procurement processes.",
    "Deliverable completed and submitted to the relevant authority for approval.",
]

_DEMO_DEVIATIONS = [
    None,
    None,
    None,
    "Budget reallocation impacted planned outputs during this period.",
    "Staff vacancies reduced operational capacity for this quarter.",
    "Procurement delays in appointing required service providers.",
    "Third-party dependency caused delays in finalising the deliverable.",
    "Adverse conditions interrupted planned field activities.",
]

_DEMO_REMEDIALS = [
    None,
    None,
    "Intensive monitoring and weekly reporting implemented to recover the timeline.",
    "Additional staff mobilised to address the identified capacity gaps.",
    "Procurement process expedited; service providers have now been appointed.",
    "Senior management engaged to resolve outstanding operational bottlenecks.",
]

_DEMO_WORKFLOW_POOL = [
    "draft", "draft",
    "submitted", "submitted", "submitted",
    "director_review", "director_review",
    "approved", "approved", "approved", "approved",
    "rejected",
]


class OpmsAppImportWizard(models.TransientModel):
    _name = "opms.app.import.wizard"
    _description = "OPMS APP Import Wizard"

    # file_data / file_name are validated in action_import_app / action_validate_file,
    # not marked required=True here so the auto-import / copy / demo buttons can
    # be invoked without a file being uploaded first.
    file_data = fields.Binary()
    file_name = fields.Char()
    financial_year = fields.Many2one(
        "account.fiscal.year",
        required=True,
        ondelete="restrict",
        default=lambda self: self._default_financial_year(),
    )
    operation_mode = fields.Selection(
        [
            ("manual_import", "Option 1 — Manual File Import"),
            ("auto_import", "Option 1b — Auto-Import (Bundled or Corrected Excel)"),
            ("copy_previous", "Option 2 — Copy from Previous Period"),
            ("demo_app_plans", "Option 3 — Load Demo APP Plans (Full Hierarchy)"),
            ("demo_submissions", "Option 4 — Load Demo Submissions"),
        ],
        string="Operation",
        required=True,
        help="Select one operation. The wizard shows only the relevant fields and action button for your selection.",
    )
    import_mode = fields.Selection(
        [("create", "Create New"), ("update", "Update Existing"), ("skip", "Skip Existing")],
        default="create",
        required=True,
    )
    source_financial_year = fields.Many2one(
        "account.fiscal.year",
        string="Copy Source Year",
        ondelete="restrict",
        help="Select the source financial year whose APP hierarchy will be copied into the selected target year above.",
    )
    versioned_excel_file = fields.Selection(
        selection="_get_versioned_file_selection",
        string="Use Corrected Version",
        help=(
            "Select a previously auto-corrected Excel file to import instead of the original bundled file.\n"
            "Corrected versions are created automatically when you click 'Auto-Import Bundled Excel'."
        ),
    )
    demo_source_url = fields.Char(
        string="Indicator Source URL or Path",
        help=(
            "Option 3 only.  Provide a URL (https://...) to an APP or AOP PDF document, "
            "or a local filename relative to the module /data/ directory.\n"
            "Leave blank to extract indicators from the bundled KPI Excel file."
        ),
    )

    @staticmethod
    def _module_data_path():
        import odoo.modules as _odoo_modules
        module_path = _odoo_modules.get_module_path("opms_ecdhs")
        return os.path.join(module_path, "data")

    def _get_versioned_file_selection(self):
        try:
            data_dir = self._module_data_path()
            pattern = re.compile(r"KPI.*-(?:v)?\d{1,4}-\d{2}-\d{2}-\d{4}\.xlsx$", re.IGNORECASE)
            files = sorted(
                f for f in os.listdir(data_dir)
                if pattern.match(f) and os.path.isfile(os.path.join(data_dir, f))
            )
            return [(f, f) for f in files]
        except Exception:
            return []

    def _default_financial_year(self):
        self.env["opms.app.plan"]._ensure_opms_fiscal_years()
        today = fields.Date.context_today(self)
        return self.env["account.fiscal.year"].search(
            [("date_from", "<=", today), ("date_to", ">=", today)],
            order="date_from desc",
            limit=1,
        )

    @api.model
    def fields_get(self, allfields=None, attributes=None):
        result = super().fields_get(allfields=allfields, attributes=attributes)
        if "operation_mode" in result and not self.env.user.has_group("base.group_system"):
            selection = result["operation_mode"].get("selection") or []
            result["operation_mode"]["selection"] = [
                item for item in selection
                if item[0] not in ("demo_submissions", "demo_app_plans")
            ]
        return result

    def _ensure_operation_mode(self, allowed_modes, admin_required=False):
        self.ensure_one()
        if isinstance(allowed_modes, str):
            allowed_modes = {allowed_modes}
        else:
            allowed_modes = set(allowed_modes or [])

        if not self.operation_mode:
            raise UserError(_("Please select an Operation at the top of the wizard."))
        if self.operation_mode not in allowed_modes:
            raise UserError(
                _("Selected Operation does not match this action. Please choose the correct option first.")
            )
        if admin_required and not self.env.user.has_group("base.group_system"):
            raise UserError(_("Only users in the Administrator/Settings group can run this operation."))

    def _notify_progress(self, title, message):
        user = self.env.user
        notify = getattr(user, "notify_info", None)
        if callable(notify):
            try:
                notify(message=message, title=title, sticky=False)
                return
            except Exception:
                pass
        _logger.info("%s: %s", title, message)

    def _bounded_param_int(self, param_key, default, min_value, max_value):
        raw = self.env["ir.config_parameter"].sudo().get_param(param_key, str(default))
        try:
            value = int(str(raw).strip())
        except Exception:
            value = default
        return max(min_value, min(max_value, value))

    def _get_import_progress_tuning(self):
        return {
            "notify_step": self._bounded_param_int(
                "opms_ecdhs.app_import_notify_step", 250, 50, 5000
            ),
            "history_batch_size": self._bounded_param_int(
                "opms_ecdhs.app_import_history_batch_size", 500, 100, 5000
            ),
            "copy_plan_notify_step": self._bounded_param_int(
                "opms_ecdhs.copy_previous_notify_step", 1, 1, 100
            ),
        }

    def _get_demo_seed_tuning(self):
        """Return tuned demo-seed performance settings from system params.

        Params (all optional):
        - opms_ecdhs.demo_seed_chunk_size
        - opms_ecdhs.demo_seed_prep_notify_step
        - opms_ecdhs.demo_seed_create_notify_every_chunks
        """

        return {
            "chunk_size": self._bounded_param_int("opms_ecdhs.demo_seed_chunk_size", 300, 50, 2000),
            "prep_notify_step": self._bounded_param_int("opms_ecdhs.demo_seed_prep_notify_step", 500, 100, 10000),
            "create_notify_every_chunks": self._bounded_param_int(
                "opms_ecdhs.demo_seed_create_notify_every_chunks", 2, 1, 50
            ),
        }

    def _value_to_text(self, value):
        if value is None:
            return ""
        if hasattr(value, "strftime"):
            return value.strftime("%d/%m/%Y")
        return str(value).strip()

    def _load_rows(self):
        if not self.file_data:
            raise UserError(_("Please upload an Excel file."))

        workbook = openpyxl.load_workbook(io.BytesIO(base64.b64decode(self.file_data)), data_only=True)
        sheet = workbook[workbook.sheetnames[0]]

        header_row = [self._value_to_text(sheet.cell(row=1, column=col).value) for col in range(1, sheet.max_column + 1)]
        headers = [value for value in header_row if value]

        missing = []
        for column in REQUIRED_COLUMNS:
            aliases = REQUIRED_COLUMN_ALIASES.get(column, [column])
            if not any(alias in headers for alias in aliases):
                missing.append(column)
        if missing:
            raise UserError(_("Missing required columns: %s") % ", ".join(missing))

        index_by_header = {header: i for i, header in enumerate(header_row)}

        data_rows = []
        for row_num in range(2, sheet.max_row + 1):
            row_values = [sheet.cell(row=row_num, column=col).value for col in range(1, sheet.max_column + 1)]
            if not any(value is not None and str(value).strip() for value in row_values):
                continue

            item = {}
            for column in header_row:
                if not column:
                    continue
                item[column] = row_values[index_by_header[column]]
            item["_row_number"] = row_num
            data_rows.append(item)

        if not data_rows:
            raise UserError(_("No importable rows were found in the spreadsheet."))

        return data_rows

    def action_validate_file(self):
        self.ensure_one()
        self._ensure_operation_mode("manual_import")
        rows = self._load_rows()
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Validation Successful"),
                "message": _("File validated with %s rows ready for import.") % len(rows),
                "type": "success",
                "sticky": False,
            },
        }

    def _parse_directorate(self, directorate_name):
        value = (directorate_name or "").strip()
        match = re.match(r"^(\d+)(?:\.(\d+))?(?:\.(\d+))?\s*(.*)$", value)
        if not match:
            return {
                "programme_code": "",
                "sub_programme_code": "",
                "directorate_code": "",
                "directorate_label": value,
            }

        p1, p2, p3, label = match.groups()
        programme_code = p1
        sub_programme_code = f"{p1}.{p2}" if p2 else p1
        directorate_code = ".".join([part for part in [p1, p2, p3] if part])
        directorate_label = f"{directorate_code} {label.strip()}".strip()

        return {
            "programme_code": programme_code,
            "sub_programme_code": sub_programme_code,
            "directorate_code": directorate_code,
            "directorate_label": directorate_label,
        }

    def _normalize_indicator_type(self, indicator_type):
        value = (self._value_to_text(indicator_type) or "AOP").upper()
        return "app" if value == "APP" else "aop"

    def _row_value(self, row, *keys):
        for key in keys:
            if key in row and row.get(key) is not None:
                return row.get(key)
        return None

    def _normalize_measurement_type(self, value):
        text = (self._value_to_text(value) or "").strip().lower()
        if not text:
            return None
        return MEASUREMENT_TYPE_ALIASES.get(text)

    def _normalize_aggregation_rule(self, value):
        text = (self._value_to_text(value) or "").strip().lower()
        if not text:
            return None
        return AGGREGATION_RULE_ALIASES.get(text)

    def _normalize_comparison_direction(self, value):
        text = (self._value_to_text(value) or "").strip().lower()
        if not text:
            return None
        return COMPARISON_DIRECTION_ALIASES.get(text)

    def _normalize_value_for_indicator(self, indicator, raw_value):
        text = self._value_to_text(raw_value)
        if not text:
            return "-"

        measurement_type = (indicator.measurement_type or "text") if indicator else "text"

        if measurement_type in ("number", "percentage"):
            # For numbers, extract numeric part and strip units/suffixes
            # Example: "240 days" or "30%" → extract just "240" or "30"
            text = text.strip()

            # Remove commas and percentage signs first
            normalized = re.sub(r"[,%]", "", text)

            # Extract leading numeric part (handles "240 days" → "240")
            # Regex: optional sign, digits, optional decimal point and more digits
            match = re.match(r"([-+]?\d+(?:[.,]\d+)?)", normalized)
            if match:
                numeric_str = match.group(1).replace(",", ".")
                try:
                    parsed = float(numeric_str)
                    if parsed.is_integer():
                        return str(int(parsed))
                    return ("%.2f" % parsed).rstrip("0").rstrip(".")
                except (TypeError, ValueError):
                    pass
            return text

        if measurement_type == "date":
            for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y", "%m/%d/%Y", "%d %B %Y", "%d %b %Y"):
                try:
                    return datetime.strptime(text, fmt).date().strftime("%Y-%m-%d")
                except ValueError:
                    continue
            try:
                parsed_date = fields.Date.to_date(text)
                return parsed_date.strftime("%Y-%m-%d") if parsed_date else text
            except Exception:
                return text

        if measurement_type == "boolean":
            lowered = text.strip().lower()
            if lowered in {"1", "true", "yes", "y", "achieved", "done", "completed"}:
                return "Yes"
            if lowered in {"0", "false", "no", "n", "not achieved", "pending", "not done"}:
                return "No"
            return text

        return text

    def _normalize_measurement_unit(self, value):
        text = (self._value_to_text(value) or "").strip()
        return text or None

    def _infer_measurement_unit(self, annual_target, quarter_values, explicit_value=None):
        explicit = self._normalize_measurement_unit(explicit_value)
        if explicit:
            return explicit

        candidate_values = [annual_target] + list(quarter_values.values())
        for value in candidate_values:
            text = self._value_to_text(value)
            if not text:
                continue
            # Infer unit from values such as "30 days" or "12 houses".
            match = re.match(r"^\s*[-+]?\d+(?:[.,]\d+)?\s*([a-zA-Z][a-zA-Z0-9 _/%-]*)\s*$", text)
            if match:
                return match.group(1).strip()
        return None

    def _looks_like_date(self, value):
        if value in (None, False, ""):
            return False
        if isinstance(value, (date, datetime)):
            return True
        text = self._value_to_text(value)
        if not text:
            return False

        for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y", "%m/%d/%Y", "%d %B %Y", "%d %b %Y"):
            try:
                datetime.strptime(text.strip(), fmt)
                return True
            except ValueError:
                continue
        return False

    def _infer_measurement_type(self, indicator_name, annual_target, quarter_values, explicit_value=None):
        explicit = self._normalize_measurement_type(explicit_value)
        if explicit:
            return explicit

        text = (self._value_to_text(indicator_name) or "").lower()
        candidate_values = [annual_target] + list(quarter_values.values())

        # Date-like targets (e.g. "31 March 2026") should be treated as date KPIs.
        if any(self._looks_like_date(value) for value in candidate_values):
            return "date"
        if "date" in text or "deadline" in text or "timeline" in text or "within the prescribed timelines" in text:
            return "date"
        if "percentage" in text or "percent" in text or any("%" in self._value_to_text(value) for value in candidate_values):
            return "percentage"
        if any(term in text for term in ("achieved", "compliant", "approved", "completed", "implemented")) and "number of" not in text:
            return "boolean"
        if any(term in text for term in ("milestone", "submission of", "tabling of")) and "number of" not in text:
            return "milestone"

        return "number"

    def _infer_aggregation_rule(self, measurement_type, indicator_name, explicit_value=None):
        explicit = self._normalize_aggregation_rule(explicit_value)
        if explicit:
            return explicit

        text = (self._value_to_text(indicator_name) or "").lower()
        if measurement_type == "percentage":
            return "average"
        if measurement_type == "date":
            return "latest"
        if measurement_type == "boolean":
            return "latest"
        if measurement_type in ("milestone", "text"):
            return "latest"
        if any(term in text for term in (
            "average", "turnaround time", "mean",
            "number of days", "days to", "average number of days",
        )):
            return "average"
        return "sum"

    def _infer_comparison_direction(self, measurement_type, indicator_name, explicit_value=None):
        explicit = self._normalize_comparison_direction(explicit_value)
        if explicit:
            return explicit

        text = (self._value_to_text(indicator_name) or "").lower()
        if measurement_type == "date":
            return "lower"
        if measurement_type in ("boolean", "milestone", "text"):
            return "exact"
        if any(term in text for term in ("turnaround time", "number of days", "days to", "average number of days", "time to")):
            return "lower"
        return "higher"

    def _upsert_record(self, model_name, domain, values, mode, cache_bucket=None, cache_key=None):
        live_sync_models = {
            "opms.programme",
            "opms.sub.programme",
            "opms.directorate",
            "opms.output",
            "opms.output.indicator",
            "opms.annual.target",
            "opms.quarterly.target",
            "opms.quarter",
        }

        if cache_bucket is not None and cache_key is not None:
            cached_record = cache_bucket.get(cache_key)
            if cached_record and cached_record.exists():
                if cached_record and mode == "update":
                    write_env = cached_record
                    if model_name in live_sync_models or self.env.context.get("opms_skip_live_sync_refresh"):
                        write_env = write_env.with_context(
                            opms_skip_live_sync_refresh=True,
                            opms_import_app_matrix=True,
                        )
                    if model_name == "opms.annual.target":
                        write_env = write_env.with_context(import_file=True)
                    write_env.write(values)
                    return cached_record, "updated"
                return cached_record, "skipped"

        model_env = self.env[model_name]
        if model_name in live_sync_models or self.env.context.get("opms_skip_live_sync_refresh"):
            model_env = model_env.with_context(
                opms_skip_live_sync_refresh=True,
                opms_import_app_matrix=True,
            )

        record = model_env.search(domain, limit=1)
        if record:
            if cache_bucket is not None and cache_key is not None:
                cache_bucket[cache_key] = record
            if mode == "create" or mode == "skip":
                return record, "skipped"
            write_env = record
            if model_name in live_sync_models or self.env.context.get("opms_skip_live_sync_refresh"):
                write_env = write_env.with_context(
                    opms_skip_live_sync_refresh=True,
                    opms_import_app_matrix=True,
                )
            if model_name == "opms.annual.target":
                write_env = write_env.with_context(import_file=True)
            write_env.write(values)
            return record, "updated"

        if model_name == "opms.annual.target":
            model_env = model_env.with_context(import_file=True)
        record = model_env.create(values)
        if cache_bucket is not None and cache_key is not None:
            cache_bucket[cache_key] = record
        return record, "created"

    def action_import_app(self):
        self.ensure_one()
        self = self.with_context(
            opms_skip_live_sync_refresh=True,
            opms_import_app_matrix=True,
        )
        self._ensure_operation_mode({"manual_import", "auto_import"})
        rows = self._load_rows()
        tune = self._get_import_progress_tuning()

        history = self.env["opms.import.history"].create(
            {
                "name": _("APP Import - %s") % (self.file_name or self.financial_year.display_name),
                "financial_year": self.financial_year.id,
                "import_mode": self.import_mode,
                "total_rows": len(rows),
                "log": "",
            }
        )

        import_cache = {
            "opms.app.plan": {},
            "opms.programme": {},
            "opms.sub.programme": {},
            "opms.directorate": {},
            "opms.output": {},
            "opms.output.indicator": {},
            "opms.annual.target": {},
            "opms.quarter": {},
            "opms.quarterly.target": {},
        }
        summary = []
        success = 0
        failed = 0
        warnings_count = 0
        history_line_vals = []
        total_rows = len(rows)

        self._notify_progress(
            _("APP Import Progress"),
            _("Starting APP Matrix import for %s row(s) into %s.")
            % (total_rows, self.financial_year.display_name),
        )

        for index, row in enumerate(rows, start=1):
            row_num = row.get("_row_number")
            row_reference = self._value_to_text(row.get("rec_no")) or self._value_to_text(row_num)
            try:
                with self.env.cr.savepoint():
                    plan_name = self._value_to_text(row.get("APP")) or f"ANNUAL PERFORMANCE - {self.financial_year.display_name}"
                    plan_key = (plan_name, self.financial_year.id)
                    plan, _status_plan = self._upsert_record(
                        "opms.app.plan",
                        [("name", "=", plan_name), ("financial_year", "=", self.financial_year.id)],
                        {
                            "name": plan_name,
                            "financial_year": self.financial_year.id,
                            "code": self.financial_year.name,
                        },
                        self.import_mode,
                        cache_bucket=import_cache["opms.app.plan"],
                        cache_key=plan_key,
                    )

                    parsed = self._parse_directorate(self._value_to_text(row.get("Directorate_Name")))

                    programme_name = self._value_to_text(row.get("PROGRAMME")) or PROGRAMME_FALLBACK.get(
                        parsed["programme_code"],
                        "Unmapped Programme",
                    )
                    programme_key = (parsed["programme_code"] or False, programme_name)
                    sub_programme_name = self._value_to_text(row.get("SUB-PROGRAMME")) or SUB_PROGRAMME_FALLBACK.get(
                        parsed["sub_programme_code"],
                        f"Sub-Programme {parsed['sub_programme_code'] or 'Unknown'}",
                    )

                    programme, _status_programme = self._upsert_record(
                        "opms.programme",
                        [
                            ("code", "=", parsed["programme_code"] or False),
                            ("name", "=", programme_name),
                        ],
                        {
                            "code": parsed["programme_code"] or False,
                            "name": programme_name,
                        },
                        self.import_mode,
                        cache_bucket=import_cache["opms.programme"],
                        cache_key=programme_key,
                    )

                    sub_programme_key = (programme.id, parsed["sub_programme_code"] or False, sub_programme_name)
                    sub_programme, _status_sub_programme = self._upsert_record(
                        "opms.sub.programme",
                        [
                            ("programme_id", "=", programme.id),
                            ("code", "=", parsed["sub_programme_code"] or False),
                            ("name", "=", sub_programme_name),
                        ],
                        {
                            "programme_id": programme.id,
                            "code": parsed["sub_programme_code"] or False,
                            "name": sub_programme_name,
                        },
                        self.import_mode,
                        cache_bucket=import_cache["opms.sub.programme"],
                        cache_key=sub_programme_key,
                    )

                    directorate_name = parsed["directorate_label"] or self._value_to_text(row.get("Directorate_Name"))
                    directorate_key = (sub_programme.id, parsed["directorate_code"] or False, directorate_name)
                    directorate, _status_directorate = self._upsert_record(
                        "opms.directorate",
                        [
                            ("sub_programme_id", "=", sub_programme.id),
                            ("code", "=", parsed["directorate_code"] or False),
                            ("name", "=", directorate_name),
                        ],
                        {
                            "sub_programme_id": sub_programme.id,
                            "code": parsed["directorate_code"] or False,
                            "name": directorate_name,
                        },
                        self.import_mode,
                        cache_bucket=import_cache["opms.directorate"],
                        cache_key=directorate_key,
                    )

                    output_name = self._value_to_text(row.get("Output")) or "Unspecified Output"
                    output_key = (directorate.id, output_name)
                    output, _status_output = self._upsert_record(
                        "opms.output",
                        [("directorate_id", "=", directorate.id), ("name", "=", output_name)],
                        {
                            "directorate_id": directorate.id,
                            "name": output_name,
                        },
                        self.import_mode,
                        cache_bucket=import_cache["opms.output"],
                        cache_key=output_key,
                    )

                    indicator_name = self._value_to_text(
                        self._row_value(row, "Output_ Indicator", "Output Indicator")
                    )
                    if not indicator_name:
                        raise UserError(_("Output_ Indicator is empty."))

                    quarter_values = {
                        "q1": self._row_value(row, "Q1_Planned", "Q1"),
                        "q2": self._row_value(row, "Q2_Planned", "Q2"),
                        "q3": self._row_value(row, "Q3_Planned", "Q3"),
                        "q4": self._row_value(row, "Q4_Planned", "Q4"),
                    }

                    measurement_type = self._infer_measurement_type(
                        indicator_name,
                        self._row_value(row, "Annual_Target", "Annual Target"),
                        quarter_values,
                        explicit_value=self._row_value(row, "Measurement_Type", "Measurement Type"),
                    )
                    aggregation_rule = self._infer_aggregation_rule(
                        measurement_type,
                        indicator_name,
                        explicit_value=self._row_value(row, "Aggregation_Rule", "Aggregation Rule"),
                    )
                    comparison_direction = self._infer_comparison_direction(
                        measurement_type,
                        indicator_name,
                        explicit_value=self._row_value(row, "Comparison_Direction", "Comparison Direction"),
                    )
                    raw_unit_value = self._row_value(row, *MEASUREMENT_UNIT_ALIASES)
                    measurement_unit = self._infer_measurement_unit(
                        self._row_value(row, "Annual_Target", "Annual Target"),
                        quarter_values,
                        explicit_value=raw_unit_value,
                    )

                    indicator_type = self._normalize_indicator_type(row.get("Indicator_Type"))
                    indicator_values = {
                        "output_id": output.id,
                        "name": indicator_name,
                        "indicator_type": indicator_type,
                        "measurement_type": measurement_type,
                        "aggregation_rule": aggregation_rule,
                        "comparison_direction": comparison_direction,
                    }

                    if measurement_type != "number":
                        indicator_values["measurement_unit"] = False
                    elif measurement_unit:
                        indicator_values["measurement_unit"] = measurement_unit
                    elif raw_unit_value not in (None, False):
                        # Explicitly provided empty unit should clear existing configured unit.
                        indicator_values["measurement_unit"] = False

                    indicator_key = (output.id, indicator_name, indicator_type)
                    output_indicator, _status_indicator = self._upsert_record(
                        "opms.output.indicator",
                        [
                            ("output_id", "=", output.id),
                            ("name", "=", indicator_name),
                            ("indicator_type", "=", indicator_type),
                        ],
                        indicator_values,
                        self.import_mode,
                        cache_bucket=import_cache["opms.output.indicator"],
                        cache_key=indicator_key,
                    )

                    row_warnings = []
                    if measurement_type == "number" and not (output_indicator.measurement_unit or "").strip():
                        row_warnings.append(
                            "Numeric indicator has no measurement unit configured. "
                            "Add Measurement Unit in the import file for clearer reporting."
                        )

                    annual_target_key = (output_indicator.id, plan.id, self.financial_year.id)
                    annual_target, _status_annual_target = self._upsert_record(
                        "opms.annual.target",
                        [
                            ("output_indicator_id", "=", output_indicator.id),
                            ("app_plan_id", "=", plan.id),
                            ("financial_year", "=", self.financial_year.id),
                        ],
                        {
                            "output_indicator_id": output_indicator.id,
                            "app_plan_id": plan.id,
                            "financial_year": self.financial_year.id,
                            "target_value": self._normalize_value_for_indicator(
                                output_indicator,
                                self._row_value(row, "Annual_Target", "Annual Target"),
                            ),
                        },
                        self.import_mode,
                        cache_bucket=import_cache["opms.annual.target"],
                        cache_key=annual_target_key,
                    )

                    for code, target_value in quarter_values.items():
                        quarter_key = (plan.id, self.financial_year.id, code)
                        quarter, _status_quarter = self._upsert_record(
                            "opms.quarter",
                            [
                                ("app_plan_id", "=", plan.id),
                                ("financial_year", "=", self.financial_year.id),
                                ("code", "=", code),
                            ],
                            {
                                "app_plan_id": plan.id,
                                "financial_year": self.financial_year.id,
                                "code": code,
                                "name": code.upper(),
                            },
                            self.import_mode,
                            cache_bucket=import_cache["opms.quarter"],
                            cache_key=quarter_key,
                        )

                        quarterly_target_key = (annual_target.id, quarter.id)
                        self._upsert_record(
                            "opms.quarterly.target",
                            [("annual_target_id", "=", annual_target.id), ("quarter_id", "=", quarter.id)],
                            {
                                "annual_target_id": annual_target.id,
                                "quarter_id": quarter.id,
                                "planned_target": self._normalize_value_for_indicator(
                                    output_indicator,
                                    target_value,
                                ),
                            },
                            self.import_mode,
                            cache_bucket=import_cache["opms.quarterly.target"],
                            cache_key=quarterly_target_key,
                        )

                    success += 1
                    summary.append(f"Row {row_num}: success")
                    if row_warnings:
                        warnings_count += len(row_warnings)
                        for warning in row_warnings:
                            summary.append(f"Row {row_num}: warning - {warning}")
                    history_line_vals.append(
                        {
                            "history_id": history.id,
                            "row_number": row_num,
                            "row_reference": row_reference,
                            "status": "success",
                            "message": (
                                "Imported successfully"
                                if not row_warnings
                                else f"Imported successfully. Warning: {' | '.join(row_warnings)}"
                            ),
                        }
                    )
            except Exception as error:
                failed += 1
                summary.append(f"Row {row_num}: failed - {error}")
                _logger.exception("APP import failed at row %s", row_num)
                detailed_error = traceback.format_exc(limit=12)
                history_line_vals.append(
                    {
                        "history_id": history.id,
                        "row_number": row_num,
                        "row_reference": row_reference,
                        "status": "failed",
                        "message": f"{error}\n\n{detailed_error}",
                    }
                )

            if index % tune["notify_step"] == 0:
                self._notify_progress(
                    _("APP Import Progress"),
                    _("Processed %s/%s rows. Success: %s, Failed: %s, Warnings: %s.")
                    % (index, total_rows, success, failed, warnings_count),
                )

        if history_line_vals:
            HistoryLine = self.env["opms.import.history.line"]
            batch_size = tune["history_batch_size"]
            for start in range(0, len(history_line_vals), batch_size):
                HistoryLine.create(history_line_vals[start:start + batch_size])

        history.write(
            {
                "success_rows": success,
                "failed_rows": failed,
                "log": "\n".join(summary),
            }
        )

        # Refresh live sync links after successful imports to sync newly created hierarchy
        if success > 0:
            self.env["opms.live.report.sync"].sudo().refresh_links_for_scope()

        self._notify_progress(
            _("APP Import Progress"),
            _("APP Matrix import completed. Success: %s, Failed: %s, Warnings: %s.")
            % (success, failed, warnings_count),
        )

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Import Completed"),
                "message": _("Imported: %s, Failed: %s, Warnings: %s") % (success, failed, warnings_count),
                "type": "warning" if (failed or warnings_count) else "success",
                "sticky": False,
            },
        }

    # ── Feature 1 – Auto-import the bundled Excel file ──────────────────────

    def action_auto_import_from_excel(self):
        """Cleanse the bundled KPI Excel (or a selected versioned copy), save a
        corrected versioned copy, then run the standard import from it."""
        self.ensure_one()
        self._ensure_operation_mode("auto_import")
        if not self.financial_year:
            raise UserError(_("Please select a Financial Year before running the auto-import."))

        data_dir = self._module_data_path()

        # ── Determine source file ─────────────────────────────────────────────
        if self.versioned_excel_file:
            # User wants to re-use a previously corrected version as-is
            source_path = os.path.join(data_dir, self.versioned_excel_file)
            if not os.path.exists(source_path):
                raise UserError(
                    _("Selected corrected file not found: %s") % source_path
                )
            with open(source_path, "rb") as fh:
                encoded = base64.b64encode(fh.read())
            self.write({"file_data": encoded, "file_name": self.versioned_excel_file})
            return self.action_import_app()

        # ── Load original bundled file ────────────────────────────────────────
        original_name = "KPI 2025-26_Remapped-UPDATED.xlsx"
        original_path = os.path.join(data_dir, original_name)
        if not os.path.exists(original_path):
            raise UserError(
                _(
                    "Bundled Excel file not found.\n"
                    "Expected location: %s\n\n"
                    "Ensure the file exists in the module's /data/ directory."
                )
                % original_path
            )

        with open(original_path, "rb") as fh:
            source_bytes = fh.read()

        # ── Cleanse & correct ─────────────────────────────────────────────────
        corrected_bytes, corrections_log = self._cleanse_excel_workbook(source_bytes)

        # ── Determine versioned filename ──────────────────────────────────────
        versioned_name = self._next_versioned_filename(data_dir, original_name)
        versioned_path = os.path.join(data_dir, versioned_name)

        try:
            os.makedirs(data_dir, exist_ok=True)
            with open(versioned_path, "wb") as fh:
                fh.write(corrected_bytes)
        except OSError as exc:
            _logger.warning(
                "opms_app_import_wizard: could not save versioned Excel to %s: %s",
                versioned_path,
                exc,
            )
            versioned_name = original_name  # fall back to original name for audit trail

        # ── Import from the corrected copy ────────────────────────────────────
        encoded = base64.b64encode(corrected_bytes)
        self.write({"file_data": encoded, "file_name": versioned_name})
        result = self.action_import_app()

        # Record the versioned filename in the most recent import history
        # This enables cascade cleanup when the APP Plan is deleted
        latest_history = self.env["opms.import.history"].search(
            [("financial_year", "=", self.financial_year.id)],
            order="id desc",
            limit=1,
        )
        if latest_history:
            # Find the APP Plan created/updated in this import
            app_plan = self.env["opms.app.plan"].search(
                [
                    ("name", "like", "ANNUAL PERFORMANCE"),
                    ("financial_year", "=", self.financial_year.id),
                ],
                order="id desc",
                limit=1,
            )
            latest_history.write({
                "versioned_excel_filename": versioned_name,
                "app_plan_id": app_plan.id if app_plan else False,
            })

        # Amend the notification to mention the saved path and corrections
        if result.get("type") == "ir.actions.client" and result.get("tag") == "display_notification":
            orig_msg = result["params"]["message"]
            result["params"]["message"] = (
                f"{orig_msg}\n\n"
                f"Corrected file saved as: {versioned_name}\n"
                f"Corrections applied: {corrections_log}"
            )
            result["params"]["sticky"] = True

        return result

    # ── Excel cleansing helpers ──────────────────────────────────────────────

    def _cleanse_excel_workbook(self, source_bytes):
        """Load *source_bytes*, apply all corrections, return (corrected_bytes, summary_str).

        Corrections applied:
        * All text cells: strip leading/trailing whitespace and embedded newlines
        * Numeric int/float cells in target columns: converted to str (e.g. 6 → "6")
        * datetime cells in target columns: converted to "DD/MM/YYYY" string
        * Dash-variant cells (" - \\n\\n", "  -  " etc.): normalised to "-"
        * Annual_Target / Q*_Planned: parenthetical notes stripped
          e.g. "4 (Events, ...)" → "4"
        * Adds a ``Measurement_Type`` column with correctly inferred type per row
        * Adds a ``Measurement_Unit`` column with an inferred unit per row
        """
        wb_src = openpyxl.load_workbook(io.BytesIO(source_bytes), data_only=True)
        ws_src = wb_src[wb_src.sheetnames[0]]

        wb_dst = openpyxl.Workbook()
        ws_dst = wb_dst.active
        ws_dst.title = ws_src.title

        # ── Copy & normalise header row ───────────────────────────────────────
        headers = []
        for col_idx in range(1, ws_src.max_column + 1):
            raw = ws_src.cell(row=1, column=col_idx).value
            header_text = self._vt_strip(raw)
            headers.append(header_text)
            ws_dst.cell(row=1, column=col_idx, value=header_text)

        # Append extra columns if not already present
        mtype_col = self._ensure_column(headers, ws_dst, "Measurement_Type")
        munit_col = self._ensure_column(headers, ws_dst, "Measurement_Unit")

        target_cols = {"Annual_Target", "Q1_Planned", "Q2_Planned", "Q3_Planned", "Q4_Planned"}

        counts = {"stripped": 0, "date_converted": 0, "num_converted": 0, "dash_normalised": 0, "paren_stripped": 0}

        # ── Process data rows ─────────────────────────────────────────────────
        for row_num in range(2, ws_src.max_row + 1):
            row_values = [ws_src.cell(row=row_num, column=c).value for c in range(1, ws_src.max_column + 1)]

            if not any(v is not None and str(v).strip() for v in row_values):
                continue  # skip entirely blank rows

            cleaned_row = {}

            for col_idx, header in enumerate(headers):
                if not header:
                    continue
                raw = row_values[col_idx] if col_idx < len(row_values) else None
                cleaned = self._clean_cell_value(
                    raw,
                    header,
                    is_target_col=(header in target_cols),
                    counts=counts,
                )
                cleaned_row[header] = cleaned
                ws_dst.cell(row=row_num, column=col_idx + 1, value=cleaned)

            # ── Infer measurement type & unit ─────────────────────────────────
            ind_name = cleaned_row.get("Output_ Indicator") or ""
            ann_target = cleaned_row.get("Annual_Target") or ""
            q_values = {
                "q1": cleaned_row.get("Q1_Planned") or "",
                "q2": cleaned_row.get("Q2_Planned") or "",
                "q3": cleaned_row.get("Q3_Planned") or "",
                "q4": cleaned_row.get("Q4_Planned") or "",
            }

            existing_mtype = (
                cleaned_row.get("Measurement_Type")
                or cleaned_row.get("Measurement Type")
                or ""
            )
            mtype = self._cleanse_infer_mtype(ind_name, ann_target, q_values, existing_mtype)
            munit = self._cleanse_infer_munit(ind_name, ann_target, q_values, mtype)

            ws_dst.cell(row=row_num, column=mtype_col, value=mtype)
            ws_dst.cell(row=row_num, column=munit_col, value=munit)

        buf = io.BytesIO()
        wb_dst.save(buf)
        corrected_bytes = buf.getvalue()

        summary = (
            f"stripped_whitespace={counts['stripped']}, "
            f"dates_converted={counts['date_converted']}, "
            f"numbers_converted={counts['num_converted']}, "
            f"dashes_normalised={counts['dash_normalised']}, "
            f"parentheticals_stripped={counts['paren_stripped']}"
        )
        return corrected_bytes, summary

    def _vt_strip(self, value):
        """Convert any cell value to a clean string (strip newlines/whitespace)."""
        if value is None:
            return ""
        if isinstance(value, (datetime, date)):
            return value.strftime("%d/%m/%Y")
        return re.sub(r"[\r\n]+", " ", str(value)).strip()

    def _ensure_column(self, headers, ws_dst, column_name):
        """Return the 1-based column index for *column_name*, adding it if absent."""
        for i, h in enumerate(headers):
            if h == column_name:
                return i + 1
        # Add at end
        new_col = len(headers) + 1
        headers.append(column_name)
        ws_dst.cell(row=1, column=new_col, value=column_name)
        return new_col

    def _clean_cell_value(self, raw, header, is_target_col, counts):
        """Return the cleaned value for a single cell."""
        if raw is None:
            return None

        # datetime / date objects → formatted string
        if isinstance(raw, (datetime, date)):
            cleaned = raw.strftime("%d/%m/%Y")
            counts["date_converted"] += 1
            return cleaned

        # numeric int / float → string
        if isinstance(raw, (int, float)) and is_target_col:
            cleaned = str(int(raw)) if float(raw).is_integer() else str(raw)
            counts["num_converted"] += 1
            return cleaned

        if not isinstance(raw, str):
            return raw

        # Strip embedded newlines and leading/trailing whitespace
        cleaned = re.sub(r"[\r\n]+", " ", raw).strip()
        if cleaned != raw:
            counts["stripped"] += 1

        # Normalise dash variants (e.g. " - ", "  -  ", "-  ")
        if is_target_col and re.fullmatch(r"[\s\-–—]+", cleaned):
            counts["dash_normalised"] += 1
            return "-"

        # Strip trailing parenthetical notes from target columns that start with a number
        # e.g. "4 (Events, Internal Communication ...)" → "4"
        if is_target_col:
            paren_stripped = re.sub(r"\s*\(.*\)\s*$", "", cleaned).strip()
            if paren_stripped != cleaned and re.match(r"^[-+]?\d+(?:[.,]\d+)?", paren_stripped):
                counts["paren_stripped"] += 1
                return paren_stripped

        return cleaned

    def _cleanse_infer_mtype(self, indicator_name, annual_target, q_values, existing_mtype):
        """Improved measurement-type inference used during cleansing.

        Unlike the wizard's _infer_measurement_type, this uses word-boundary checks
        so that 'updates' does not incorrectly trigger the 'date' branch, and
        'percentage' / 'percent' take priority over 'date' keywords.
        """
        if existing_mtype and existing_mtype.lower() in MEASUREMENT_TYPE_ALIASES:
            return MEASUREMENT_TYPE_ALIASES[existing_mtype.lower()]

        text = (str(indicator_name or "")).lower().strip()
        cands = [annual_target] + list(q_values.values())

        # 1. Percentage takes highest priority (avoids "30 days from date of …")
        if re.search(r"\bpercentage\b|\bpercent\b", text):
            return "percentage"
        if any("%" in str(v or "") for v in cands):
            return "percentage"

        # 2. Date — use word boundary so "updates" ≠ "date"
        if any(isinstance(v, (date, datetime)) for v in cands):
            return "date"
        # Check string values that look like dates
        for v in cands:
            t = str(v or "").strip()
            if t and t.lower() not in ("-", "n/a", "na") and re.search(
                r"\b\d{1,2}[/\-]\d{1,2}[/\-]\d{2,4}\b|\b\d{4}-\d{2}-\d{2}\b"
                r"|\b\d{1,2}\s+(?:January|February|March|April|May|June|July"
                r"|August|September|October|November|December)\s+\d{4}\b",
                t,
                re.IGNORECASE,
            ):
                return "date"
        if re.search(r"\bdate\b|\bdeadline\b|\btimeline\b", text) or "within the prescribed timelines" in text:
            return "date"

        # 3. Boolean
        if (
            re.search(r"\bachieved\b|\bcompliant\b|\bapproved\b|\bcompleted\b|\bimplemented\b", text)
            and "number of" not in text
        ):
            return "boolean"

        # 4. Milestone
        if (
            re.search(r"\bmilestone\b|\bsubmission of\b|\btabling of\b", text)
            and "number of" not in text
        ):
            return "milestone"

        return "number"

    def _cleanse_infer_munit(self, indicator_name, annual_target, q_values, mtype):
        """Infer a measurement unit string for the cleansed Excel Measurement_Unit column."""
        if mtype != "number":
            return ""

        # Try extracting a unit from target values (e.g. "30 days" → "days")
        cands = [annual_target] + list(q_values.values())
        for v in cands:
            t = str(v or "").strip()
            if not t or t == "-":
                continue
            m = re.match(r"^\s*[-+]?\d+(?:[.,]\d+)?\s+([a-zA-Z][a-zA-Z0-9 _/%-]*)\s*$", t)
            if m:
                return m.group(1).strip()

        # Extract noun phrase from "Number of <noun>" indicators
        text = str(indicator_name or "").strip()
        m = re.match(r"^[Nn]umber\s+of\s+(.+)", text)
        if m:
            noun = m.group(1).strip()
            # Drop trailing past-tense verbs that are not the core unit
            noun = re.sub(
                r"\s+(conducted|submitted|coordinated|performed|implemented|approved"
                r"|developed|prepared|tabled|supported|completed|achieved|installed"
                r"|delivered|reviewed|allocated|finalized|updated|verified|produced"
                r"|compiled|processed|generated|issued|presented|recruited|trained"
                r"|identified|engaged|registered|administered|established|monitored"
                r"|assessed|facilitated|provided|resolved|rectified|attended"
                r"|supported|undertaken|inspected)\s*$",
                "",
                noun,
                flags=re.IGNORECASE,
            ).strip()
            words = noun.split()
            unit = " ".join(words[:3]) if len(words) > 3 else noun
            return unit if unit else "count"

        return "count"

    @staticmethod
    def _next_versioned_filename(data_dir, original_name):
        """Return the next versioned filename, e.g. 'KPI 2025-26_Remapped-UPDATED-v3-07-05-2026.xlsx'."""
        base = os.path.splitext(original_name)[0]  # strip .xlsx
        today_str = date.today().strftime("%d-%m-%Y")
        # Accept both historical '-3-' and required '-v3-' formats when computing next version.
        pattern = re.compile(re.escape(base) + r"-(?:v)?(\d+)-\d{2}-\d{2}-\d{4}\.xlsx$", re.IGNORECASE)

        max_version = 0
        try:
            existing_files = os.listdir(data_dir)
        except OSError:
            existing_files = []
        for fname in existing_files:
            m = pattern.match(fname)
            if m:
                max_version = max(max_version, int(m.group(1)))

        new_version = max_version + 1
        return f"{base}-v{new_version}-{today_str}.xlsx"

    # ── Feature 2 – Copy hierarchy from a previous period ───────────────────

    def action_copy_from_previous_period(self):
        """Copy the full APP hierarchy (APP Plan → Annual Targets → Quarters →
        Quarterly Targets) from a source financial year into the selected
        target financial year.  Dates are shifted by the FY offset where
        possible."""
        self.ensure_one()
        self = self.with_context(
            opms_skip_live_sync_refresh=True,
            opms_import_app_matrix=True,
        )
        self._ensure_operation_mode("copy_previous")
        if not self.financial_year:
            raise UserError(_("Please select a target Financial Year."))
        if not self.source_financial_year:
            raise UserError(_("Please select a source Financial Year to copy data from."))
        if self.source_financial_year == self.financial_year:
            raise UserError(_("Source and target Financial Years must be different."))

        target_fy = self.financial_year
        source_fy = self.source_financial_year

        date_delta = None
        if source_fy.date_from and target_fy.date_from:
            date_delta = target_fy.date_from - source_fy.date_from

        source_plans = self.env["opms.app.plan"].search([("financial_year", "=", source_fy.id)])
        if not source_plans:
            raise UserError(
                _("No APP Plans found for '%s'. Nothing to copy.") % source_fy.display_name
            )

        tune = self._get_import_progress_tuning()
        created_plans = created_annual = created_quarterly = 0
        target_plans_by_name = {
            rec.name: rec
            for rec in self.env["opms.app.plan"].search([("financial_year", "=", target_fy.id)])
        }

        self._notify_progress(
            _("Copy Previous Progress"),
            _("Starting copy from %s to %s for %s APP Plan(s).")
            % (source_fy.display_name, target_fy.display_name, len(source_plans)),
        )

        for plan_index, source_plan in enumerate(source_plans, start=1):
            plan_name = source_plan.name
            if source_fy.name and target_fy.name and source_fy.name in plan_name:
                plan_name = plan_name.replace(source_fy.name, target_fy.name)

            target_plan = target_plans_by_name.get(plan_name)
            if not target_plan:
                target_plan = self.env["opms.app.plan"].create({
                    "name": plan_name,
                    "financial_year": target_fy.id,
                    "code": target_fy.name,
                })
                target_plans_by_name[plan_name] = target_plan
                created_plans += 1

            # Build source-quarter → target-quarter mapping
            quarter_map = {}
            source_quarters = self.env["opms.quarter"].search([
                ("app_plan_id", "=", source_plan.id),
                ("financial_year", "=", source_fy.id),
            ])
            target_quarters_by_code = {
                rec.code: rec
                for rec in self.env["opms.quarter"].search([
                    ("app_plan_id", "=", target_plan.id),
                    ("financial_year", "=", target_fy.id),
                ])
            }
            for sq in source_quarters:
                tq = target_quarters_by_code.get(sq.code)
                if not tq:
                    q_vals = {
                        "name": sq.name,
                        "code": sq.code,
                        "financial_year": target_fy.id,
                        "app_plan_id": target_plan.id,
                    }
                    if date_delta:
                        for date_fld in (
                            "start_date", "end_date",
                            "submission_open_date", "submission_close_date",
                        ):
                            src_date = getattr(sq, date_fld)
                            if src_date:
                                q_vals[date_fld] = src_date + date_delta
                    tq = self.env["opms.quarter"].create(q_vals)
                    target_quarters_by_code[sq.code] = tq
                quarter_map[sq.id] = tq

            # Copy annual targets (Programmes / Directorates / Indicators reused as-is)
            source_annual_targets = self.env["opms.annual.target"].search([
                ("app_plan_id", "=", source_plan.id),
                ("financial_year", "=", source_fy.id),
            ])
            target_annual_targets_by_indicator = {
                rec.output_indicator_id.id: rec
                for rec in self.env["opms.annual.target"].search([
                    ("app_plan_id", "=", target_plan.id),
                    ("financial_year", "=", target_fy.id),
                ])
            }
            source_quarterly_by_annual = {}
            source_quarterly_targets = self.env["opms.quarterly.target"].search([
                ("annual_target_id", "in", source_annual_targets.ids),
            ])
            for sqt in source_quarterly_targets:
                source_quarterly_by_annual.setdefault(sqt.annual_target_id.id, []).append(sqt)

            target_quarterly_pairs = set()
            if target_annual_targets_by_indicator:
                existing_target_quarterlies = self.env["opms.quarterly.target"].search([
                    ("annual_target_id", "in", list(rec.id for rec in target_annual_targets_by_indicator.values())),
                ])
                target_quarterly_pairs = {
                    (rec.annual_target_id.id, rec.quarter_id.id) for rec in existing_target_quarterlies
                }

            for sat in source_annual_targets:
                tat = target_annual_targets_by_indicator.get(sat.output_indicator_id.id)
                if not tat:
                    tv = sat.target_value
                    if sat.output_indicator_id.measurement_type == "date" and date_delta:
                        tv = self._shift_date_string(tv, date_delta)
                    tv = self._normalize_value_for_indicator(sat.output_indicator_id, tv)
                    tat = self.env["opms.annual.target"].with_context(import_file=True).create({
                        "output_indicator_id": sat.output_indicator_id.id,
                        "app_plan_id": target_plan.id,
                        "financial_year": target_fy.id,
                        "target_value": tv,
                    })
                    target_annual_targets_by_indicator[sat.output_indicator_id.id] = tat
                    created_annual += 1

                # Copy quarterly targets
                for sqt in source_quarterly_by_annual.get(sat.id, []):
                    tq = quarter_map.get(sqt.quarter_id.id)
                    if not tq:
                        continue
                    quarterly_key = (tat.id, tq.id)
                    if quarterly_key not in target_quarterly_pairs:
                        pt = sqt.planned_target
                        if sat.output_indicator_id.measurement_type == "date" and date_delta:
                            pt = self._shift_date_string(pt, date_delta)
                        pt = self._normalize_value_for_indicator(sat.output_indicator_id, pt)
                        self.env["opms.quarterly.target"].create({
                            "annual_target_id": tat.id,
                            "quarter_id": tq.id,
                            "planned_target": pt,
                        })
                        target_quarterly_pairs.add(quarterly_key)
                        created_quarterly += 1

            if plan_index % tune["copy_plan_notify_step"] == 0:
                self._notify_progress(
                    _("Copy Previous Progress"),
                    _("Processed %s/%s APP Plan(s). Created: %s plans, %s annual targets, %s quarterly targets.")
                    % (plan_index, len(source_plans), created_plans, created_annual, created_quarterly),
                )

        self._notify_progress(
            _("Copy Previous Progress"),
            _("Copy completed from %s to %s. Created: %s plans, %s annual targets, %s quarterly targets.")
            % (source_fy.display_name, target_fy.display_name, created_plans, created_annual, created_quarterly),
        )

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Copy Complete"),
                "message": _(
                    "Copied from %s → %s:\n"
                    "%s APP Plan(s), %s Annual Targets, %s Quarterly Targets created."
                ) % (
                    source_fy.display_name, target_fy.display_name,
                    created_plans, created_annual, created_quarterly,
                ),
                "type": "success",
                "sticky": True,
            },
        }

    def _shift_date_string(self, value, delta):
        """Attempt to shift a date string by *delta* (timedelta).
        Returns the original string unchanged if it cannot be parsed."""
        text = (self._value_to_text(value) or "").strip()
        if not text:
            return value
        for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y", "%m/%d/%Y", "%d %B %Y", "%d %b %Y"):
            try:
                shifted = datetime.strptime(text, fmt).date() + delta
                return shifted.strftime(fmt)
            except ValueError:
                continue
        return value

    # ── Feature 3 – Load Demo APP Plans (full cascading hierarchy) ──────────
    # Generates APP Plan → Programme → Sub-Programme → Directorate → Output
    # → Output Indicator → Annual Target → Quarter → Quarterly Target
    # with randomised planned values.  Indicator source is configurable.
    # Visible to Settings / Administrator group only.

    _DEMO_INDICATOR_FALLBACK = [
        {"name": "Number of strategic plans approved and submitted to the relevant authority", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Percentage of planned annual performance targets achieved", "measurement_type": "percentage", "aggregation_rule": "average", "comparison_direction": "higher"},
        {"name": "Number of quarterly performance reports submitted within prescribed timeframes", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Date by which the annual report is tabled in the Legislature", "measurement_type": "date", "aggregation_rule": "latest", "comparison_direction": "lower"},
        {"name": "Number of funded vacant posts filled within 6 months of becoming vacant", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Percentage of disciplinary cases finalised within 60 days of charge sheet", "measurement_type": "percentage", "aggregation_rule": "average", "comparison_direction": "higher"},
        {"name": "Number of internal audit reports issued to management", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Number of beneficiary households verified and registered in the database", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Number of housing units completed and handed over to beneficiaries", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Percentage of conditional grant budget spent on service delivery programmes", "measurement_type": "percentage", "aggregation_rule": "average", "comparison_direction": "higher"},
        {"name": "Number of community stakeholder engagement sessions conducted", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Number of project monitoring visits conducted to construction sites", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Percentage of service delivery complaints resolved within stipulated timeframes", "measurement_type": "percentage", "aggregation_rule": "average", "comparison_direction": "higher"},
        {"name": "Number of training and development interventions conducted for staff", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Number of intergovernmental service delivery agreements signed", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Number of land parcels acquired for human settlements development", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Percentage of infrastructure projects completed on time and within budget", "measurement_type": "percentage", "aggregation_rule": "average", "comparison_direction": "higher"},
        {"name": "Number of performance management review sessions conducted", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Percentage of invoices paid within 30 days of receipt", "measurement_type": "percentage", "aggregation_rule": "average", "comparison_direction": "higher"},
        {"name": "Average number of days to finalise building plan applications", "measurement_type": "number", "aggregation_rule": "average", "comparison_direction": "lower"},
        {"name": "Number of fraud and corruption risk assessments conducted", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Number of supply chain management compliance assessments completed", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
        {"name": "Annual report submitted to Legislature by the legislated deadline", "measurement_type": "boolean", "aggregation_rule": "all", "comparison_direction": "exact"},
        {"name": "Number of ICT systems implemented or upgraded within the reporting period", "measurement_type": "number", "aggregation_rule": "sum", "comparison_direction": "higher"},
    ]

    def action_load_demo_app_plans(self):
        """Generate a complete demo APP Plan hierarchy cascading from APP Plan
        all the way down to Quarterly Targets with randomised planned values.

        Indicator source priority:
        1. ``demo_source_url`` starting with http/https → download PDF and extract text.
        2. ``demo_source_url`` as a local filename/path → read from disk.
        3. Uploaded ``file_data`` / ``file_name`` when the file is a PDF.
        4. Bundled KPI Excel in the module /data/ folder.
        5. Built-in fallback set of ~24 South African government indicators.
        """
        self.ensure_one()
        self = self.with_context(
            opms_skip_live_sync_refresh=True,
            opms_import_app_matrix=True,
        )
        self._ensure_operation_mode("demo_app_plans", admin_required=True)
        if not self.financial_year:
            raise UserError(_("Please select a Financial Year before loading demo plans."))

        fy = self.financial_year
        rng = random.Random()

        self._notify_progress(
            _("Demo APP Plans"),
            _("Collecting performance indicators for demo plan generation..."),
        )

        indicators = self._collect_demo_plan_indicators()
        if not indicators:
            raise UserError(_(
                "No performance indicators could be extracted from the configured source.\n"
                "Check the URL / path in 'Indicator Source URL or Path', or leave it blank to use "
                "the bundled Excel indicators."
            ))

        self._notify_progress(
            _("Demo APP Plans"),
            _("Building hierarchy from %s indicator(s) into '%s'...") % (len(indicators), fy.display_name),
        )

        # ── APP Plan ─────────────────────────────────────────────────────────
        plan_name = "ANNUAL PERFORMANCE PLAN %s (DEMO)" % (fy.name or fy.display_name)
        plan = self.env["opms.app.plan"].search(
            [("name", "=", plan_name), ("financial_year", "=", fy.id)], limit=1
        )
        if not plan:
            plan = self.env["opms.app.plan"].create({
                "name": plan_name,
                "financial_year": fy.id,
                "code": "DEMO-%s" % (fy.name or str(fy.id)),
            })

        # ── Quarters Q1–Q4 ───────────────────────────────────────────────────
        quarters = {}
        for qcode in ("q1", "q2", "q3", "q4"):
            qrec = self.env["opms.quarter"].search(
                [("app_plan_id", "=", plan.id), ("financial_year", "=", fy.id), ("code", "=", qcode)],
                limit=1,
            )
            if not qrec:
                qrec = self.env["opms.quarter"].create({
                    "app_plan_id": plan.id,
                    "financial_year": fy.id,
                    "code": qcode,
                    "name": qcode.upper(),
                })
            quarters[qcode] = qrec

        # ── Skeleton: Programme → Sub-Programme → Directorate → Output ───────
        destinations = []  # list of opms.output records
        for prog_code, prog_name in PROGRAMME_FALLBACK.items():
            programme = self.env["opms.programme"].search(
                [("code", "=", prog_code), ("name", "=", prog_name)], limit=1
            )
            if not programme:
                programme = self.env["opms.programme"].create({
                    "code": prog_code,
                    "name": prog_name,
                })

            prog_subs = [(k, v) for k, v in SUB_PROGRAMME_FALLBACK.items() if k.startswith(prog_code + ".")]
            for sub_code, sub_name in prog_subs:
                sub_prog = self.env["opms.sub.programme"].search(
                    [("programme_id", "=", programme.id), ("code", "=", sub_code)], limit=1
                )
                if not sub_prog:
                    sub_prog = self.env["opms.sub.programme"].create({
                        "programme_id": programme.id,
                        "code": sub_code,
                        "name": sub_name,
                    })

                dir_code = sub_code + ".1"
                dir_name = "%s.1 %s Management" % (sub_code, sub_name)
                directorate = self.env["opms.directorate"].search(
                    [("sub_programme_id", "=", sub_prog.id), ("code", "=", dir_code)], limit=1
                )
                if not directorate:
                    directorate = self.env["opms.directorate"].create({
                        "sub_programme_id": sub_prog.id,
                        "code": dir_code,
                        "name": dir_name,
                    })

                output_name = "Output: %s Delivery" % sub_name
                output = self.env["opms.output"].search(
                    [("directorate_id", "=", directorate.id), ("name", "=", output_name)], limit=1
                )
                if not output:
                    output = self.env["opms.output"].create({
                        "directorate_id": directorate.id,
                        "name": output_name,
                    })
                destinations.append(output)

        if not destinations:
            raise UserError(_(
                "No output records could be created. Check that Programmes and Sub-Programmes "
                "are properly configured."
            ))

        # ── Indicators: round-robin across destination outputs ────────────────
        created_annual = 0
        created_quarterly = 0

        for ind_idx, ind_data in enumerate(indicators):
            output = destinations[ind_idx % len(destinations)]
            ind_name = (ind_data.get("name") or "").strip()
            if not ind_name:
                continue
            mtype = ind_data.get("measurement_type") or "number"
            agg_rule = ind_data.get("aggregation_rule") or "sum"
            comp_dir = ind_data.get("comparison_direction") or "higher"

            output_indicator = self.env["opms.output.indicator"].search(
                [("output_id", "=", output.id), ("name", "=", ind_name)], limit=1
            )
            if not output_indicator:
                output_indicator = self.env["opms.output.indicator"].create({
                    "output_id": output.id,
                    "name": ind_name,
                    "indicator_type": "app",
                    "measurement_type": mtype,
                    "aggregation_rule": agg_rule,
                    "comparison_direction": comp_dir,
                })

            planned_annual = self._demo_random_planned_value(rng, mtype, is_annual=True, fy=fy)
            annual_target = self.env["opms.annual.target"].search(
                [
                    ("output_indicator_id", "=", output_indicator.id),
                    ("app_plan_id", "=", plan.id),
                    ("financial_year", "=", fy.id),
                ],
                limit=1,
            )
            if not annual_target:
                annual_target = self.env["opms.annual.target"].with_context(import_file=True).create({
                    "output_indicator_id": output_indicator.id,
                    "app_plan_id": plan.id,
                    "financial_year": fy.id,
                    "target_value": planned_annual,
                })
                created_annual += 1

            for qcode, qrec in quarters.items():
                qt = self.env["opms.quarterly.target"].search(
                    [("annual_target_id", "=", annual_target.id), ("quarter_id", "=", qrec.id)],
                    limit=1,
                )
                if not qt:
                    planned_q = self._demo_random_planned_value(rng, mtype, quarter_code=qcode, fy=fy)
                    self.env["opms.quarterly.target"].create({
                        "annual_target_id": annual_target.id,
                        "quarter_id": qrec.id,
                        "planned_target": planned_q,
                    })
                    created_quarterly += 1

        self._notify_progress(
            _("Demo APP Plans"),
            _("Completed: %s annual targets and %s quarterly targets created under '%s'.")
            % (created_annual, created_quarterly, plan_name),
        )

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Demo APP Plans Loaded"),
                "message": _(
                    "Demo plan '%s' created.\nAnnual targets: %s | Quarterly targets: %s"
                ) % (plan_name, created_annual, created_quarterly),
                "type": "success",
                "sticky": True,
            },
        }

    def _collect_demo_plan_indicators(self):
        """Collect indicator definitions from the best available source.

        Source priority:
        1. ``demo_source_url`` starting with http/https (download PDF, extract text).
        2. ``demo_source_url`` as a local path (relative to /data/ or absolute).
        3. Uploaded ``file_data`` when ``file_name`` ends with ``.pdf``.
        4. Bundled KPI Excel file in /data/.
        5. Built-in fallback indicator set.
        """
        url = (self.demo_source_url or "").strip()

        # 1. Remote URL
        if url.lower().startswith(("http://", "https://")):
            try:
                content = self._fetch_url_bytes(url)
                parsed = self._parse_indicators_from_text(self._extract_text_from_pdf_bytes(content))
                if parsed:
                    _logger.info("opms demo_app_plans: %d indicator(s) from URL %s", len(parsed), url)
                    return parsed
                _logger.warning("opms demo_app_plans: no indicators extracted from URL %s, falling back", url)
            except Exception as exc:
                _logger.warning("opms demo_app_plans: URL extraction failed (%s), falling back", exc)

        # 2. Local file path
        elif url:
            local_path = url if os.path.isabs(url) else os.path.join(self._module_data_path(), url)
            try:
                with open(local_path, "rb") as fh:
                    content = fh.read()
                if local_path.lower().endswith(".pdf"):
                    parsed = self._parse_indicators_from_text(self._extract_text_from_pdf_bytes(content))
                else:
                    parsed = self._extract_indicators_from_excel(content)
                if parsed:
                    return parsed
            except Exception as exc:
                _logger.warning("opms demo_app_plans: local path extraction failed (%s), falling back", exc)

        # 3. Uploaded PDF
        if self.file_data and (self.file_name or "").lower().endswith(".pdf"):
            try:
                parsed = self._parse_indicators_from_text(
                    self._extract_text_from_pdf_bytes(base64.b64decode(self.file_data))
                )
                if parsed:
                    return parsed
            except Exception as exc:
                _logger.warning("opms demo_app_plans: uploaded PDF extraction failed (%s), falling back", exc)

        # 4. Bundled Excel
        try:
            excel_path = os.path.join(self._module_data_path(), "KPI 2025-26_Remapped-UPDATED.xlsx")
            if os.path.exists(excel_path):
                with open(excel_path, "rb") as fh:
                    parsed = self._extract_indicators_from_excel(fh.read())
                if parsed:
                    _logger.info("opms demo_app_plans: %d indicator(s) from bundled Excel", len(parsed))
                    return parsed
        except Exception as exc:
            _logger.warning("opms demo_app_plans: bundled Excel extraction failed (%s), falling back", exc)

        # 5. Built-in fallback
        return self._DEMO_INDICATOR_FALLBACK[:]

    def _extract_indicators_from_excel(self, excel_bytes):
        """Extract unique indicator names from an Excel workbook and infer properties."""
        try:
            wb = openpyxl.load_workbook(io.BytesIO(excel_bytes), data_only=True, read_only=True)
            ws = wb[wb.sheetnames[0]]
            headers = [self._value_to_text(ws.cell(1, c).value) for c in range(1, ws.max_column + 1)]
            ind_col = next(
                (i + 1 for i, h in enumerate(headers)
                 if h in ("Output_ Indicator", "Output Indicator", "Indicator")),
                None,
            )
            if not ind_col:
                return []
            seen = set()
            result = []
            for row_num in range(2, ws.max_row + 1):
                name = self._value_to_text(ws.cell(row_num, ind_col).value).strip()
                if name and name not in seen and len(name) >= 10:
                    seen.add(name)
                    mtype = self._infer_measurement_type(name, None, {})
                    result.append({
                        "name": name,
                        "measurement_type": mtype,
                        "aggregation_rule": self._infer_aggregation_rule(mtype, name),
                        "comparison_direction": self._infer_comparison_direction(mtype, name),
                    })
            return result
        except Exception:
            return []

    def _extract_text_from_pdf_bytes(self, pdf_bytes):
        """Extract plain text from PDF bytes using the best available library.

        Attempts: pypdf → PyPDF2 → pdfminer.six → raw byte scan.
        """
        for mod_name in ("pypdf", "PyPDF2"):
            try:
                mod = __import__(mod_name)
                reader_cls = getattr(mod, "PdfReader", None) or getattr(mod, "PdfFileReader", None)
                if reader_cls:
                    reader = reader_cls(io.BytesIO(pdf_bytes))
                    pages = getattr(reader, "pages", None)
                    if pages is None:
                        pages = [reader.getPage(i) for i in range(reader.numPages)]
                    texts = []
                    for page in pages:
                        fn = getattr(page, "extract_text", None) or getattr(page, "extractText", None)
                        texts.append(fn() or "" if fn else "")
                    return "\n".join(texts)
            except ImportError:
                continue
            except Exception:
                continue

        # Try pdfminer.six
        try:
            from pdfminer.high_level import extract_text as _pdfminer_extract  # noqa: PLC0415
            return _pdfminer_extract(io.BytesIO(pdf_bytes))
        except ImportError:
            pass
        except Exception:
            pass

        # Last resort: scan raw PDF bytes for readable string literals
        try:
            text = pdf_bytes.decode("latin-1", errors="replace")
            parts = re.findall(r"\(([^()]{10,250})\)", text)
            return "\n".join(parts)
        except Exception:
            return ""

    def _fetch_url_bytes(self, url):
        """Download *url* and return the raw response bytes."""
        import urllib.request  # noqa: PLC0415
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (OPMS/1.0)"})
            with urllib.request.urlopen(req, timeout=30) as response:
                return response.read()
        except Exception as exc:
            raise UserError(_("Could not download from URL: %s\n\nError: %s") % (url, exc))

    def _parse_indicators_from_text(self, text):
        """Extract performance-indicator-like lines from plain text (e.g. PDF extract)."""
        if not text:
            return []
        result = []
        seen = set()
        for line in text.splitlines():
            line = re.sub(r"\s+", " ", line).strip()
            if not line or len(line) < 15 or len(line) > 350:
                continue
            # Skip lines that are clearly not indicator sentences
            if re.fullmatch(r"[\d\s.,:;/\\()\-]+", line):
                continue
            if re.match(r"^\s*(?:page|table|figure|section|chapter|appendix)\s*\d*\s*$", line, re.IGNORECASE):
                continue
            # Accept lines that contain indicator-pattern keywords
            if re.search(
                r"\b(number of|percentage|rate of|proportion|level of|degree of|extent to|"
                r"average number|achieved|implemented|submitted|approved|completed|conducted|"
                r"developed|established|maintained|reviewed|finalised|finalized|tabled|"
                r"published|issued|registered|verified|inspected|assessed|audited)\b",
                line, re.IGNORECASE,
            ):
                if line not in seen:
                    seen.add(line)
                    mtype = self._infer_measurement_type(line, None, {})
                    result.append({
                        "name": line,
                        "measurement_type": mtype,
                        "aggregation_rule": self._infer_aggregation_rule(mtype, line),
                        "comparison_direction": self._infer_comparison_direction(mtype, line),
                    })
                    if len(result) >= 300:
                        break
        return result

    def _demo_random_planned_value(self, rng, measurement_type, quarter_code=None, fy=None, is_annual=False):
        """Return a plausible randomised planned target value for demo plan generation."""
        if measurement_type == "number":
            base = rng.randint(3, 24)
            return str(base * 4 if is_annual else base)

        if measurement_type == "percentage":
            return str(rng.randint(70, 95))

        if measurement_type == "date":
            fy_end = (fy.date_to if fy and fy.date_to else date.today())
            fy_start = (fy.date_from if fy and fy.date_from else fy_end.replace(month=4, day=1))
            span = max(1, (fy_end - fy_start).days)
            if is_annual:
                return fy_end.strftime("%Y-%m-%d")
            q_num = {"q1": 1, "q2": 2, "q3": 3, "q4": 4}.get(quarter_code or "q4", 4)
            q_end = fy_start + timedelta(days=span * q_num // 4)
            return q_end.strftime("%Y-%m-%d")

        if measurement_type == "boolean":
            return "Yes"

        if measurement_type == "milestone":
            return rng.choice([
                "Annual report tabled in Parliament by the stipulated deadline",
                "Strategy document submitted and approved by the Executive Authority",
                "Implementation plan developed and approved by the Accounting Officer",
                "Review report finalized and submitted to the relevant committee",
                "Service delivery improvement plan published on the departmental website",
            ])

        # text / default
        return "Activity fully completed as per the approved operational plan"

    # ── Feature 4 – Load demo seed submissions ──────────────────────────────
    # Visible to Settings / Administrator group only (enforced in the view).

    def action_load_demo_submissions(self):
        """Generate scrambled demo submissions for every quarterly target in the
        selected financial year.  A dummy evidence file is attached to every
        non-draft submission so the portal workflow operates correctly."""
        self.ensure_one()
        self._ensure_operation_mode("demo_submissions", admin_required=True)
        if not self.financial_year:
            raise UserError(_("Please select a Financial Year to load demo submissions for."))

        fy = self.financial_year
        rng = random.Random()  # non-deterministic — each run produces a different scramble

        quarterly_targets = self.env["opms.quarterly.target"].search(
            [("financial_year", "=", fy.id)]
        )
        if not quarterly_targets:
            raise UserError(
                _(
                    "No quarterly targets found for '%s'.\n"
                    "Please import the APP Matrix first before loading demo submissions."
                )
                % fy.display_name
            )

        # Delete all existing demo submissions for this FY so the run is fully fresh
        existing_demos = self.env["opms.reporting.submission"].search(
            [("name", "like", "[DEMO]"), ("financial_year", "=", fy.id)]
        )
        if existing_demos:
            existing_demos.sudo().unlink()

        tune = self._get_demo_seed_tuning()
        dummy_evidence = base64.b64encode(_DUMMY_EVIDENCE_BYTES)
        created = skipped = 0
        prepared_rows = []
        total_targets = len(quarterly_targets)
        prep_notify_step = tune["prep_notify_step"]
        create_chunk_size = tune["chunk_size"]
        create_notify_every_chunks = tune["create_notify_every_chunks"]

        def _notify_progress(message):
            user = self.env.user
            notify = getattr(user, "notify_info", None)
            if callable(notify):
                try:
                    notify(message=message, title=_("Demo Seed Progress"), sticky=False)
                except Exception:
                    _logger.info("Demo seed progress: %s", message)
            else:
                _logger.info("Demo seed progress: %s", message)

        _notify_progress(
            _("Starting demo seed for %s quarterly target(s) in %s (chunk=%s, prep-step=%s).")
            % (total_targets, fy.display_name, create_chunk_size, prep_notify_step)
        )

        for idx, qt in enumerate(quarterly_targets, start=1):
            # Randomly leave ~28 % of targets unsubmitted so the dashboard shows
            # a realistic mix of Loaded / Not Loaded across indicators and quarters.
            if rng.random() < 0.28:
                skipped += 1
                continue

            indicator = qt.output_indicator_id
            mtype = indicator.measurement_type if indicator else "text"
            workflow_status = rng.choice(_DEMO_WORKFLOW_POOL)
            actual_value = self._generate_demo_actual(
                rng, mtype, qt.planned_target or "10", workflow_status, qt
            )
            comments = rng.choice(_DEMO_COMMENTS)
            deviation = rng.choice(_DEMO_DEVIATIONS)
            remedial = rng.choice(_DEMO_REMEDIALS) if deviation else None

            quarter_label = (qt.quarter_id.code or "QX").upper()
            year_label = fy.name or str(fy.id)
            indicator_name = indicator.name if indicator else "Indicator"

            prepared_rows.append({
                "qt_id": qt.id,
                "quarter_label": quarter_label,
                "year_label": year_label,
                "workflow_status": workflow_status,
                "submission_vals": {
                    "name": f"[DEMO] {indicator_name} \u2014 {quarter_label} {year_label}",
                    "quarterly_target_id": qt.id,
                    "submitted_by": self.env.user.id,
                    "submission_date": fields.Datetime.now(),
                    "workflow_status": workflow_status,
                    "comments": comments,
                    "reason_for_deviation": deviation,
                    "remedial_actions": remedial,
                    "actual_value": actual_value,
                },
            })

            if idx % prep_notify_step == 0:
                _notify_progress(
                    _("Prepared %s/%s targets (%s submissions to create, %s skipped).")
                    % (idx, total_targets, len(prepared_rows), skipped)
                )

        if prepared_rows:
            submission_ctx = dict(
                self.env.context,
                opms_allow_closed_submission_seed=True,
                opms_skip_submission_auto_status_sync=True,
                tracking_disable=True,
                mail_create_nolog=True,
                mail_notrack=True,
                mail_notify_force_send=False,
            )
            evidence_ctx = dict(
                self.env.context,
                opms_skip_submission_auto_status_sync=True,
                tracking_disable=True,
                mail_create_nolog=True,
                mail_notrack=True,
                mail_notify_force_send=False,
            )

            total_to_create = len(prepared_rows)
            evidence_total = 0
            chunk_count = 0
            for start in range(0, total_to_create, create_chunk_size):
                chunk_count += 1
                chunk = prepared_rows[start:start + create_chunk_size]
                submissions = self.env["opms.reporting.submission"].with_context(submission_ctx).create(
                    [row["submission_vals"] for row in chunk]
                )

                evidence_vals = []
                for row, submission in zip(chunk, submissions):
                    if row["workflow_status"] != "draft":
                        evidence_vals.append({
                            "name": f"[DEMO] Evidence \u2014 {row['quarter_label']} {row['year_label']}",
                            "quarterly_target_id": row["qt_id"],
                            "reporting_submission_id": submission.id,
                            "file": dummy_evidence,
                            "file_name": f"demo_evidence_{row['qt_id']}.txt",
                        })

                if evidence_vals:
                    self.env["opms.evidence"].with_context(evidence_ctx).create(evidence_vals)
                    evidence_total += len(evidence_vals)

                created += len(chunk)
                if (chunk_count % create_notify_every_chunks == 0) or (created >= total_to_create):
                    _notify_progress(
                        _("Created %s/%s submissions and %s evidence file(s).")
                        % (created, total_to_create, evidence_total)
                    )

            _notify_progress(
                _("Demo seed completed: %s submissions created, %s skipped.")
                % (created, skipped)
            )

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Demo Submissions Loaded"),
                "message": _(
                    "Created: %s demo submission(s).  Left unsubmitted (randomised): %s."
                ) % (created, skipped),
                "type": "success" if created else "warning",
                "sticky": True,
            },
        }

    def _generate_demo_actual(self, rng, measurement_type, planned, workflow_status, qt):
        """Return a plausible demo actual value for the given indicator type."""
        if workflow_status == "draft":
            return None

        if measurement_type == "number":
            try:
                num_str = re.sub(r"[^\d.]", "", str(planned).split()[0].replace(",", "."))
                base = float(num_str) if num_str else 10.0
            except (ValueError, TypeError, IndexError):
                base = 10.0
            actual = round(base * rng.uniform(0.7, 1.4))
            return str(actual)

        if measurement_type == "percentage":
            return str(round(rng.uniform(50.0, 100.0), 1))

        if measurement_type == "date":
            q = qt.quarter_id
            ref = q.end_date if (q and q.end_date) else date.today()
            return (ref + timedelta(days=rng.randint(-20, 10))).strftime("%Y-%m-%d")

        if measurement_type == "boolean":
            return rng.choice(["Yes", "Yes", "Yes", "No"])

        if measurement_type == "milestone":
            return rng.choice([
                "Milestone completed and signed off by the relevant authority.",
                "Milestone achieved within the stipulated timeframe.",
                "Milestone partially achieved; final steps are in progress.",
            ])

        # text / default
        return rng.choice([
            "Activity completed as planned for this quarter.",
            "Deliverable submitted to the relevant authority.",
            "Work is ongoing with no major issues identified.",
        ])
