from werkzeug import urls
import io
import json
import xlsxwriter
from odoo import api, fields, models, _
from odoo.tools.json import json_default
from odoo.tools import html2plaintext
import base64
from odoo.exceptions import ValidationError
from openpyxl import load_workbook
from datetime import datetime, date, time


class ProjectTask(models.Model):
    """Project Task"""
    _inherit = 'project.task'

    stages = fields.Selection([
        ('preparer', 'Preparer'),
        ('first_reviewer', 'First Reviewer'),
        ('second_reviewer', 'Reviewer'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ], 'State', default='preparer', tracking=True)
    sub_task_count = fields.Integer(string="Sub Task Count", compute="_compute_sub_task_count")
    reference_number = fields.Char(string="Reference Number")

    audit_steps = fields.Html(string="Audit Steps",
                              help="Detailed steps and procedures to be followed during the audit.")

    guidance = fields.Html(
        string="Guidance",
        help="Provide specific instructions or guidelines for the audit process."
    )

    work_done = fields.Html(
        string="Work Done",
        help="Record the work completed during the audit process."
    )

    attachment_id = fields.Many2many('ir.attachment',
                                     help="The file generated by edi_format_id when the invoice is posted (and this document is processed)."
                                     )
    upload_document_name = fields.Char(related='attachment_id.name')

    sample_selection = fields.Html(
        string="Sample Selection",
        help="Details about the sample selection criteria and process used for auditing."
    )

    conclusion = fields.Html(
        string="Conclusion",
        help="Summarize the findings and outcomes of the audit."
    )
    upload_report_document_name = fields.Char('Upload Document Name',help="Uploaded report document")
    attachment_report_ids = fields.Many2many('ir.attachment', 'report_rel',
                                                   string="Attachment", tracking=True)
    upload_draft_audit_document_name = fields.Char('Upload Document Name', help="Uploaded report document")
    attachment_draft_audit_ids = fields.Many2many('ir.attachment', 'audit_document_rel',
                                             string="Attachment", tracking=True)

    upload_final_audit_document_name = fields.Char('Upload Document Name', help="Uploaded report document")
    attachment_final_audit_ids = fields.Many2many('ir.attachment', 'final_document_rel',
                                                  string="Attachment", tracking=True)
    upload_quality_assessment_document_name = fields.Char('Upload Document Name', help="Uploaded report document")
    attachment_quality_assessment_audit_ids = fields.Many2many('ir.attachment', 'quality_assessment_rel',
                                                  string="Attachment", tracking=True)
    documents = fields.Html(
        string="Documents",
        help="List or describe the documents reviewed or used during the audit."
    )
    request_documents = fields.Html(
        string="Request Documents",
        help="Details about the documents requested for the audit."
    )

    upload_document = fields.Binary(
        string="Upload Document",
        help="Upload relevant documents to be included in the audit."
    )
    attachment_notification_ids = fields.Many2many('ir.attachment','notification_rel',
                                      string="Attachment", tracking=True)
    upload_notification_name = fields.Char(string="Name")
    comments = fields.Html(
        string="General Comments",
        help="Details about the General Comments."
    )
    audit_objective = fields.Html(
        string="Audit Objective",
        help="Details about the Audit  Objective."
    )
    special_instruction = fields.Html(
        string="Special  Instruction",
        help="Details about the Special  Instruction."
    )
    internal_audit_ids = fields.Many2many('res.users',string='Internal Audit Personal Assigned')
    auditor_id = fields.Many2one('res.users',string='Auditor In Charge')
    objective = fields.Html(string="Objective",help="Add the objective")
    rules = fields.Html(string = "Add the Laws,Rules,Regulations,Policies and Procedures",help="Add the Laws")
    skill = fields.Html(string = "Key Performance Area's",help="Add the performance areas")
    system_objective = fields.Html(string = "Audit Objective",help="Add the objective for the audit")
    component_nature = fields.Html(string = "Nature of Component",help="Add the component of nature")
    share_document = fields.Binary(
        string="Share Document",
        help="Share documents related to the audit with stakeholders."
    )
    share_document_ids = fields.Many2many('documents.document',string='Share Document', help="Share documents related to the audit with stakeholders.", compute='_compute_share_document_ids',
    store=False)
    references = fields.Html(
        string="References",
        help="Include references or citations used in the audit."
    )

    finding_raised = fields.Html(
        string="Finding Raised",
        help="Document the issues or findings identified during the audit."
    )

    type = fields.Many2one('task.type', default=lambda self: self._get_default_type())
    manager_id =  fields.Many2one("hr.employee",string="Manager",tracking=True)
    audit_finding_ids = fields.Many2many('audit.finding',
                                        string="Audit Finding", tracking=True)
    hr_team_id = fields.Many2one('hr.department', string="Team", tracking=True)
    user_preparer_ids = fields.Many2one('res.users',
                                        string="Preparer", tracking=True, related='project_id.user_preparer_ids',readonly=False)
    user_reviewer_1_ids = fields.Many2one('res.users',string="First Reviewer", tracking=True, related='project_id.user_reviewer_1_ids',readonly=False)
    user_reviewer_2_ids = fields.Many2one('res.users', string="Reviewer ", tracking=True,related='project_id.user_reviewer_2_ids',readonly=False)
    user_approver = fields.Many2one('res.users',string="Approver", tracking=True, related='project_id.user_approver',readonly=False)
    user_approver_ids = fields.Many2many('res.users','user_approver_project_rel',string="Approver", tracking=True)
    control_assessment_ids = fields.One2many("control.assessment", 'project_control_id',string="Control Assessment")
    activity_description_ids = fields.One2many("activity.description", 'project_activity_description_id',string="Activity Description")
    professional_development_ids = fields.One2many("professional.development",'professional_development_id',string="Professional Development")
    time_budget_task_ids = fields.One2many("time.budget", 'task_time_id',string="Time Budget")
    state = fields.Selection([
        ('01_in_progress', 'In Progress'), ('02_changes_requested', 'Changes Requested'),
        ('03_approved', 'Approved'), ('1_done', 'Done'),('1_canceled','Canceled'),('04_waiting_normal','Waiting')],
        string='State')
    stages_id = fields.Many2one("project.task.type",string="Stages")
    survey_details = fields.One2many('survey.details','survey_details_id')
    memo_attachment_id = fields.Many2many('ir.attachment','memo_attachment_id',string="Upload Engagement Memorandum")
    audit_pgm_id = fields.One2many('audit.pgm','audit_details_id')
    mom_attachment_id = fields.Many2many('ir.attachment', 'mom_attachment_id',
                                         string="Upload Minutes of Meeting")
    client_survey_ids = fields.One2many('client.survey','client_survey_id')
    risk_ids = fields.Many2many('business.risk', string="Risk")
    task_type = fields.Selection([('plan_1', 'Plan 1'), ('plan_2', 'Plan 2'),
                                  ('plan_3', 'Plan 3'), ('plan_4', 'Plan 4'),
                                  ('plan_5', 'Plan 5'), ('plan_6', 'Plan 6'),
                                  ('plan_7', 'Plan 7'), ('plan_8', 'Plan 8'),
                                  ('plan_9', 'Plan 9'), ('plan_10', 'Plan 10'),('exec_1', 'EXEC 1'),
                                  ('exec_2', 'EXEC 2'), ('exec_3', 'EXEC 3'),
                                  ('rep_1', 'REP 1'), ('rep_2', 'REP 2'),
                                  ('rep_3', 'REP 3'), ('rep_4', 'REP 4'),  ('rep_5', 'REP 5'),('pro_mgt_1','PM 1'),('pro_mgt_2','PM 2'),('pro_mgt_3','PM 3'),('pro_mgt_4','PM 4'),('pro_mgt_5','PM 5')], related="type.task_type", store=True)
    population_type = fields.Selection([('class_transaction',
                                         'Class of transactions and its related disclosures'),
                                        ('account_balance',
                                         'Account balance and its related disclosures'),
                                        ('disclosure_class_transaction',
                                         'Disclosure that is similar in nature to classes of transactions and events'),
                                        ('disclosure_account_balances',
                                         'Disclosure that is similar in nature to account balances')
                                        ])
    name_population = fields.Char(string="Name of the population")
    recorded_amount = fields.Float(string="Recorded amount")
    completeness = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Completeness")
    occurrence = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Occurrence")
    accuracy = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Accuracy")
    cut_off = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Cut-off")
    existence = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Existence")
    valuation = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Accuracy, valuation and allocation")
    obligations = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Rights and obligations")

    classification = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Classification")
    presentation = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Presentation")
    revised = fields.Selection([('yes', 'Yes'), ('no', 'No')],string="Materiality revised", help="Indicate whether the preliminary materiality was revised during the course of the audit")
    preliminary_materiality_overall = fields.Float(string="Preliminary overall/ specific materiality")
    preliminary_performance_materiality = fields.Float(string="Preliminary performance materiality")
    revised_materiality_overall = fields.Float(string="Revised overall/ specific materiality")
    revised_performance_materiality = fields.Float(string="Revised performance materiality")
    final_materiality_overall = fields.Float(string="Final overall/ specific materiality")
    final_performance_materiality = fields.Float(string="Final performance materiality")
    level_assurance = fields.Selection([('1', '1'), ('2', '2'), ('3', '3')], string="Level of assurance",
                           help="Level of assurance required from substantive tests of details")
    define_population = fields.Char(string="Define the population",
                                    help="Define the population; i.e. the entire set of data from which the sample will be drawn")
    define_sampling = fields.Char(string="Define the sampling",
                                  help="Define the sampling unit; i.e. the individual items of the sampling population")
    indicate_sample_selection = fields.Selection([
        ('random', 'Random selection'), ('systematic', 'Systematic selection'),
        ('haphazard', 'Haphazard selection'), ('monetary', 'Monetary unit sampling'),
        ('block', 'Block selection')],string="Indicate The Sample Selection",
        help="Indicate the sample selection method that will be used to select items for testing (e.g. haphazard, systematic, random, etc.): (Select from the drop-down menu.)")
    sample_size_3 = fields.Float(string="Sample Size", help="Sample size calculated per the formula (Level of assurance x Population amount ÷ Performance materiality)")
    mini_sample_size_3 = fields.Float(string="Minimum Sample Size",)
    final_sample_size_3 = fields.Float(string="Final sample size", help="Sample sizes based the population being audited")
    sample_size_2 = fields.Float(string="Sample Size", help="Sample size calculated per the formula (Level of assurance x Population amount ÷ Performance materiality)")
    mini_sample_size_2 = fields.Float(string="Minimum Sample Size",)
    final_sample_size_2 = fields.Float(string="Final sample size", help="Sample sizes based the population being audited")
    sample_size_1 = fields.Float(string="Sample Size", help="Sample size calculated per the formula (Level of assurance x Population amount ÷ Performance materiality)")
    mini_sample_size_1 = fields.Float(string="Minimum Sample Size",)
    final_sample_size_1 = fields.Float(string="Final sample size", help="Sample sizes based the population being audited")
    initial_sample_size = fields.Float(string="Initial Sample Size",)

    work_performed = fields.Html(string="Worked Performed")
    risk_analysis_id = fields.One2many('risk.analysis','task_id')
    background_body = fields.Html("Background", copy=False)

    project_share_doc_ids = fields.Many2many(
        'documents.document',
        string='Project Share Documents',
        compute='_compute_project_share_doc_ids',
        store=False,
        help="Documents shared at the project level."
    )
    project_checklist_id = fields.One2many('project.checklist','project_task_id',string='Project Checklist')
    project_satisfaction_id = fields.One2many('client.survey','project_task_id',string='Client Survey')
    sequence_no = fields.Char(
        string="Working Paper Number",
        default=lambda self: _('New'),
        help="Sequence will be automatically created",
        store=True,
        copy=False,
        readonly=True,
    )

    @api.onchange('project_id')
    def _onchange_project_id(self):
        """Onchange project"""
        for rec in self:
            rec.user_approver = self.project_id.user_approver.id
            rec.user_preparer_ids = self.project_id.user_preparer_ids.id
            rec.user_reviewer_2_ids = self.project_id.user_reviewer_2_ids.id

    @api.onchange('type')
    def _onchange_type(self):
        """Auto-fill background when type changes."""
        if self.type and self.type.edms_template and self.type.edms_template.background_body:
            self.background_body = self.type.edms_template.background_body
        else:
            self.background_body = ''


    @api.depends('project_id.share_doc_ids')
    def _compute_project_share_doc_ids(self):
        for record in self:
            if record.project_id:
                record.project_share_doc_ids = record.project_id.share_doc_ids
            else:
                record.project_share_doc_ids = False


    def _compute_share_document_ids(self):
        for record in self:
            if record.id:
                docs = self.env['documents.document'].search([
                    ('res_model', '=', 'project.task'),
                    ('res_id', '=', record.id),
                ])
                record.share_document_ids = docs
            else:
                record.share_document_ids = False

    @api.model
    def _get_default_type(self):
        task_name = self.name
        task_type = self.env['task.type'].sudo().search([('name', 'ilike', f"%{task_name}%")], limit=1)
        return task_type.id if task_type else False


    @api.onchange('level_assurance', 'recorded_amount', 'preliminary_performance_materiality', 'mini_sample_size_2', 'mini_sample_size_3', 'mini_sample_size_1')
    def _onchange_sample_size(self):
        for rec in self:
            sample_size_3 = 0
            sample_size_2 = 0
            sample_size_1 = 0
            initial_sample_size = 0
            if rec.preliminary_performance_materiality:
                sample_size_3 = round((rec.recorded_amount * 3)/ rec.preliminary_performance_materiality)
                sample_size_2 = round((rec.recorded_amount * 2)/ rec.preliminary_performance_materiality)
                sample_size_1 = round((rec.recorded_amount * 1)/ rec.preliminary_performance_materiality)
            rec.sample_size_3 = sample_size_3
            rec.final_sample_size_3 = sample_size_3 if sample_size_3 > rec.mini_sample_size_3 else rec.mini_sample_size_3
            rec.sample_size_2 = sample_size_2
            rec.final_sample_size_2 = sample_size_2 if sample_size_2 > rec.mini_sample_size_2 else rec.mini_sample_size_2
            rec.sample_size_1 = sample_size_1
            rec.final_sample_size_1 = sample_size_1 if sample_size_1 > rec.mini_sample_size_1 else rec.mini_sample_size_1
            if rec.level_assurance == '1':
                initial_sample_size = rec.final_sample_size_1
            if rec.level_assurance == '2':
                initial_sample_size = rec.final_sample_size_2
            if rec.level_assurance == '3':
                initial_sample_size = rec.final_sample_size_3
            rec.initial_sample_size = initial_sample_size


    @api.onchange('revised', 'preliminary_materiality_overall',
                  'preliminary_performance_materiality', 'revised_materiality_overall',
                  'revised_performance_materiality')
    def _onchange_materiality(self):
        """Onchange Materiality"""
        for rec in self:
            final_materiality_overall = rec.preliminary_materiality_overall
            final_performance_materiality = rec.preliminary_performance_materiality
            if rec.revised == 'yes':
                final_materiality_overall = rec.revised_materiality_overall if rec.revised_materiality_overall != 0 else rec.preliminary_materiality_overall
                final_performance_materiality = rec.revised_performance_materiality if rec.revised_performance_materiality != 0 else rec.preliminary_performance_materiality
            rec.final_materiality_overall = final_materiality_overall
            rec.final_performance_materiality = final_performance_materiality

    @api.onchange('hr_team_id')
    def _onchange_team_id(self):
        """Onchange Team"""
        for rec in self:
            user = []
            user_reviewer_2 = []
            user_approver = []
            users = []
            if rec.hr_team_id:
                users = rec.hr_team_id.employee_ids.mapped('user_id')
                user = [
                    employee.user_id.id
                    for employee in rec.hr_team_id.employee_ids
                    if any(role.type == 'Reviewer_1' for role in employee.role_ids)
                ]
                user_reviewer_2 = [
                    employee.user_id.id
                    for employee in rec.hr_team_id.employee_ids
                    if
                    any(role.type == 'Reviewer_2' for role in employee.role_ids)
                ]
                user_approver = [
                    employee.user_id.id
                    for employee in rec.hr_team_id.employee_ids
                    if
                    any(role.type == 'Approver' for role in employee.role_ids)
                ]
            rec.user_reviewer_1_ids = user
            rec.user_reviewer_2_ids = user_reviewer_2
            rec.user_approver = user_approver
            rec.user_ids = users

    def action_view_records(self):
        """Method for view records"""
        return {
            'name': 'Audit Reverts/ Review Notes',
            'type': 'ir.actions.act_window',
            'res_model': 'audit.revert',
            'domain': [('res_id', '=', self.id), ('res_model', '=', self._name)],
            'view_mode': 'list,form',
            'target': 'current',
        }

    @api.model_create_multi
    def create(self, vals_list):

        for vals in vals_list:
            if not vals.get('sequence') or vals['sequence'] == _('New'):
                vals['sequence_no'] = self.env['ir.sequence'].next_by_code(
                    'project.task')
            if vals.get('type') and not vals.get('background_body'):
                type_rec = self.env['task.type'].sudo().browse(vals['type'])
                if type_rec.sudo().edms_template and type_rec.sudo().edms_template.background_body:
                    vals[
                        'background_body'] = type_rec.sudo().edms_template.background_body
            # Handle parent task logic
            if vals.get('parent_id'):
                parent_task = self.env['project.task'].browse(int(vals.get('parent_id')))
                vals['stage_id'] = parent_task.stage_id.id
                vals['type'] = parent_task.type.id
                prefix = parent_task.stage_id.prefix or ""
                vals['reference_number'] = f"{prefix}: {parent_task.sub_task_count + 1}"

            # Handle project logic
            if vals.get('project_id'):
                project = self.env['project.project'].browse(int(vals.get('project_id')))
                if project.department_id:
                    vals['hr_team_id'] = project.department_id.id
                    vals['user_ids'] = project.team_member_ids.mapped('user_id')

                    # Optional: reviewer/approver lists
                    user_reviewer_1 = [
                        emp.user_id.id
                        for emp in project.department_id.employee_ids
                        if any(role.type == 'Reviewer_1' for role in emp.role_ids)
                    ]
                    user_reviewer_2 = [
                        emp.user_id.id
                        for emp in project.department_id.employee_ids
                        if any(role.type == 'Reviewer_2' for role in emp.role_ids)
                    ]
                    user_approver = [
                        emp.user_id.id
                        for emp in project.department_id.employee_ids
                        if any(role.type == 'Approver' for role in emp.role_ids)
                    ]
                    # Uncomment if you want to store these IDs in fields
                    # vals['user_reviewer_1_ids'] = user_reviewer_1
                    # vals['user_reviewer_2_ids'] = user_reviewer_2
                    # vals['user_approver_ids'] = user_approver or []
                if not vals.get('user_approver') and project.user_approver:
                    vals['user_approver'] = project.user_approver.id
                if not vals.get('user_preparer_ids') and project.user_preparer_ids:
                    vals['user_preparer_ids'] = project.user_preparer_ids.id
                if not vals.get('user_reviewer_2_ids') and project.user_reviewer_2_ids:
                    vals['user_reviewer_2_ids'] = project.user_reviewer_2_ids.id

        # Create all tasks
        records = super(ProjectTask, self).create(vals_list)
        return records

    @api.onchange('child_ids')
    def _compute_sub_task_count(self):
        """Calculate the sub-tasks"""
        for rec in self:
            rec.sub_task_count = len(rec.child_ids)

    def action_view_sub_task(self):
        return {
            'type': 'ir.actions.act_window',
            'name': 'Sub Task',
            'res_model': 'project.task',
            'view_mode': 'form',
            'views': [(self.env.ref('internal_audit_management.view_my_sub_task_form').id, 'form')],
            'res_id': self.id,  # Opens the current record
            'target': 'current',  # Opens in the same window
            'context': {
                'default_title': self.name,
                'active_id': self.id,
                'default_res_id': self.id,

            },
        }

    def action_view_request_documents(self):
        return {
            'name': 'Request Document',
            'type': 'ir.actions.act_window',
            'res_model': 'documents.request_wizard',
            'view_mode': 'form',
            'view_id': self.env.ref('documents.documents_request_form_view').id,
            'target': 'new',
            'context': {
                'default_res_id': self.id,
                'default_res_model': 'project.task',
            },
        }

    def action_request_details(self):
        return {
            'res_model': 'documents.document',
            'type': 'ir.actions.act_window',
            'name': _("%(project_name)s's Documents", project_name=self.name),
            'domain': [
                ('res_model', '=', 'project.task'),
                ('res_id', '=', self.id),
                ('attachment_id', '=', False)
            ],
            'view_mode': 'kanban,form',
            'context': {'default_res_model': 'project.task',
                        'default_res_id': self.id,
                        'limit_folders_to_project': True},
        }

    def get_list_url(self):
        """Method for create the url."""
        base_url = self.env['ir.config_parameter'].sudo().get_param(
            'web.base.url')
        Urls = urls.url_join(base_url,
                             'web#id=%s&model=task.project&view_type=form' % self.id)
        return Urls

    def action_review(self):
        """First Review"""
        mail_template = self.env.ref(
            'internal_audit_management.email_template_audit_procedure_to_review')
        recipient_ids = self.user_reviewer_2_ids
        partner = recipient_ids.mapped('partner_id')
        email_values = {
            'recipient_ids': [(6, 0, partner.ids)]
        }
        mail_template.send_mail(self.id, force_send=True,
                                email_values=email_values)
        self.message_post(body=_('The Audit Procedure %s was reviewed by %s') % (
        self.name, self.env.user.name))
        self.stages = 'first_reviewer'
        self.state = '01_in_progress'

    def action_2nd_review(self):
        """Second Review"""
        mail_template = self.env.ref('internal_audit_management.email_template_audit_procedure_to_approve')
        recipient_ids = self.user_approver
        partner = recipient_ids.mapped('partner_id')
        email_values = {
            'recipient_ids': [(6, 0, partner.ids)]
        }
        mail_template.send_mail(self.id, force_send=True,
                                email_values=email_values)
        self.message_post(
            body=_('The Audit Procedure %s was reviewed by %s') % (
                self.name, self.env.user.name))
        self.stages = 'second_reviewer'
        self.state = '01_in_progress'

    def action_approve(self):
        """First Review"""
        mail_template = self.env.ref('internal_audit_management.email_template_audit_procedure_to_approved')
        recipient_ids = self.user_ids
        partner = recipient_ids.mapped('partner_id')
        email_values = {
            'recipient_ids': [(6, 0, partner.ids)]
        }
        mail_template.send_mail(self.id, force_send=True,
                                email_values=email_values)
        self.message_post(
            body=_('The Audit Procedure %s was Approved by %s') % (
                self.name, self.env.user.name))
        self.stages = 'approved'
        self.state = '03_approved'

    def action_reject(self):
        """First Review"""
        self.state = '1_canceled'
        mail_template = self.env.ref('internal_audit_management.email_template_audit_procedure_to_rejected')
        recipient_ids = self.user_ids
        partner = recipient_ids.mapped('partner_id')
        email_values = {
            'recipient_ids': [(6, 0, partner.ids)]
        }
        mail_template.send_mail(self.id, force_send=True,
                                email_values=email_values)
        self.message_post(
            body=_('The Audit Procedure %s was Rejected by %s') % (
                self.name, self.env.user.name))
        self.stages = 'rejected'

    def action_revert(self):
        return {
            'name': 'Revert Procedure',
            'type': 'ir.actions.act_window',
            'res_model': 'project.task.revert',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_task_id': self.id,
            },
        }

    def action_export_lines(self):
        plan = self.id
        data = {
            'model_id': self.id,
            'plan': plan,
            'task_type': self.task_type,
        }
        return {
            'type': 'ir.actions.report',
            'data': {'model': self._name,
                     'options': json.dumps(data,
                                           default=json_default),
                     'output_format': 'xlsx',
                     'report_name': 'Audit Program',
                     },
            'report_type': 'xlsx',
        }

    def get_xlsx_report(self, data, response):
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})
        sheet = workbook.add_worksheet()
        plan = self.env[self._name].browse(int(data['plan']))
        small_head = workbook.add_format(
            {'align': 'center', 'font_size': 11})  # ✅ Numeric value
        txt = workbook.add_format(
            {'font_size': 10, 'align': 'center',  # ✅ Numeric value
             'valign': 'vcenter', 'text_wrap': True})
        date_format = workbook.add_format(
            {'num_format': 'd-m-yyyy', 'align': 'center'})
        text_format = workbook.add_format(
            {'align': 'left', 'font_size': 10, 'text_wrap': True})
        # small_head = workbook.add_format(
        #     {'align': 'center', 'font_size': '11px'})
        # txt = workbook.add_format({'font_size': '10px', 'align': 'center',
        #                            'valign': 'vcenter', 'text_wrap': True})
        # date_format = workbook.add_format({'num_format': 'd-m-yyyy', 'align': 'center'})
        # text_format = workbook.add_format({'align': 'left', 'font_size': 10, 'text_wrap': True})
        sheet.set_column(1, 11, 12, txt)
        txt_wrap = workbook.add_format({'text_wrap': True})
        if data['task_type'] == 'exec_1':
            sheet.write('A1', "Task", small_head)
            sheet.write('B1', "Process", small_head)
            sheet.write('C1', "Risk Identified ", small_head)
            sheet.write('D1', "Controls Identified", small_head)
            sheet.write('E1', "Audit Procedures to Test Control Effectiveness", small_head)
            sheet.write('F1', "Timeline", small_head)
            sheet.write('G1', "Assigned To", small_head)
            sheet.write('H1', "WP Reference", small_head)
            row = 1
            col = 0
            for line in plan.audit_pgm_id:
                sheet.write(row, col,line.audit_details_id.name, txt)
                sheet.write(row, col + 1,html2plaintext(line.process), txt_wrap)
                sheet.write(row, col + 2, html2plaintext(line.risk_identified), txt_wrap)
                sheet.write(row, col + 3, html2plaintext(line.controls_identified), txt_wrap)
                sheet.write(row, col + 4, html2plaintext(line.audit_procedures), txt_wrap)
                sheet.write(row, col + 5, html2plaintext(line.timeline), txt_wrap)
                sheet.write(row, col + 6, html2plaintext(line.responsibility_assigned_to), txt_wrap)
                sheet.write(row, col + 7, html2plaintext(line.wp_reference), txt_wrap)
                row += 1

        elif data['task_type'] == 'plan_8':
            sheet.write('A1', "Task", small_head)
            sheet.write('B1', "Risk ID", small_head)
            sheet.write('C1', "Category Tag ", small_head)
            sheet.write('D1', "Inherent Risk Score", small_head)
            sheet.write('E1', "Control Effectiveness", small_head)
            sheet.write('F1', "Residual Risk Score", small_head)
            sheet.write('G1', "Owner", small_head)
            sheet.write('H1', "Risk Severity", small_head)
            sheet.write('I1', "Risk Status", small_head)
            sheet.write('J1', "Next Review", small_head)
            row = 1
            col = 0
            for line in plan.risk_ids:
                categories = ', '.join(line.category.mapped('name'))
                sheet.write(row, col, plan.name, txt)
                sheet.write(row, col + 1, line.name, text_format)
                sheet.write(row, col + 2, categories,text_format)
                sheet.write(row, col + 3,line.inherent_risk_score, text_format)
                sheet.write(row, col + 4, line.control_effectiveness,text_format)
                sheet.write(row, col + 5, line.residual_risk_score,text_format)
                sheet.write(row, col + 6,line.owner.name,text_format)
                sheet.write(row, col + 7, line.severity,text_format)
                sheet.write(row, col + 8, line.status,text_format)
                sheet.write(row, col + 9, line.next_date,date_format)
                row += 1

        # elif data['task_type'] == 'plan_5':
        #     sheet.write('A1', "Task Name", small_head)
        #     sheet.write('B1', "Flow Chart", small_head)
        #     sheet.write('C1', "Activity Description", small_head)
        #     sheet.write('D1', "Risk Description ", small_head)
        #     sheet.write('E1', "Rating", small_head)
        #     sheet.write('F1', "Control Description", small_head)
        #     sheet.write('G1', "Control Rating", small_head)
        #     sheet.write('H1', "Residual Risk", small_head)
        #     sheet.write('I1', "Reporting", small_head)
        #     sheet.write('J1', "Audit Procedures", small_head)
        #     row = 1
        #     col = 0
        #     for line in plan.risk_analysis_id:
        #         sheet.write(row, col, plan.name, txt)
        #         sheet.write(row, col + 1, html2plaintext(line.flow_chart), txt_wrap)
        #         sheet.write(row, col + 2, html2plaintext(line.activity_description),txt_wrap)
        #         sheet.write(row, col + 3, html2plaintext(line.risk_description), txt_wrap)
        #         sheet.write(row, col + 4, html2plaintext(line.rating),txt_wrap)
        #         sheet.write(row, col + 5, html2plaintext(line.control_description),txt_wrap)
        #         sheet.write(row, col + 6, line.control_rating,text_format)
        #         sheet.write(row, col + 7, line.residual_risk,text_format)
        #         sheet.write(row, col + 8, line.reporting_point,text_format)
        #         sheet.write(row, col + 9, html2plaintext(line.audit_procedures),txt_wrap)
        #         row += 1
        elif data['task_type'] == 'plan_5':
            # ── Formats ────────────────────────────────────────────────────────
            def fmt(**kw):
                base = {
                    'font_name': 'Arial', 'font_size': 10, 'border': 1,
                    'valign': 'vcenter', 'text_wrap': True
                }
                base.update(kw)
                return workbook.add_format(base)

            meta_bold = workbook.add_format({
                'font_name': 'Arial', 'font_size': 10, 'bold': True, 'border': 1,
                'valign': 'vcenter'
            })
            meta = workbook.add_format({
                'font_name': 'Arial', 'font_size': 10, 'valign': 'vcenter'
            })
            col_hdr = fmt(bold=True, align='center', bg_color='#D9D9D9')
            sub_hdr = fmt(bold=True, align='center', bg_color='#D9D9D9',
                          font_size=9)
            cell = fmt(align='left', font_size=9)
            cell_c = fmt(align='center', font_size=9)
            label_fmt = fmt(bold=True, align='center', bg_color='#F2F2F2',
                            font_size=9)

            # ── Column widths ──────────────────────────────────────────────────
            # A=Flow Chart, B=Activity Desc, C=Risk Desc, D=Rating,
            # E=Control Desc, F=Control Rating, G=Residual Risk, H=Risk No,
            # I=Reporting Point, J=Audit Procedures
            col_widths = [14, 30, 30, 8, 30, 14, 14, 8, 20, 30]
            for i, w in enumerate(col_widths):
                sheet.set_column(i, i, w)

            def plain(val):
                if not val:
                    return ''
                if isinstance(val, str):
                    return html2plaintext(val).strip()
                return str(val)

            r = 0  # current row pointer (0-based)

            # ── META HEADER BLOCK ──────────────────────────────────────────────
            # Pulls values from the plan record — adjust field names to match
            # your actual model if they differ.
            unit_name = plan.company_id.name if plan.company_id else ''
            client = plain(getattr(plan, 'client_name', ''))
            project_name = plain(
                plan.project_id.name if plan.project_id else plan.name)
            project_number = plain(
                plan.project_id.name if plan.project_id else '')
            process = plain(getattr(plan, 'process', ''))
            fin_year = plain(getattr(plan, 'financial_year', ''))

            preparer_name = plan.user_preparer_ids.name if hasattr(plan,
                                                             'user_preparer_ids') and plan.user_preparer_ids else ''
            reviewer_name = plan.user_reviewer_2_ids.name if hasattr(plan,
                                                             'user_reviewer_2_ids') and plan.user_reviewer_2_ids else ''
            approver_name = plan.user_approver.name if hasattr(plan,
                                                             'user_approver') and plan.user_approver else ''

            try:
                preparer_date = plan.date_start.strftime(
                    '%m/%d/%Y') if plan.date_start else ''
            except Exception:
                preparer_date = ''
            try:
                reviewer_date = plan.date_end.strftime(
                    '%m/%d/%Y') if plan.date_end else ''
            except Exception:
                reviewer_date = ''

            meta_rows = [
                (unit_name, 'Prepared by', preparer_name),
                ('Client: %s' % client, 'Date', preparer_date),
                ('Project Name: %s' % project_name, 'Reviewed', reviewer_name),
                ('Project Number: %s' % project_number, 'Date', reviewer_date),
                ('Process: %s' % process, 'Approved by', approver_name),
                (fin_year, 'Date', ''),
            ]
            for left, rl, rv in meta_rows:
                sheet.merge_range(r, 0, r, 1, left, meta_bold)
                sheet.write(r, 8, rl, meta_bold)
                sheet.write(r, 9, rv, meta)
                r += 1

            r += 1  # blank spacer row

            # ── COLUMN HEADERS (2 rows) ────────────────────────────────────────
            # Row 1 – merged group labels
            sheet.merge_range(r, 0, r + 1, 0, 'Flow Chart', col_hdr)
            sheet.merge_range(r, 1, r + 1, 1, 'Activity\nDescription', col_hdr)
            sheet.merge_range(r, 2, r + 1, 2, 'Is Same as\nPrior Year', col_hdr)
            sheet.merge_range(r, 3, r, 4, 'Risk', col_hdr)
            sheet.merge_range(r, 5, r, 6, 'Control', col_hdr)
            sheet.merge_range(r, 7, r + 1, 7, 'Residual\nRisk', col_hdr)
            sheet.merge_range(r, 8, r + 1, 8, 'RISK\nNO', col_hdr)
            sheet.merge_range(r, 9, r + 1, 9, 'Reporting\nPoint', col_hdr)
            sheet.merge_range(r, 10, r + 1, 10, 'Audit Procedures', col_hdr)
            sheet.set_row(r, 25)
            r += 1
            # Row 2 – sub-headers for Risk and Control columns
            sheet.write(r, 3, 'Description', sub_hdr)
            sheet.write(r, 4, 'Rating', sub_hdr)
            sheet.write(r, 5, 'Description', sub_hdr)
            sheet.write(r, 6, 'Rating', sub_hdr)
            sheet.set_row(r, 20)
            r += 1

            # ── DATA ROWS ──────────────────────────────────────────────────────
            # Group lines by flow_chart value so the label cell can be merged
            # vertically across all rows sharing the same label (like Image 2).
            lines = plan.risk_analysis_id

            groups = []
            for line in lines:
                fc = plain(line.flow_chart)
                if groups and groups[-1][0] == fc:
                    groups[-1][1].append(line)
                else:
                    groups.append([fc, [line]])

            for fc_label, group_lines in groups:
                count = len(group_lines)

                # Merge the Flow Chart label cell vertically across all rows
                if count == 1:
                    sheet.write(r, 0, fc_label, label_fmt)
                else:
                    sheet.merge_range(r, 0, r + count - 1, 0, fc_label,
                                      label_fmt)

                for line in group_lines:
                    sheet.write(r, 1, plain(line.activity_description), cell)
                    sheet.write(r, 2,
                                'Yes' if line.is_same_prior_year else 'No',
                                cell_c)
                    sheet.write(r, 3, plain(line.risk_description), cell)
                    sheet.write(r, 4, plain(line.rating), cell_c)
                    sheet.write(r, 5, plain(line.control_description), cell)
                    sheet.write(r, 6, plain(line.control_rating), cell_c)
                    sheet.write(r, 7, plain(line.residual_risk), cell_c)
                    sheet.write(r, 8, plain(getattr(line, 'risk_no', '')),
                                cell_c)
                    sheet.write(r, 9, plain(line.reporting_point), cell)
                    sheet.write(r, 10, plain(line.audit_procedures), cell)
                    sheet.set_row(r, 60)
                    r += 1
        elif data['task_type'] == 'exec_3':
            sheet.write('A1', "Task", small_head)
            sheet.write('B1', "Audit Objectives", small_head)
            sheet.write('C1', "Audit Procedures", small_head)
            sheet.write('D1', "Sample Selection", small_head)
            sheet.write('E1', "Work Performed", small_head)
            sheet.write('F1', "Conclusion", small_head)
            row = 1
            col = 0
            # for line in plan.risk_ids:
            # categories = ', '.join(line.category.mapped('name'))
            sheet.write(row, col, plan.name, txt)
            sheet.write(row, col + 1, html2plaintext(plan.guidance), txt_wrap)
            sheet.write(row, col + 2, html2plaintext(plan.audit_steps), txt_wrap)
            sheet.write(row, col + 3, html2plaintext(plan.sample_selection), txt_wrap)
            sheet.write(row, col + 4, html2plaintext(plan.work_performed),txt_wrap)
            sheet.write(row, col + 5, html2plaintext(plan.conclusion), txt_wrap)
            row += 1

        workbook.close()
        output.seek(0)
        response.stream.write(output.read())
        output.close()

    def action_import_lines(self):
        """Method for view Audit Program importing wizard"""
        return {
            'type': 'ir.actions.act_window',
            'name': 'Import Lines',
            'res_model': 'audit.pgm.import.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_task_id': self.id,
            }
        }

    class SurveyDetails(models.Model):
        """Survey Details"""
        _name = 'survey.details'
        _description = "Survey Details"

        survey_details_id = fields.Many2one('project.task',string='Project Task')
        survey_num = fields.Html(string="No",help="Survey Number")
        item_description = fields.Html(string="Item Description",help="Item Description")
        assignment_category = fields.Many2one('audit.assignment.category',string="Assignment Category/Discipline",help="Assignment Category")
        comments = fields.Html(string="Comments", help="Comments")
        analysis = fields.Html(string="Analysis",help="Analysis")
        reference = fields.Html(string="Ref", help="Reference")


    class AuditProgram(models.Model):
        """Audit Program"""
        _name = 'audit.pgm'
        _description = "Audit Program"

        audit_details_id = fields.Many2one('project.task',
                                            string='Task')
        process = fields.Html(string='Process',help='Audit Process')
        risk_identified = fields.Html(string='Risk Identified',help='Risk Identified')
        controls_identified = fields.Html(string='Controls Identified',help='Controls Identified')
        audit_procedures = fields.Html(string='Audit Procedures to Test Control Effectiveness',help='Audit Procedures to Test Control Effectiveness')
        timeline = fields.Html(string='Timeline',help='Timeline')
        responsibility_assigned_to = fields.Html(string='Responsibility Assigned To',help='Responsibility Assigned To')
        wp_reference = fields.Html(string='WP Reference',help='WP Reference')

    class AuditProgramImportWizard(models.TransientModel):
        """Audit Program"""
        _name = 'audit.pgm.import.wizard'
        _description = 'Audit Program Import Wizard'

        file = fields.Binary(string="XLSX File", required=True)
        filename = fields.Char(string="File Name")
        task_id = fields.Many2one('project.task',string='Task')

        def action_import(self):
            """
            Import Audit Program records from an uploaded XLSX file.

            This method validates the uploaded file, reads the XLSX content,
            and creates `audit.pgm` records based on the data in the file.
            Each row in the XLSX file (starting from the second row) is mapped
            to an Audit Program entry and linked to the selected project task.

            Expected XLSX format:
                Column A : (Skipped / Identifier)
                Column B : Process
                Column C : Risk Identified
                Column D : Controls Identified
                Column E : Audit Procedures
                Column F : Timeline
                Column G : Responsibility Assigned To
                Column H : WP Reference

            Raises:
                ValidationError: If no file is uploaded or if the file format is not XLSX.

            Returns:
                dict: Action to close the wizard window after successful import.
            """
            if not self.file:
                raise ValidationError(_("Please upload an XLSX file."))

            if not self.filename or not self.filename.lower().endswith('.xlsx'):
                raise ValidationError(_("Only XLSX files are supported."))

            file_data = base64.b64decode(self.file)
            workbook = load_workbook(
                io.BytesIO(file_data),
                data_only=True,
                read_only=True
            )
            sheet = workbook.active

            AuditPgm = self.env['audit.pgm']
            Risk = self.env['business.risk']
            Category = self.env['risk.category']
            Users = self.env['res.users']
            RiskAnalysis = self.env['risk.analysis']

            for row in sheet.iter_rows(min_row=2, values_only=True):
                if not row or not row[0]:
                    continue
                if self.task_id.task_type == 'exec_1':
                    vals = {
                        'audit_details_id': self.task_id.id,
                        'process': row[1],
                        'risk_identified': row[2],
                        'controls_identified': row[3],
                        'audit_procedures': row[4],
                        'timeline': row[5],
                        'responsibility_assigned_to': row[6],
                        'wp_reference': row[7],
                    }
                    AuditPgm.create(vals)
                elif self.task_id.task_type == 'plan_8':

                    # Many2many: Category
                    category_ids = []
                    if row[2]:
                        category_names = [c.strip() for c in row[2].split(',')]
                        category_ids = Category.search([
                            ('name', 'in', category_names)
                        ]).ids

                    # Many2one: Owner
                    owner_id = False
                    if row[6]:
                        owner = Users.search([('name', '=', row[6])], limit=1)
                        owner_id = owner.id

                    next_date = False
                    cell_value = row[9]

                    if isinstance(cell_value, datetime):
                        next_date = cell_value.date()

                    elif isinstance(cell_value, date):
                        next_date = cell_value

                    elif isinstance(cell_value, time):
                        next_date = False  # ignore pure time values

                    elif isinstance(cell_value, str) and cell_value:
                        try:
                            next_date = datetime.strptime(cell_value,
                                                          '%d-%m-%Y').date()
                        except ValueError:
                            next_date = False
                    vals = {
                        'name': row[1],
                        'category': [(6, 0, category_ids)],
                        'inherent_risk_score': row[3],
                        'control_effectiveness': row[4],
                        'residual_risk_score': row[5],
                        'owner': owner_id,
                        'severity': row[7],
                        'status': row[8],
                        'next_date': next_date,
                    }
                    risk_id =  Risk.create(vals)
                    self.task_id.write({
                        'risk_ids': [(4, risk_id.id)]
                    })
                elif self.task_id.task_type == 'exec_3':
                    vals = {
                        'guidance': row[1],  # Audit Objectives
                        'audit_steps': row[2],  # Audit Procedures
                        'sample_selection': row[3],  # Sample Selection
                        'work_performed': row[4],  # Work Performed
                        'conclusion': row[5],  # Conclusion
                    }

                    # Update task directly
                    self.task_id.write(vals)

                if self.task_id.task_type == 'plan_5':
                    self._import_plan_5(sheet, RiskAnalysis)

                return {'type': 'ir.actions.act_window_close'}

        def _import_plan_5(self, sheet, RiskAnalysis):
                """
                Import risk analysis lines from a plan_5 exported template.

                Template structure:
                    Rows 1-6  : meta header block  (unit, client, project…)
                    Row  7    : blank spacer
                    Row  8    : column headers     ← detected by 'Flow Chart' in col 0
                    Row  9    : sub-headers        (Description / Rating x2)
                    Row  10+  : data rows

                Column mapping (0-based):
                    0  = Flow Chart
                    1  = Activity Description
                    2  = Is Same as Prior Year  ('Yes' / 'No')
                    3  = Risk Description
                    4  = Risk Rating
                    5  = Control Description
                    6  = Control Rating
                    7  = Residual Risk
                    8  = Risk No               ← skipped (informational only)
                    9  = Reporting Point
                    10 = Audit Procedures
                """
                all_rows = list(sheet.iter_rows(values_only=True))

                # Locate the header row by finding 'Flow Chart' in column 0
                data_start = None
                for idx, row in enumerate(all_rows):
                    if row and str(row[0] or '').strip() == 'Flow Chart':
                        data_start = idx + 2  # +1 skips header row, +1 skips sub-header row
                        break

                if data_start is None:
                    raise ValidationError(
                        _("Could not find the 'Flow Chart' header row in the uploaded "
                          "file. Please make sure you are uploading the correct template.")
                    )

                def safe(val):
                    return str(val).strip() if val not in (None, False,
                                                           '') else ''

                for row in all_rows[data_start:]:
                    # Skip blank rows
                    if not row or not any(row):
                        continue

                    # Skip rows where all meaningful columns are empty
                    if not any(row[i] for i in [0, 1, 3, 5, 10] if
                               i < len(row)):
                        continue

                    vals_line = {
                        'task_id': self.task_id.id,
                        'flow_chart': safe(row[0]),
                        'activity_description': safe(row[1]),
                        'is_same_prior_year': str(
                            row[2] or '').strip().lower() == 'yes',
                        'risk_description': safe(row[3]),
                        'rating': safe(row[4]),
                        'control_description': safe(row[5]),
                        'control_rating': safe(row[6]),
                        'residual_risk': safe(row[7]),
                        # col 8 (Risk No) intentionally skipped
                        'reporting_point': safe(row[9]) if len(
                            row) > 9 else '',
                        'audit_procedures': safe(row[10]) if len(
                            row) > 10 else '',
                    }

                    RiskAnalysis.create(vals_line)
