{
    'name': "Tender Management",
    'description': """Tender Management""",
    'summary': """Tender Management""",
    'version': '19.0.1.0.0',
    'sequence': '20',
    'category': 'Services',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'depends': ['mail', 'website', 'account_budget', 'product', 'portal', 'contacts', 'account',
                'documents', 'purchase', 'website_mail'],
    'data': [
        'security/tender_management_groups.xml',
        'security/tender_management_security.xml',
        'security/ir.model.access.csv',
        'data/mail_template.xml',
        'data/tender_sequence.xml',
        'data/bid_sequence.xml',
        'data/tender_cron.xml',
        'report/tender_report_template.xml',
        'views/tender_category.xml',
        'views/tender_bid.xml',
        'views/tender_document.xml',
        'views/tender_tender.xml',
        'views/tender_menu.xml',
        'views/entity_class.xml',
        'views/tender_information_template.xml',
        'views/dashboard_views.xml',
        'views/request_for_quotation_views.xml',
        'views/supplier_verification.xml',
        'views/vendor_registration.xml',
        'views/purchase_order_views.xml',
        'views/tender_bid_portal_views.xml',
        'views/res_partner.xml',
        'views/demand_management_views.xml',
        'views/procurement_entity.xml',
        'views/bid_award.xml',
        'views/res_config_settings_views.xml',
        # 'views/procurement_plan_views.xml',

        'views/tender_tender_template.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'tender_management/static/src/css/tender_information.css',
            'tender_management/static/src/css/vendor_registration_style.css',
            'tender_management/static/src/js/website_tender.js',
        ],
        'web.assets_backend': [
            'tender_management/static/src/css/dashboard.css',
            'tender_management/static/src/js/tender_dashboard.js',
            'tender_management/static/src/xml/tender_dashboard.xml',
        ],
    },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
