{
    'name': "Documents File Plan",
    'description': """Documents File Plan""",
    'summary': """Documents File Plan""",
    'version': '16.0.1.0.0',
    'category': 'Services',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': "https://natedsystems.co.za",
    'depends': ['documents', 'physical_document_records_manage'],
    'data': [
        'security/physical_record_security.xml',
        'security/ir.model.access.csv',
        'views/documents_document_view.xml',
        'views/physical_document_submission_view.xml',
        'views/physical_record_keeper_view.xml',
    ],
    'images': [],
    'license': 'OEEL-1',
    'installable': True,
    'application': True,
    'auto_install': False,
}
