{
    'name': 'Internal Audit Workflow',
    'version': '18.0.1.0.0',
    'category': 'Productivity',
    'author': '',
    'website': '',
    'sequence': 5,
    'summary': 'Risk Workflow',
    'description': """
    """,
    'depends': ['internal_audit_management'],
    'data': [
        'views/res_config_settings_views.xml',
        'views/internal_audit_method_views.xml',
        'views/internal_audit_plan_views.xml',
        'views/audit_universe_views.xml',
        'views/pestel_analysis_views.xml',
        'views/swot_analysis_view.xml',
        'views/rolling_plan_views.xml',
        'views/operational_plan_views.xml',
        'views/other_documents_views.xml',
        'views/audit_action_plan_views.xml',
        'views/quality_control_peer_views.xml',
        'views/quality_control_outsourced_peer.xml',
        'views/internal_quality_control_views.xml',
        'views/project_checklist_views.xml',
        'views/quality_assurance_views.xml',
        'views/financial_statement_views.xml',
        'views/client_survey_views.xml',
        'views/internal_audit_charter_views.xml',
        'views/audit_committee_charter_views.xml',
        'views/professional_development_views.xml',
        'views/audit_standards_views.xml',
        'views/minutes_meeting_views.xml',
        'views/audit_finding_views.xml',
        'views/exception_report_views.xml',
        'views/audit_strategy_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'OPL-1'
}
