{
    'name': "Cemetery Management",
    'description': """Cemetery Management.""",
    'summary': """Cemetery Management through
     online and walkin.""",
    'version': '18.0.1.5.0',
    'sequence': '20',
    'category': 'Services',
    'depends': ['base', 'auth_signup', 'mail', 'website', 'calendar',
                'contacts', 'account', 'sale_management', 'base_geolocalize'],
    'data': [
        'data/province_province_data.xml',
        'data/municipality_municipality_data.xml',
        'data/product_data.xml',
        'data/cemetery_tag_data.xml',
        'data/ir_dequence_data.xml',
        'data/mail_template_data.xml',

        'security/ir.model.access.csv',
        'security/cemetery_management_groups.xml',
        'report/cemetery_burial_report_views.xml',
        'report/cemetery_cremation_report_views.xml',
        'report/grave_cemetery_report_views.xml',

        'views/cemetery_cemetery_views.xml',
        'views/cemetery_section_views.xml',
        'views/grave_grave_views.xml',
        'views/cemetery_application_views.xml',
        'views/province_province_views.xml',
        'views/municipality_muncipality_views.xml',
        'views/auth_signup_login_templates.xml',
        'views/res_users_views.xml',
        'views/cemetery_tag_views.xml',
        'views/res_partner_views.xml',
        'views/cemetery_application_templates.xml',
        'views/cemetery_overview_views.xml',
        'views/cemetery_cemetery_public_views.xml',
        'views/grave_booking_views.xml',
        'views/grave_booking_templates.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/portal_burial_cemetery_templates.xml',
        'views/ward_ward_views.xml',

        'views/cemetery_management_menus.xml',
        'views/cause_death.xml',
        'views/funeral_parlour.xml',
        'views/death_register.xml',
        'views/crematorium_crematorium.xml',
        'views/undertaker_undertaker.xml',
        'wizard/application_verify_views.xml',
        'report/ir_actions_report.xml',
        'report/burial_cremation_report.xml',
    ],

    'assets': {
        'web.assets_frontend': [
            'cemetery_management/static/src/scss/cemetery_application.scss',
            'cemetery_management/static/src/scss/grave_application.scss',
            # 'cemetery_management/static/src/js/cemetery_attachement.js',
            'cemetery_management/static/src/js/cemetery_application.js',
            'cemetery_management/static/src/js/grave_application.js',
        ],
        'web.assets_backend': [
            "https://code.jquery.com/jquery-3.7.1.min.js",
            'cemetery_management/static/src/xml/cemetery_dashbaord.xml',
            'cemetery_management/static/src/scss/cemetery_dashboard.scss',
            'cemetery_management/static/src/js/cemetery_dashboard.js',
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'
        ]
    },
    'external_dependencies': {'python': ['geopy']},
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
