{
    'name': "Document Update",
    'description': """Document Update""",
    'summary': """Document Update""",
    'version': '19.0.1.0.0',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'sequence': '10',
    'category': 'Services',
    'depends': ['base', 'documents', 'web', 'itsys_real_estate','sign'],
    'data': [
        'data/mail_template.xml',
        # 'views/mail_template.xml',
        # 'views/building_views.xml',
        'security/ir.model.access.csv',
        'data/documents_data.xml',
        'data/cron_archive.xml',
        # 'data/document_classification_type.xml',
        # 'views/document_classification_type.xml',
        'views/document_folder.xml',
        'views/documents_document.xml',
        # 'wizard/document_classification.xml',
        'wizard/document_upload_views.xml',
    ],
    # 'assets': {
    #     'web.assets_backend': [
    # #         'document_update/static/src/css/workspace_scroll.css',
    # #         'document_update/static/src/views/document_inspector.js', need to check in v19
    # #         'document_update/static/src/views/documents_inspector.xml', need to check in v19
    #         # 'document_update/static/src/views/documens_controller_mixins.js',
    #         # 'document_update/static/src/views/document_kanban_floder.js',
    #     ],
    # },
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
