from . import project
from . import court
from . import court_judge
from . import project_task
from . import law_document_name
from . import trust_account
from . import calendar_event
from . import account_move
from . import crm_lead
from . import law_task_list
from . import res_partner
from . import res_users
from . import hr_expense
from . import hr_employee
from . import crime_type
from . import legal_subtype
from . import helpdesk_ticket
