from odoo import fields, models


class CSD(models.Model):
    _name = "csd.sage"
    _rec_name = 'csd_name'

    csd_partner_id = fields.Many2one('res.partner',string='Partner')
    csd_name = fields.Char(string='Name', description='Supplier Legal Name')
    csd_title = fields.Char(string='Title', description='Supplier Contact Person Title')
    csd_initial = fields.Char(string='Initials', description='Initials')
    contact_person = fields.Char(string='Contact Person', description='Full Name and Surname')
    # Address fields
    street = fields.Char('Street')
    street2 = fields.Char('Street2')
    zip = fields.Char('Zip', change_default=True)
    city = fields.Char('City')
    state_id = fields.Many2one(
        "res.country.state", string='State',
        domain="[('country_id', '=?', country_id)]")
    country_id = fields.Many2one(
        'res.country', string='Country')
    post_street = fields.Char('Street')
    post_street2 = fields.Char('Street2')
    post_zip = fields.Char('Zip', change_default=True)
    post_city = fields.Char('City')
    post_state_id = fields.Many2one(
        "res.country.state", string='State',
        domain="[('country_id', '=?', post_country_id)]")
    post_country_id = fields.Many2one(
        'res.country', string='Country')
    telephone_1 = fields.Char(string='Telephone')
    telephone_2 = fields.Char(string='Telephone')
    fax_1 = fields.Char(string='Fax Number')
    fax_2 = fields.Char(string='Fax Number')
    tax_number = fields.Char(string='Tax Number')
    registration = fields.Char(string='CIPC/Company  Registration number')
    email = fields.Char(string='Supplier Email')
    branch_code = fields.Char(string='Bank Branch Code')
    bank_acc_num = fields.Char(string='Bank Account Number')
    bank_acc_type = fields.Char(string='Bank Account Type')
    c_bank_acc_holder = fields.Char(string='Bank Account Holder')
    c_id_number = fields.Char(string='Preferred Contact ID Number')
    c_passport_number = fields.Char(string='Preferred Contact Passport Number')
    ub_ap_tax_clearance_cert_valid = fields.Char(string='Tax Clearance Certificate Valid')
    ub_ap_tax_clearance_cert_expiry = fields.Char(string='Tax Clearance Certificate Expiry Date')
    uc_ap_csd_supplier_id = fields.Char(string='CSD Supplier ID')
    uc_ap_csd_in_active = fields.Boolean(string='CSD Inactive/Active')
    uc_ap_csd_on_hold = fields.Char(string='CSD On Hold Status')
    uc_ap_commodity_1 = fields.Char(string='CSD Commodity 1')
    uc_ap_commodity_2 = fields.Char(string='CSD Commodity 2')
    uc_ap_commodity_3 = fields.Char(string='CSD Commodity 3')
    uc_ap_commodity_4 = fields.Char(string='CSD Commodity 4')
    uf_ap_black_ownership = fields.Char(string='% Black Ownership')
    uf_ap_black_woman_ownership = fields.Char(string='% Black Women Ownership')
    uf_ap_empowering_supplier = fields.Boolean(string='Is Supplier an Empowering Supplier')
    uf_ap_value_adding_supplier = fields.Boolean(string='Is Supplier an Value Adding Supplier')
    uf_ap_black_youth = fields.Boolean(string='Is Supplier Black Youth')
    uf_ap_black_disabled = fields.Boolean(string='Is Supplier Disabled')
    uf_ap_director_surname_1 = fields.Char(string='Supplier Director 1 Surname')
    uf_ap_director_surname_2 = fields.Char(string='Supplier Director 2 Surname')
    uf_ap_director_surname_3 = fields.Char(string='Supplier Director 3 Surname')
    uf_ap_director_surname_4 = fields.Char(string='Supplier Director 4 Surname')
    uf_ap_director_surname_5 = fields.Char(string='Supplier Director 5 Surname')
    uf_ap_director_surname_6 = fields.Char(string='Supplier Director 6 Surname')
    uf_ap_director_surname_7 = fields.Char(string='Supplier Director 7 Surname')
    uf_ap_director_surname_8 = fields.Char(string='Supplier Director 8 Surname')
    uf_ap_director_surname_9 = fields.Char(string='Supplier Director 9 Surname')
    uf_ap_director_surname_10 = fields.Char(string='Supplier Director 10 Surname')
    uf_ap_director_name_1 = fields.Char(string='Supplier Director 1 Name')
    uf_ap_director_name_2 = fields.Char(string='Supplier Director 2 Name')
    uf_ap_director_name_3 = fields.Char(string='Supplier Director 3 Name')
    uf_ap_director_name_4 = fields.Char(string='Supplier Director 4 Name')
    uf_ap_director_name_5 = fields.Char(string='Supplier Director 5 Name')
    uf_ap_director_name_6 = fields.Char(string='Supplier Director 6 Name')
    uf_ap_director_name_7 = fields.Char(string='Supplier Director 7 Name')
    uf_ap_director_name_8 = fields.Char(string='Supplier Director 8 Name')
    uf_ap_director_name_9 = fields.Char(string='Supplier Director 9 Name')
    uf_ap_director_name_10 = fields.Char(string='Supplier Director 10 Name')
    uf_ap_director_id_1 = fields.Char(string='Supplier Director 1 ID')
    uf_ap_director_id_2 = fields.Char(string='Supplier Director 2 ID')
    uf_ap_director_id_3 = fields.Char(string='Supplier Director 3 ID')
    uf_ap_director_id_4 = fields.Char(string='Supplier Director 4 ID')
    uf_ap_director_id_5 = fields.Char(string='Supplier Director 5 ID')
    uf_ap_director_id_6 = fields.Char(string='Supplier Director 6 ID')
    uf_ap_director_id_7 = fields.Char(string='Supplier Director 7 ID')
    uf_ap_director_id_8 = fields.Char(string='Supplier Director 8 ID')
    uf_ap_director_id_9 = fields.Char(string='Supplier Director 9 ID')
    uf_ap_director_id_10 = fields.Char(string='Supplier Director 10 ID')
    uc_ap_status_level_contributor = fields.Char(string='BBBEE Certificate: Status Level Of Contributor ID')
    ud_ap_certificate_issue_expiry_date = fields.Char(string='BBBEE Certificate: Certificate Issue Expiry Date')
    ud_ap_vat_number = fields.Char(string='Supplier Vat Number')
    ud_ap_income_tax_number = fields.Char(string='Supplier IncomeTax Number')
    uc_ap_csd_bank_account_status = fields.Char(string='Supplier CSD Bank Account Status Verification')
    uc_ap_csd_tax_validation_response = fields.Char(string='Supplier CSD Tax Validation Response')
    uc_ap_csd_trading_name = fields.Char(string='Supplier CSD Trading Name')

