from odoo import fields, models


class ResPartner(models.Model):
    _inherit = "res.partner"


    csd_details_id = fields.One2many('csd.sage','csd_partner_id',string='Name',description='Supplier')

    csd_titles = fields.Char(string='Title', description='Supplier Contact Person Title')
    csd_initials = fields.Char(string='Initials', description='Initials')
    telephones_1 = fields.Char(string='Telephone')
    telephones_2 = fields.Char(string='Telephone')
    faxs_1 = fields.Char(string='Fax Number')
    faxs_2 = fields.Char(string='Fax Number')
    registrations = fields.Char(string='CIPC/Company  Registration number')
    c_id_numbers = fields.Char(string='Preferred Contact ID Number')
    c_passport_numbers = fields.Char(string='Preferred Contact Passport Number')
    ub_ap_tax_clearance_cert_valids = fields.Char(string='Tax Clearance Certificate Valid')
    ub_ap_tax_clearance_cert_expirys = fields.Char(string='Tax Clearance Certificate Expiry Date')
    uc_ap_csd_supplier_ids = fields.Char(string='CSD Supplier ID')
    uc_ap_csd_in_actives = fields.Boolean(string='CSD Inactive/Active')
    uc_ap_csd_on_holds = fields.Char(string='CSD On Hold Status')
    uc_ap_commoditys_1 = fields.Char(string='CSD Commodity 1')
    uc_ap_commoditys_2 = fields.Char(string='CSD Commodity 2')
    uc_ap_commoditys_3 = fields.Char(string='CSD Commodity 3')
    uc_ap_commoditys_4 = fields.Char(string='CSD Commodity 4')
    uf_ap_black_ownerships = fields.Char(string='% Black Ownership')
    uf_ap_black_woman_ownerships = fields.Char(string='% Black Women Ownership')
    uf_ap_empowering_suppliers = fields.Boolean(string='Is Supplier an Empowering Supplier')
    uf_ap_value_adding_suppliers = fields.Boolean(string='Is Supplier an Value Adding Supplier')
    uf_ap_black_youths = fields.Boolean(string='Is Supplier Black Youth')
    uf_ap_blacks_disabled = fields.Boolean(string='Is Supplier Disabled')
    uf_ap_directors_surname_1 = fields.Char(string='Supplier Director 1 Surname')
    uf_ap_directors_surname_2 = fields.Char(string='Supplier Director 2 Surname')
    uf_ap_directors_surname_3 = fields.Char(string='Supplier Director 3 Surname')
    uf_ap_directors_surname_4 = fields.Char(string='Supplier Director 4 Surname')
    uf_ap_directors_surname_5 = fields.Char(string='Supplier Director 5 Surname')
    uf_ap_directors_surname_6 = fields.Char(string='Supplier Director 6 Surname')
    uf_ap_directors_surname_7 = fields.Char(string='Supplier Director 7 Surname')
    uf_ap_directors_surname_8 = fields.Char(string='Supplier Director 8 Surname')
    uf_ap_directors_surname_9 = fields.Char(string='Supplier Director 9 Surname')
    uf_ap_directors_surname_10 = fields.Char(string='Supplier Director 10 Surname')
    uf_ap_directors_name_1 = fields.Char(string='Supplier Director 1 Name')
    uf_ap_directors_name_2 = fields.Char(string='Supplier Director 2 Name')
    uf_ap_directors_name_3 = fields.Char(string='Supplier Director 3 Name')
    uf_ap_directors_name_4 = fields.Char(string='Supplier Director 4 Name')
    uf_ap_directors_name_5 = fields.Char(string='Supplier Director 5 Name')
    uf_ap_directors_name_6 = fields.Char(string='Supplier Director 6 Name')
    uf_ap_directors_name_7 = fields.Char(string='Supplier Director 7 Name')
    uf_ap_directors_name_8 = fields.Char(string='Supplier Director 8 Name')
    uf_ap_directors_name_9 = fields.Char(string='Supplier Director 9 Name')
    uf_ap_directors_name_10 = fields.Char(string='Supplier Director 10 Name')
    uf_ap_directors_id_1 = fields.Char(string='Supplier Director 1 ID')
    uf_ap_directors_id_2 = fields.Char(string='Supplier Director 2 ID')
    uf_ap_directors_id_3 = fields.Char(string='Supplier Director 3 ID')
    uf_ap_directors_id_4 = fields.Char(string='Supplier Director 4 ID')
    uf_ap_directors_id_5 = fields.Char(string='Supplier Director 5 ID')
    uf_ap_directors_id_6 = fields.Char(string='Supplier Director 6 ID')
    uf_ap_directors_id_7 = fields.Char(string='Supplier Director 7 ID')
    uf_ap_directors_id_8 = fields.Char(string='Supplier Director 8 ID')
    uf_ap_directors_id_9 = fields.Char(string='Supplier Director 9 ID')
    uf_ap_directors_id_10 = fields.Char(string='Supplier Director 10 ID')
    uc_ap_status_level_contributors = fields.Char(string='BBBEE Certificate: Status Level Of Contributor ID')
    ud_ap_certificate_issues_expiry_date = fields.Char(string='BBBEE Certificate: Certificate Issue Expiry Date')
    ud_ap_vat_numbers = fields.Char(string='Supplier Vat Number')
    ud_ap_income_tax_numbers = fields.Char(string='Supplier IncomeTax Number')
    uc_ap_csd_bank_accounts_status = fields.Char(string='Supplier CSD Bank Account Status Verification')
    uc_ap_csd_tax_validation_responses = fields.Char(string='Supplier CSD Tax Validation Response')
    uc_ap_csd_trading_names = fields.Char(string='Supplier CSD Trading Name')