
{
    'name': 'SCM Skills Audit (National Treasury)',
    'version': '16.0.1.0.0',
    'summary': 'Automated SCM Skills Audit aligned with National Treasury SCM Technical Competency Dictionary (2015)',
    'author': 'Skills Audit Project',
    'category': 'Human Resources',
    'license': 'LGPL-3',
    'depends': ['base', 'hr', 'mail'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/clusters_competencies.xml',
        'data/competency_definitions.xml',
        'data/ir_cron.xml',
        'data/demo_training.xml',
        'report/profile_report.xml',
        'views/menu.xml',
        'views/cluster_views.xml',
        'views/competency_views.xml',
        'views/job_role_views.xml',
        'views/employee_profile_views.xml',
        'views/assessment_views.xml',
        'views/training_views.xml',
        'views/wizard_views.xml',
    ],
    'images': ['static/description/icon.png'],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
}
