{
    'name': "Contract Update",
    'description': """Contract Update""",
    'summary': """Contract Update""",
    'version': '19.0.1.0.0',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': 'https://natedsystems.co.za/',
    'sequence': '20',
    'category': 'Services',
    'depends': ['xf_partner_contract', 'xf_partner_contract_purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/xf_partner_contract_views.xml',
        # 'views/property_zoning_views.xml',
        # 'views/property_contract_views.xml',
        # 'views/property_zoning_views.xml',
        # 'views/creditor_region_views.xml',
        # 'views/outdoor_advertisement_views.xml',
        # 'views/region_views.xml',
        # 'views/trade_rent_views.xml',
        # 'wizard/trade_rent_import_views.xml',
        # 'wizard/property_import_views.xml',
        # 'wizard/outdoor_advertisement_import_views.xml',
        # 'wizard/property_contract_import_views.xml'
    ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
