# -*- coding: utf-8 -*-
{
    'name': "E-system Management",
    'version': '18.0.1.0.0',
    "summary": "Manage internal memos,circular and procuremtn with approval, signature, and acknowledgment",
    'category': 'Services',
    'author': 'Nated Systems',
    'company': 'Nated Systems',
    'maintainer': 'Nated Systems',
    'website': "https://natedsystems.co.za",
    "depends": ["base", "web", "hr", "mail", "sign", "documents", "ecdhs_base"],
    "data": [
        "security/memo_security.xml",
        "security/ir.model.access.csv",
        "data/memo_sequence.xml",
        "data/circular_sequence.xml",
        "data/procurement_sequence.xml",
        "data/email_template.xml",
        "data/ir_cron.xml",
        "wizard/memo_email_wizard_views.xml",
        "wizard/signature_wizard_views.xml",
        "wizard/memo_action_wizard_view.xml",
        'report/memo_template.xml',
        'report/memo_report.xml',
        'report/circular_template.xml',
        'report/circular_report.xml',
        'report/procurement_template.xml',
        'report/procurement_report.xml',
        "views/memo_views.xml",
        "views/memo_dashboard_views.xml",
        "views/circular_dashboard_views.xml",
        "views/procurement_dashboard_views.xml",
        "views/general_dashbord_views.xml",
        "views/memo_menu.xml",
        "views/memo_template_views.xml",
        "views/hr_department_view.xml",
        "views/sign_item_role_view.xml",
        "views/sign_item_option_views.xml",
        "views/sign_refuse_reason_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "e_system/static/src/js/custom_name_and_signature.js",
            "e_system/static/src/js/sign_item_option_no_create.js",
            "e_system/static/src/js/sign_refusal_dialog_patch.js",
            "e_system/static/src/css/overrides_sign_item_pdfview.css",
            "e_system/static/src/css/overrides_sign_frame_active.scss",
        ],
        "web.assets_frontend": [
            "e_system/static/src/js/custom_name_and_signature.js",
            "e_system/static/src/css/overrides_sign_item_pdfview.css",
            "e_system/static/src/css/overrides_sign_frame_active.scss",
        ],
        "sign.assets_public_sign": [
            "e_system/static/src/js/custom_name_and_signature.js",
            "e_system/static/src/js/sign_refusal_dialog_patch.js",
            "e_system/static/src/css/overrides_sign_item_pdfview.css",
            "e_system/static/src/css/overrides_sign_frame_active.scss",
        ],
        "sign.assets_pdf_iframe":[
            "e_system/static/src/css/overrides_sign_item_pdfview.css",
        ],
    },
    'qweb': [],
    'images': [],
    'license': 'OEEL-1',
    'installable': True,
    'application': True,
    'auto_install': False,
}
